"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
type Envelope<T>={data:T;message?:string;error?:string};
type Summary={run:null|{id:string;lookbackDays:number;completedAt:string};summary:{supplierCount:number;preferredSupplierCount:number;gradeA:number;gradeB:number;gradeC:number;gradeD:number;totalSpend:number;averageScore:number;averageOnTime:number;averageQuality:number;averageFillRate:number};topSuppliers:SupplierRow[];spendLeaders:SupplierRow[]};
type SupplierRow={_id:string;supplierName:string;supplierCode:string;isActive:boolean;purchaseOrderCount:number;totalSpend:number;averageOrderValue:number;fillRatePercent:number;rejectionRatePercent:number;qualityScore:number;onTimeDeliveryPercent:number;averageLeadTimeDays:number;averageDelayDays:number;purchasePriceVariancePercent:number;returnValue:number;overallScore:number;grade:string;preferredSupplier:boolean;recommendation:string};
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
function unwrap<T>(payload:Envelope<T>|T):T{return typeof payload==="object"&&payload!==null&&"data" in payload?(payload as Envelope<T>).data:payload as T;}
async function request<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers??{})}});const payload=await response.json() as Envelope<T>;if(!response.ok)throw new Error(payload.message??payload.error??"Request failed.");return unwrap(payload);}
export function SupplierIntelligenceDashboardClient({canManage,canExport}:{canManage:boolean;canExport:boolean}){
 const [summary,setSummary]=useState<Summary|null>(null),[rows,setRows]=useState<SupplierRow[]>([]),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[grade,setGrade]=useState(""),[preferred,setPreferred]=useState(""),[lookbackDays,setLookbackDays]=useState(365);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const q=new URLSearchParams({limit:"100",...(search.trim()?{search:search.trim()}:{}),...(grade?{grade}:{}),...(preferred?{preferredSupplier:preferred}:{})});const [s,i]=await Promise.all([request<Summary>("/api/v1/admin/suppliers/intelligence/summary"),request<{rows:SupplierRow[]}>(`/api/v1/admin/suppliers/intelligence/items?${q}`)]);setSummary(s);setRows(i.rows);}catch(e){setError(e instanceof Error?e.message:"Unable to load supplier intelligence.");}finally{setLoading(false);}},[search,grade,preferred]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t);},[load]);
 async function generate(){setWorking(true);setError("");setNotice("");try{await request("/api/v1/admin/suppliers/intelligence/run",{method:"POST",body:JSON.stringify({lookbackDays,source:"manual"})});setNotice("Supplier scorecards and recommendations generated.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to generate supplier intelligence.");}finally{setWorking(false);}}
 const cards=useMemo(()=>[["Suppliers",String(summary?.summary.supplierCount??0)],["Preferred suppliers",String(summary?.summary.preferredSupplierCount??0)],["Average score",`${Number(summary?.summary.averageScore??0).toFixed(1)}%`],["On-time delivery",`${Number(summary?.summary.averageOnTime??0).toFixed(1)}%`],["Average quality",`${Number(summary?.summary.averageQuality??0).toFixed(1)}%`],["Purchase spend",money.format(summary?.summary.totalSpend??0)]],[summary]);
 if(loading&&!summary)return <div className="rounded-3xl border border-neutral-200 bg-white p-8">Loading supplier intelligence…</div>;
 return <div className="space-y-6">
  <section className="rounded-3xl bg-neutral-950 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-amber-400">Phase 6 intelligence</p><div className="mt-2 flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><h1 className="text-3xl font-black">Supplier Intelligence</h1><p className="mt-2 max-w-3xl text-sm text-neutral-300">Rank suppliers using delivery reliability, fill rate, quality, price stability, returns, lead time, and actual purchase history.</p></div>{canManage?<div className="flex items-end gap-2"><label className="text-xs text-neutral-300">Analysis period<select value={lookbackDays} onChange={e=>setLookbackDays(Number(e.target.value))} className="mt-1 block rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-white"><option className="text-black" value={90}>90 days</option><option className="text-black" value={180}>180 days</option><option className="text-black" value={365}>365 days</option><option className="text-black" value={730}>2 years</option></select></label><button disabled={working} onClick={()=>void generate()} className="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-black hover:bg-red-500 disabled:opacity-50">{working?"Generating…":"Generate scorecards"}</button></div>:null}</div></section>
  {error?<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>:null}{notice?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{notice}</div>:null}
  {!summary?.run?<section className="rounded-3xl border border-dashed border-neutral-300 bg-white p-10 text-center"><h2 className="text-xl font-black">No supplier intelligence run yet</h2><p className="mt-2 text-sm text-neutral-500">Generate scorecards from purchase orders, receipts, rejections, returns, delivery dates, and item prices.</p></section>:<>
   <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value])=><div key={label} className="rounded-3xl border border-neutral-200 bg-white p-5 shadow-sm"><p className="text-sm text-neutral-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</div>
   <section className="rounded-3xl border border-neutral-200 bg-white p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-black">Supplier scorecards</h2><p className="mt-1 text-xs text-neutral-500">Last generated {new Date(summary.run.completedAt).toLocaleString()} using {summary.run.lookbackDays} days.</p></div><div className="flex flex-wrap gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search supplier or code" className="rounded-xl border px-3 py-2 text-sm"/><select value={grade} onChange={e=>setGrade(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="">All grades</option><option>A</option><option>B</option><option>C</option><option>D</option></select><select value={preferred} onChange={e=>setPreferred(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="">All suppliers</option><option value="true">Preferred</option><option value="false">Not preferred</option></select><button onClick={()=>void load()} className="rounded-xl bg-neutral-950 px-4 py-2 text-sm font-bold text-white">Apply</button>{canExport?<><Link prefetch={false} href="/api/v1/admin/suppliers/intelligence/export/xlsx" className="rounded-xl border px-4 py-2 text-sm font-bold">Excel</Link><Link prefetch={false} href="/api/v1/admin/suppliers/intelligence/export/pdf" className="rounded-xl border px-4 py-2 text-sm font-bold">PDF</Link></>:null}</div></div>
    <div className="mt-5 overflow-x-auto"><table className="min-w-[1450px] w-full text-sm"><thead><tr className="border-b text-left text-neutral-500"><th className="py-3">Supplier</th><th>Grade</th><th>Score</th><th>Preferred</th><th>Orders</th><th>Spend</th><th>On time</th><th>Lead time</th><th>Delay</th><th>Fill rate</th><th>Rejection</th><th>Quality</th><th>Price variance</th><th>Returns</th><th>Recommendation</th></tr></thead><tbody>{rows.map(row=><tr key={row._id} className="border-b border-neutral-100 align-top"><td className="py-3"><p className="font-bold">{row.supplierName}</p><p className="text-xs text-neutral-500">{row.supplierCode}</p></td><td className="font-black">{row.grade}</td><td className="font-black">{row.overallScore.toFixed(1)}</td><td>{row.preferredSupplier?"Yes":"No"}</td><td>{row.purchaseOrderCount}</td><td>{money.format(row.totalSpend)}</td><td>{row.onTimeDeliveryPercent.toFixed(1)}%</td><td>{row.averageLeadTimeDays.toFixed(1)} days</td><td>{row.averageDelayDays.toFixed(1)} days</td><td>{row.fillRatePercent.toFixed(1)}%</td><td>{row.rejectionRatePercent.toFixed(1)}%</td><td>{row.qualityScore.toFixed(1)}%</td><td>{row.purchasePriceVariancePercent>=0?"+":""}{row.purchasePriceVariancePercent.toFixed(1)}%</td><td>{money.format(row.returnValue)}</td><td className="max-w-sm text-xs text-neutral-600">{row.recommendation}</td></tr>)}</tbody></table>{rows.length===0?<p className="py-8 text-center text-sm text-neutral-500">No suppliers match these filters.</p>:null}</div>
   </section>
   <section className="grid gap-4 xl:grid-cols-2"><div className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Top-ranked suppliers</h2><div className="mt-4 space-y-3">{summary.topSuppliers.map((row,index)=><div key={row._id} className="flex items-center justify-between rounded-2xl bg-neutral-50 p-4"><div><p className="font-bold">#{index+1} {row.supplierName}</p><p className="text-xs text-neutral-500">Grade {row.grade} · {row.onTimeDeliveryPercent.toFixed(1)}% on time</p></div><p className="text-2xl font-black">{row.overallScore.toFixed(1)}</p></div>)}</div></div><div className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Spend leaders</h2><div className="mt-4 space-y-3">{summary.spendLeaders.map(row=><div key={row._id} className="flex items-center justify-between rounded-2xl bg-neutral-50 p-4"><div><p className="font-bold">{row.supplierName}</p><p className="text-xs text-neutral-500">{row.purchaseOrderCount} purchase orders</p></div><p className="text-xl font-black">{money.format(row.totalSpend)}</p></div>)}</div></div></section>
  </>}
 </div>;
}
