export const routes = {
  public: {
    home: "/",
    menu: "/menu",
    offers: "/offers",
    about: "/about",
    trackOrder: "/track-order",
    contact: "/contact",
    faq: "/faq",
    rewards: "/rewards",
    cart: "/cart",
    checkout: "/checkout",
    order: "/order",
    orderSuccess: "/order/success",
    item: (slug: string) => `/menu/${slug}`,
  },
  auth: {
    login: "/login",
    signup: "/signup",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    verifyEmail: "/verify-email",
    verifyOtp: "/verify-otp",
  },
  account: {
    root: "/account",
    orders: "/account/orders",
    order: (id: string) => `/account/orders/${id}`,
    reservations: "/account/reservations",
    rewards: "/account/rewards",
    favourites: "/account/favourites",
    reviews: "/account/reviews",
    notifications: "/account/notifications",
    profile: "/account/profile",
    settings: "/account/settings",
  },
  legal: {
    terms: "/terms",
    privacy: "/privacy",
    refund: "/refund-policy",
    rewards: "/rewards-terms",
    offers: "/offer-terms",
  },
  admin: {
    dashboard: "/admin/dashboard",
    orders: "/admin/orders",
    order: (id: string) => `/admin/orders/${id}`,
    menu: "/admin/menu",
    inventory: "/admin/inventory",
    reservations: "/admin/reservations",
    customers: "/admin/customers",
    customer: (id: string) => `/admin/customers/${id}`,
    rewards: "/admin/rewards",
    coupons: "/admin/coupons",
    offers: "/admin/coupons",
    spinWheel: "/admin/spin-wheel",
    referrals: "/admin/referrals",
    reviews: "/admin/reviews",
    notifications: "/admin/notifications",
    reports: "/admin/reports",
    analytics: "/admin/analytics",
    roles: "/admin/roles",
    settings: "/admin/settings",
    activityLogs: "/admin/activity-logs",
  },
  operations: {
    pos: "/pos",
    kds: "/admin/kds",
    shifts: "/pos/shifts",
    receipts: "/pos/receipts",
  },
} as const;
