"use client";

import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faStar } from "@fortawesome/free-solid-svg-icons";
import { MediaPlaceholder } from "@/components/site/MediaPlaceholder";
import { formatPrice, type Tab } from "@/components/menu-item/menu-item-utils";
import type { MenuItemDetails } from "@/types/menu";

export function MenuItemMediaDetails({item,activeTab,onTabChange}:{item:MenuItemDetails;activeTab:Tab;onTabChange:(tab:Tab)=>void}){
 const gallery=item.media.length?item.media:[];
 return <div className="min-w-0"><div className="relative overflow-hidden rounded-[2rem] border border-[#E8D8C9] bg-white shadow-[0_24px_60px_rgba(50,30,15,.08)]">{item.isBestseller&&<span className="absolute left-4 top-4 z-10 rounded-full bg-[#C8102E] px-4 py-2 text-[9px] font-black uppercase text-white">Bestseller</span>}{gallery[0]?.url?<img src={gallery[0].url} alt={gallery[0].alt||item.name} className="aspect-[4/3] w-full object-cover"/>:<MediaPlaceholder label={`${item.name} main image`} className="aspect-[4/3] w-full border-0"/>}</div>
 {gallery.length>1&&<div className="mt-4 grid grid-cols-4 gap-3 sm:grid-cols-5">{gallery.slice(0,5).map(media=><div key={media.id} className="overflow-hidden rounded-xl border border-[#E8D8C9] bg-white"><img src={media.url} alt={media.alt} className="aspect-square w-full object-cover"/></div>)}</div>}
 <ItemTabs item={item} activeTab={activeTab} onTabChange={onTabChange}/><RelatedItems item={item}/></div>
}

function ItemTabs({item,activeTab,onTabChange}:{item:MenuItemDetails;activeTab:Tab;onTabChange:(tab:Tab)=>void}){
 const tabs:Tab[]=["description","ingredients","nutrition","reviews"];
 return <div className="mt-8"><div className="flex gap-5 overflow-x-auto border-b border-[#EDE3D8]">{tabs.map(tab=><button key={tab} type="button" onClick={()=>onTabChange(tab)} className={`shrink-0 border-b-2 pb-3 text-[10px] font-black uppercase ${activeTab===tab?"border-[#C8102E] text-[#C8102E]":"border-transparent text-[#655E57]"}`}>{tab}{tab==="reviews"&&item.reviewSummary?` (${item.reviewSummary.totalReviews})`:""}</button>)}</div><div className="min-h-[130px] py-6 text-sm leading-7 text-[#625B55]">{activeTab==="description"&&<p>{item.description}</p>}{activeTab==="ingredients"&&<div className="flex flex-wrap gap-2">{(item.ingredients?.length?item.ingredients:["Ingredient information will be added from admin"]).map(ingredient=><span key={ingredient} className="rounded-full border border-[#E8D8C9] bg-white px-4 py-2 text-[10px] font-semibold">{ingredient}</span>)}</div>}{activeTab==="nutrition"&&<div className="grid gap-3 sm:grid-cols-2">{item.nutrition?Object.entries(item.nutrition).map(([key,value])=><div key={key} className="rounded-xl border border-[#EDE3D8] bg-white p-4"><strong className="block text-[9px] uppercase text-[#C8102E]">{key.replace(/([A-Z])/g," $1")}</strong><span className="mt-1 block text-sm font-bold">{String(value)}</span></div>):<p>Nutrition details will be maintained from the admin dashboard.</p>}</div>}{activeTab==="reviews"&&<div className="rounded-2xl border border-[#EDE3D8] bg-white p-5"><div className="flex items-center gap-3"><FontAwesomeIcon icon={faStar} className="h-5 text-[#E8A53A]"/><strong className="text-2xl">{item.reviewSummary?.averageRating??"New"}</strong><span className="text-[10px]">{item.reviewSummary?`${item.reviewSummary.totalReviews} verified reviews`:"No published reviews yet"}</span></div></div>}</div></div>
}

function RelatedItems({item}:{item:MenuItemDetails}){const related=item.frequentlyOrderedWith?.length?item.frequentlyOrderedWith:(item.relatedItems??[]);return <section className="mt-6"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-black uppercase">Mostly Bought Together</h2><Link href={`/menu?category=${encodeURIComponent(item.category.slug)}`} className="text-[9px] font-black uppercase text-[#C8102E]">View Category</Link></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{related.slice(0,6).map(entry=><Link key={entry.id} href={`/menu/${entry.slug}`} className="overflow-hidden rounded-2xl border border-[#EDE3D8] bg-white transition hover:-translate-y-1 hover:border-[#C8102E]">{entry.thumbnail?.url?<img src={entry.thumbnail.url} alt={entry.thumbnail.alt} className="aspect-[4/3] w-full object-cover"/>:<MediaPlaceholder label={`${entry.name} image`} className="aspect-[4/3] w-full border-0"/>}<div className="p-4"><h3 className="text-sm font-black">{entry.name}</h3><p className="mt-2 text-sm font-black text-[#C8102E]">From {formatPrice(entry.priceFrom)}</p></div></Link>)}</div></section>}
