"use client";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCheck, faMinus, faPlus } from "@fortawesome/free-solid-svg-icons";
import { formatPrice, getChoicePrice, type SelectedOptionState } from "@/components/menu-item/menu-item-utils";
import { isFullPortion } from "@/lib/mixed-naan";
import type { MenuItemDetails, MenuOptionGroup } from "@/types/menu";

export function MenuItemConfiguration({item,visibleGroups,selectedPriceOptionId,selectedPriceOptionLabel,selectedOptions,mixedSecondNaanId,selectedMixedNaanName,mixedNaanPrice,basePrice,onPriceOptionChange,onChoiceChange,onMixedNaanChange}:{item:MenuItemDetails;visibleGroups:MenuOptionGroup[];selectedPriceOptionId:string;selectedPriceOptionLabel?:string;selectedOptions:SelectedOptionState;mixedSecondNaanId:string;selectedMixedNaanName?:string;mixedNaanPrice:number|null;basePrice:number;onPriceOptionChange:(id:string,label:string)=>void;onChoiceChange:(group:MenuOptionGroup,choiceId:string,nextQuantity?:number)=>void;onMixedNaanChange:(id:string)=>void}){
 return <><h2 className="text-lg font-black uppercase text-[#C8102E]">Customise Your Order</h2>
 {item.pricingOptions&&item.pricingOptions.length>0&&<div className="mt-6"><div className="flex items-center justify-between gap-3"><h3 className="text-[10px] font-black uppercase">Select Size / Portion</h3><span className="text-[8px] text-[#8A8179]">Required</span></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{item.pricingOptions.filter(option=>option.isAvailable!==false).map(option=>{const selected=option.id===selectedPriceOptionId;return <button key={option.id} type="button" onClick={()=>onPriceOptionChange(option.id,option.label)} className={`relative rounded-xl border p-3 text-center transition ${selected?"border-[#C8102E] bg-[#FFF3F3]":"border-[#E5D9CD] bg-[#FFFDF9]"}`}>{selected&&<span className="absolute right-2 top-2 grid h-5 w-5 place-items-center rounded-full bg-[#C8102E] text-white"><FontAwesomeIcon icon={faCheck} className="h-2"/></span>}<span className="block text-[9px] font-black">{option.label}</span>{!item.combinationPricing?.enabled&&<span className="mt-1 block text-sm font-black">{formatPrice(option.price)}</span>}</button>})}</div></div>}
 <div className="mt-6 grid gap-6">{visibleGroups.map(group=><OptionGroup key={group.id} group={group} selected={selectedOptions[group.id]??{}} variantLabel={selectedPriceOptionLabel} onChoiceChange={onChoiceChange}/>)}</div>
 {isFullPortion(selectedPriceOptionLabel??"")&&(item.mixedNaanOptions?.length??0)>0&&<section className="rounded-[1.5rem] border border-[#E8D8C9] bg-white p-5"><h3 className="text-sm font-black text-[#172536]">Choose a different second naan</h3><p className="mt-1 text-[10px] font-semibold leading-5 text-[#655E57]">Optional. A Full platter includes two naans. Keep the default for two {item.name}, or choose another naan below. The higher Full-platter price applies.</p><select value={mixedSecondNaanId} onChange={e=>onMixedNaanChange(e.currentTarget.value)} className="mt-4 h-12 w-full rounded-xl border border-[#DCCEC1] bg-white px-4 text-sm font-bold outline-none focus:border-[#C8102E]"><option value="">Two {item.name}</option>{item.mixedNaanOptions?.map(option=><option key={option.menuItemId} value={option.menuItemId}>1 {item.name} + 1 {option.name}</option>)}</select>{selectedMixedNaanName&&mixedNaanPrice!=null?<p className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-[10px] font-bold text-amber-900">Mixed Full platter price: {formatPrice(Math.max(basePrice,mixedNaanPrice))}</p>:null}</section>}</>
}

function OptionGroup({group,selected,variantLabel,onChoiceChange}:{group:MenuOptionGroup;selected:Record<string,number>;variantLabel?:string;onChoiceChange:(group:MenuOptionGroup,choiceId:string,nextQuantity?:number)=>void}){return <div><div className="flex items-center justify-between gap-3"><h3 className="text-[10px] font-black uppercase">{group.name}</h3><span className="text-[8px] text-[#8A8179]">{group.required?"Required":"Optional"}</span></div><div className="mt-3 grid gap-2">{group.choices.filter(choice=>choice.isAvailable!==false).map(choice=>{const quantity=selected[choice.id]??0;const active=quantity>0;const price=getChoicePrice(choice,variantLabel);return <div key={choice.id} className={`flex min-w-0 items-center gap-3 rounded-xl border p-3 ${active?"border-[#C8102E] bg-[#FFF8F8]":"border-[#E5D9CD] bg-[#FFFDF9]"}`}><button type="button" onClick={()=>onChoiceChange(group,choice.id)} className={`grid h-5 w-5 shrink-0 place-items-center rounded border ${active?"border-[#C8102E] bg-[#C8102E] text-white":"border-[#BFB6AD] bg-white text-transparent"}`} aria-label={`Select ${choice.name}`}><FontAwesomeIcon icon={faCheck} className="h-2"/></button><button type="button" onClick={()=>onChoiceChange(group,choice.id)} className="min-w-0 flex-1 text-left"><span className="block text-[10px] font-black">{choice.name}</span>{choice.description&&<span className="mt-1 block text-[8px] leading-4 text-[#7A726B]">{choice.description}</span>}</button>{price>0&&<span className="shrink-0 text-[10px] font-black">+{formatPrice(price)}</span>}{group.selectionType==="quantity"&&<div className="flex shrink-0 items-center gap-2"><button type="button" onClick={()=>onChoiceChange(group,choice.id,quantity-1)} className="grid h-7 w-7 place-items-center rounded-lg border border-[#E5D9CD]"><FontAwesomeIcon icon={faMinus} className="h-2"/></button><span className="w-4 text-center text-[10px] font-black">{quantity}</span><button type="button" onClick={()=>onChoiceChange(group,choice.id,quantity+1)} className="grid h-7 w-7 place-items-center rounded-lg border border-[#E5D9CD]"><FontAwesomeIcon icon={faPlus} className="h-2"/></button></div>}</div>})}</div></div>}
