"use client";
import { useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCoins,faCrown,faDownload,faGift,faRotate } from "@fortawesome/free-solid-svg-icons";
import { PageHeader,StatCard } from "@/components/admin/AdminPrimitives";
type Tier={_id:string;key:string;name:string;rank:number;minimumLifetimeSpend:number;minimumAnnualSpend:number;minimumAnnualOrders:number;pointsMultiplier:number;birthdayBonusCoins:number;benefits:string[];colorHex:string;isActive:boolean};
type Reward={_id:string;name:string;slug:string;description:string;rewardType:string;coinCost:number;rewardValue:number;minimumOrderAmount:number;eligibleTierKeys:string[];inventoryLimit:number|null;redeemedCount:number;isActive:boolean};
type Summary={tiers:Tier[];members:Array<{_id:string;customers:number;annualSpend:number}>;wallet:{balance:number;earned:number;redeemed:number};catalog:Reward[];redemptions:Array<{_id:string;count:number;coins:number}>;expiringCoins:number};
async function api<T>(url:string,init?:RequestInit){const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers??{})}});const j=await r.json();if(!r.ok)throw new Error(j.message??"Request failed.");return j.data as T;}
export function LoyaltyEngineClient({canManage}:{canManage:boolean}){const[data,setData]=useState<Summary|null>(null);const[error,setError]=useState("");const[working,setWorking]=useState(false);const load=useCallback(async()=>{try{setError("");setData(await api<Summary>("/api/v1/admin/loyalty/summary"));}catch(e){setError(e instanceof Error?e.message:"Unable to load loyalty engine.");}},[]);useEffect(()=>{let cancelled=false;api<Summary>("/api/v1/admin/loyalty/summary").then(summary=>{if(!cancelled){setData(summary);}}).catch((e:unknown)=>{if(!cancelled){setError(e instanceof Error?e.message:"Unable to load loyalty engine.");}});return()=>{cancelled=true;};},[]);
async function evaluate(){setWorking(true);try{await api("/api/v1/admin/loyalty/evaluate",{method:"POST",body:JSON.stringify({limit:10000})});await load();}catch(e){setError(e instanceof Error?e.message:"Evaluation failed.");}finally{setWorking(false);}}
async function createReward(form:FormData){setWorking(true);try{await api("/api/v1/admin/loyalty/rewards",{method:"POST",body:JSON.stringify({name:String(form.get("name")),slug:String(form.get("slug")),description:String(form.get("description")??""),rewardType:String(form.get("rewardType")),coinCost:Number(form.get("coinCost")),rewardValue:Number(form.get("rewardValue")),minimumOrderAmount:Number(form.get("minimumOrderAmount")||0),eligibleTierKeys:["bronze","silver","gold","platinum"],inventoryLimit:null,isActive:true,imageUrl:""})});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create reward.");}finally{setWorking(false);}}
const members=data?.members.reduce((s,x)=>s+x.customers,0)??0;const issued=data?.redemptions.reduce((s,x)=>s+x.count,0)??0;return <><PageHeader eyebrow="Phase 7 · Customer Experience" title="Loyalty Engine 2.0" description="Manage membership tiers, TRS Coins, expiring balances, milestones, reward catalog and customer qualification." action={<div className="flex flex-wrap gap-2"><Link href="/api/v1/admin/loyalty/report" prefetch={false} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-xs font-black"><FontAwesomeIcon icon={faDownload}/>Export CSV</Link>{canManage?<button disabled={working} onClick={()=>void evaluate()} className="inline-flex items-center gap-2 rounded-xl bg-[#173044] px-4 py-3 text-xs font-black text-white"><FontAwesomeIcon icon={faRotate}/>Rebuild tiers</button>:null}</div>}/>{error?<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>:null}<div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Members" value={String(members)} icon={faCrown} detail="Customers with evaluated membership"/><StatCard label="Coins in wallets" value={String(data?.wallet.balance??0)} icon={faCoins} detail={`${data?.wallet.earned??0} lifetime earned`}/><StatCard label="Rewards issued" value={String(issued)} icon={faGift} detail={`${data?.catalog.length??0} catalog items`}/><StatCard label="Expiring in 30 days" value={String(data?.expiringCoins??0)} icon={faRotate} detail="Coins requiring customer communication"/></div>
<section className="mt-6 rounded-[24px] border border-[#e8ddd3] bg-[#fffdf9] p-5 shadow-sm"><h2 className="text-lg font-black text-[#173044]">Tier rules</h2><div className="mt-4 grid gap-4 xl:grid-cols-4">{data?.tiers.map(t=><article key={t.key} className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><span className="rounded-full px-3 py-1 text-[10px] font-black uppercase text-white" style={{backgroundColor:t.colorHex}}>{t.name}</span><b>{t.pointsMultiplier}×</b></div><p className="mt-4 text-xs text-[#756960]">Lifetime ₹{t.minimumLifetimeSpend.toLocaleString("en-IN")} · Annual ₹{t.minimumAnnualSpend.toLocaleString("en-IN")} or {t.minimumAnnualOrders} orders</p><ul className="mt-3 space-y-1 text-xs">{t.benefits.map(b=><li key={b}>• {b}</li>)}</ul><p className="mt-3 text-xs font-black">{data.members.find(m=>m._id===t.key)?.customers??0} members</p></article>)}</div></section>
<section className="mt-6 overflow-hidden rounded-[24px] border border-[#e8ddd3] bg-[#fffdf9] shadow-sm"><div className="flex items-center justify-between p-5"><div><h2 className="text-lg font-black text-[#173044]">Reward catalog</h2><p className="text-xs text-[#756960]">Redeemable discounts, items and bonus-coin rewards.</p></div></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-[#faf5ef] text-[10px] uppercase text-[#756960]"><tr><th className="px-5 py-3">Reward</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Coin cost</th><th className="px-5 py-3">Value</th><th className="px-5 py-3">Redeemed</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y">{data?.catalog.length?data.catalog.map(r=><tr key={r._id}><td className="px-5 py-4"><b>{r.name}</b><p className="text-xs text-[#756960]">{r.description}</p></td><td className="px-5 py-4">{r.rewardType.replaceAll("_"," ")}</td><td className="px-5 py-4 font-black">{r.coinCost}</td><td className="px-5 py-4">{r.rewardValue}</td><td className="px-5 py-4">{r.redeemedCount}{r.inventoryLimit!==null?` / ${r.inventoryLimit}`:""}</td><td className="px-5 py-4">{r.isActive?"Active":"Inactive"}</td></tr>):<tr><td colSpan={6} className="p-10 text-center text-[#756960]">No catalog rewards configured.</td></tr>}</tbody></table></div></section>
{canManage?<section className="mt-6 rounded-[24px] border border-[#e8ddd3] bg-[#fffdf9] p-5 shadow-sm"><h2 className="text-lg font-black text-[#173044]">Create catalog reward</h2><form action={form=>void createReward(form)} className="mt-4 grid gap-3 md:grid-cols-3"><input required name="name" placeholder="Reward name" className="rounded-xl border px-3 py-3 text-sm"/><input required name="slug" placeholder="reward-slug" className="rounded-xl border px-3 py-3 text-sm"/><select name="rewardType" className="rounded-xl border px-3 py-3 text-sm"><option value="fixed_discount">Fixed discount</option><option value="percentage_discount">Percentage discount</option><option value="free_item">Free item</option><option value="bonus_coins">Bonus coins</option></select><input required type="number" min="1" name="coinCost" placeholder="Coin cost" className="rounded-xl border px-3 py-3 text-sm"/><input required type="number" min="0" name="rewardValue" placeholder="Reward value" className="rounded-xl border px-3 py-3 text-sm"/><input type="number" min="0" name="minimumOrderAmount" placeholder="Minimum order" className="rounded-xl border px-3 py-3 text-sm"/><textarea name="description" placeholder="Description" className="rounded-xl border px-3 py-3 text-sm md:col-span-2"/><button disabled={working} className="rounded-xl bg-[#C8102E] px-4 py-3 text-xs font-black text-white">Create reward</button></form></section>:null}</>}
