"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRotateRight, faMagnifyingGlass } from "@fortawesome/free-solid-svg-icons";
import { PageHeader, SectionCard, StatusBadge } from "@/components/admin/AdminPrimitives";

type RecordRow = { _id:string; orderNumber:string; saleType:string; status:string; createdAt:string; items:Array<{name:string;quantity:number;lineTotal:number}>; internalConsumption:{personName:string;reason:string;notes:string;menuValue:number;approvalStatus?:string;approvalReason?:string;approvedBy?:{name:string;email:string};dailyUsageBefore?:number;monthlyUsageBefore?:number;dailyLimit?:number;monthlyLimit?:number}; cashierId?:{name:string} };
type AuditRow = { _id:string; action:string; saleType:string; subjectName:string; actorName:string; reason:string; createdAt:string };
const labels:Record<string,string>={staff_meal:"Staff Meal",family_meal:"Family Meal",complimentary:"Complimentary",food_wastage:"Food Wastage",kitchen_test:"Kitchen Testing"};
const date=(v:string)=>new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(v||0);
export function InternalConsumptionRecordsClient(){
 const [rows,setRows]=useState<RecordRow[]>([]),[audit,setAudit]=useState<AuditRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [q,setQ]=useState(""),[saleType,setSaleType]=useState("all"),[page,setPage]=useState(1),[pages,setPages]=useState(1);
 const query=useMemo(()=>new URLSearchParams({q,saleType,page:String(page),limit:"25"}).toString(),[q,saleType,page]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/v1/admin/internal-consumption/records?${query}`,{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.message||"Unable to load records.");setRows(json.data.records);setAudit(json.data.audit);setPages(json.data.pagination.pages||1);}catch(e){setError(e instanceof Error?e.message:"Unable to load records.");}finally{setLoading(false);}},[query]);
 useEffect(() => {
  const timeoutId = window.setTimeout(() => { void load(); }, 0);
  return () => window.clearTimeout(timeoutId);
 }, [load]);
 return <div className="space-y-6"><PageHeader eyebrow="Operations & compliance" title="Internal Consumption Records" description="Complete order history, meal-limit approvals, testing and wastage records, and immutable audit activity." actions={<button onClick={()=>void load()} className="rounded-xl bg-[#173044] px-4 py-2 text-xs font-black text-white"><FontAwesomeIcon icon={faArrowRotateRight} className="mr-2"/>Refresh</button>}/>
 <SectionCard><div className="grid gap-3 md:grid-cols-[1fr_240px_auto]"><label className="relative"><FontAwesomeIcon icon={faMagnifyingGlass} className="absolute left-3 top-3.5 text-slate-400"/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Order number, person or reason" className="h-11 w-full rounded-xl border pl-10 pr-3"/></label><select value={saleType} onChange={e=>{setSaleType(e.target.value);setPage(1)}} className="h-11 rounded-xl border bg-white px-3"><option value="all">All types</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={()=>void load()} className="h-11 rounded-xl bg-[#C8102E] px-5 text-xs font-black text-white">Apply</button></div></SectionCard>
 {error&&<p className="rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</p>}
 <SectionCard><h2 className="text-lg font-black">Consumption and testing records</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr className="border-b text-slate-500"><th className="p-3">Order</th><th className="p-3">Type / person</th><th className="p-3">Reason</th><th className="p-3">Items</th><th className="p-3">Value</th><th className="p-3">Approval</th></tr></thead><tbody>{!loading&&rows.map(row=><tr key={row._id} className="border-b align-top"><td className="p-3"><p className="font-black">{row.orderNumber}</p><p className="text-slate-500">{date(row.createdAt)}</p></td><td className="p-3"><p className="font-black">{labels[row.saleType]}</p><p>{row.internalConsumption.personName}</p></td><td className="p-3"><p className="font-bold">{row.internalConsumption.reason}</p><p className="max-w-xs text-slate-500">{row.internalConsumption.notes}</p></td><td className="p-3">{row.items.map(i=><p key={`${i.name}-${i.quantity}`}>{i.quantity}× {i.name}</p>)}</td><td className="p-3 font-black text-[#C8102E]">{money(row.internalConsumption.menuValue)}</td><td className="p-3"><StatusBadge tone={row.internalConsumption.approvalStatus==="approved"?"success":"neutral"}>{row.internalConsumption.approvalStatus||"not required"}</StatusBadge>{row.internalConsumption.approvedBy&&<p className="mt-1 text-slate-500">{row.internalConsumption.approvedBy.name}</p>}</td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={6} className="p-10 text-center font-bold text-slate-400">No records found.</td></tr>}</tbody></table></div><div className="mt-4 flex items-center justify-end gap-2"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><span className="text-xs font-black">Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(v=>v+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></SectionCard>
 <SectionCard><h2 className="text-lg font-black">Audit trail</h2><div className="mt-4 divide-y">{audit.map(row=><article key={row._id} className="grid gap-2 py-3 md:grid-cols-[180px_1fr_180px]"><div><p className="font-black capitalize">{row.action.replaceAll("_"," ")}</p><p className="text-slate-500">{date(row.createdAt)}</p></div><div><p className="font-bold">{row.subjectName||labels[row.saleType]||"Internal consumption"}</p><p className="text-slate-500">{row.reason}</p></div><p className="font-bold text-slate-600">By {row.actorName||"System"}</p></article>)}</div></SectionCard></div>;
}
