import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowTrendUp, faBell, faBoxesStacked, faBriefcase, faChartLine,
  faFileInvoiceDollar, faGaugeHigh, faGift, faImage, faKitchenSet,
  faPeopleGroup, faPhotoFilm, faReceipt, faSliders, faStore, faTags, faTruck, faPanorama, faCashRegister,
  faUserShield, faUsers, faUtensils, faServer, faAddressCard, faPlateWheat, faBullhorn, faCrown, faBrain, faStar, faMoneyBillTrendUp, faMoneyCheckDollar, faFileShield, faClockRotateLeft, faTableColumns, faEnvelopeOpenText, faMoneyBillTransfer, faPrint,
} from "@fortawesome/free-solid-svg-icons";

export type AdminNavItem = { label: string; href: string; icon: IconDefinition; permission?: string };
export type AdminNavGroup = { label: string; items: AdminNavItem[] };

export const adminNavigation: AdminNavGroup[] = [
  { label: "Overview", items: [
    { label: "Dashboard", href: "/admin/dashboard", icon: faGaugeHigh, permission: "reports.read" },
    { label: "Sales Analytics", href: "/admin/sales-analytics", icon: faMoneyBillTrendUp, permission: "reports.read" },
  ] },
  { label: "Operations", items: [
    { label: "Point of Sale", href: "/admin/pos", icon: faCashRegister, permission: "orders.read" },
    { label: "Running Orders", href: "/admin/pos/operations", icon: faClockRotateLeft, permission: "pos.use" },
    { label: "POS Analytics", href: "/admin/pos/analytics", icon: faChartLine, permission: "reports.read" },
    { label: "Cash Registers", href: "/admin/pos/cash-registers", icon: faMoneyBillTransfer, permission: "pos.use" },
    { label: "Print Center", href: "/admin/pos/print-center", icon: faPrint, permission: "pos.use" },
    { label: "Bill History", href: "/admin/pos/bills", icon: faReceipt, permission: "orders.read" },
    { label: "POS & Printer Settings", href: "/admin/pos/setup", icon: faSliders, permission: "settings.manage" },
    { label: "Orders", href: "/admin/orders", icon: faReceipt, permission: "orders.read" },
    { label: "Live Orders", href: "/admin/orders/live", icon: faArrowTrendUp, permission: "orders.read" },
    { label: "Kitchen Display", href: "/admin/kds", icon: faKitchenSet, permission: "kds.use" },
  ]},
  { label: "Catalog", items: [
    { label: "Menu", href: "/admin/menu", icon: faUtensils, permission: "menu.read" },
    { label: "Inventory", href: "/admin/inventory", icon: faBoxesStacked, permission: "inventory.read" },
    { label: "Recipe Management", href: "/admin/inventory/recipes", icon: faKitchenSet, permission: "inventory.read" },
    { label: "Daily Stock Count", href: "/admin/inventory/daily-stock-count", icon: faTableColumns, permission: "inventory.read" },
    { label: "Purchase Requirements", href: "/admin/inventory/purchase-requirements", icon: faTruck, permission: "purchases.read" },
    { label: "Inventory Analytics", href: "/admin/inventory-analytics", icon: faChartLine, permission: "inventory.read" },
    { label: "Inventory Forecasting", href: "/admin/inventory-forecasting", icon: faArrowTrendUp, permission: "inventory.read" },
    { label: "Vendors & Purchases", href: "/admin/purchasing", icon: faTruck, permission: "purchases.read" },
    { label: "Supplier Intelligence", href: "/admin/supplier-intelligence", icon: faChartLine, permission: "purchases.read" },
    { label: "Procurement Intelligence", href: "/admin/procurement-intelligence", icon: faArrowTrendUp, permission: "purchases.read" },
  ]},
  { label: "Customers", items: [
    { label: "CRM & Customer 360", href: "/admin/crm", icon: faAddressCard, permission: "users.read" },
    { label: "Customers", href: "/admin/customers", icon: faUsers, permission: "users.read" },
    { label: "Reviews", href: "/admin/reviews", icon: faPeopleGroup, permission: "reviews.read" },
    { label: "Feedback & Reputation", href: "/admin/feedback-reputation", icon: faStar, permission: "reviews.read" },
    { label: "Enquiries", href: "/admin/enquiries", icon: faBell, permission: "notifications.read" },
  ]},
  { label: "Growth", items: [
    { label: "Marketing Automation", href: "/admin/marketing", icon: faBullhorn, permission: "users.read" },
    { label: "Loyalty Engine 2.0", href: "/admin/loyalty", icon: faCrown, permission: "reports.read" },
    { label: "AI Recommendations", href: "/admin/recommendations", icon: faBrain, permission: "reports.read" },
    { label: "Customer Analytics", href: "/admin/customer-analytics", icon: faChartLine, permission: "reports.read" },
    { label: "Coupons & Offers", href: "/admin/coupons", icon: faTags, permission: "orders.read" },
    { label: "Spin Wheel", href: "/admin/spin-wheel", icon: faGift, permission: "settings.manage" },
    { label: "Referrals", href: "/admin/referrals", icon: faPeopleGroup, permission: "users.read" },
  ]},
  { label: "Content", items: [
    { label: "CMS", href: "/admin/cms", icon: faSliders, permission: "cms.read" },
    { label: "Page Heroes", href: "/admin/page-heroes", icon: faPanorama, permission: "cms.read" },
    { label: "Gallery", href: "/admin/gallery", icon: faImage, permission: "cms.read" },
    { label: "Media Library", href: "/admin/media-library", icon: faPhotoFilm, permission: "cms.read" },
    { label: "Jobs", href: "/admin/jobs", icon: faBriefcase, permission: "cms.read" },
  ]},
  { label: "Finance", items: [
    { label: "Revenue Management", href: "/admin/finance/revenue", icon: faMoneyBillTrendUp, permission: "reports.read" },
    { label: "Expense Management", href: "/admin/finance/expenses", icon: faFileInvoiceDollar, permission: "reports.read" },
    { label: "Accounts Receivable", href: "/admin/finance/accounts-receivable", icon: faMoneyCheckDollar, permission: "reports.read" },
    { label: "Accounts Payable", href: "/admin/finance/accounts-payable", icon: faMoneyCheckDollar, permission: "reports.read" },
    { label: "Invoices & Receipts", href: "/admin/finance/invoices-receipts", icon: faFileInvoiceDollar, permission: "reports.read" },
    { label: "Payment Management", href: "/admin/finance/payment-management", icon: faFileInvoiceDollar, permission: "payments.read" },
    { label: "Financial Reports", href: "/admin/finance/financial-reports", icon: faChartLine, permission: "reports.read" },
    { label: "Budgeting & Forecasting", href: "/admin/finance/budgeting-forecasting", icon: faChartLine, permission: "reports.read" },
    { label: "Executive Financial Dashboard", href: "/admin/finance/executive-finance", icon: faChartLine, permission: "reports.read" },
    { label: "Payments", href: "/admin/payments", icon: faFileInvoiceDollar, permission: "payments.read" },
    { label: "Reports", href: "/admin/reports", icon: faChartLine, permission: "reports.read" },
    { label: "Report Builder", href: "/admin/report-builder", icon: faTableColumns, permission: "reports.read" },
    { label: "Scheduled Reports", href: "/admin/scheduled-reports", icon: faClockRotateLeft, permission: "reports.read" },
    { label: "Report Background Jobs", href: "/admin/report-jobs", icon: faServer, permission: "reports.read" },
    { label: "Report Automation", href: "/admin/report-automation", icon: faEnvelopeOpenText, permission: "reports.read" },
    { label: "Executive BI", href: "/admin/executive-bi", icon: faChartLine, permission: "reports.read" },
    { label: "Business Forecasting", href: "/admin/business-forecasting", icon: faArrowTrendUp, permission: "reports.read" },
    { label: "KPI Intelligence", href: "/admin/kpi-intelligence", icon: faBrain, permission: "reports.read" },
    { label: "Forecast Governance", href: "/admin/forecast-governance", icon: faFileShield, permission: "reports.read" },
    { label: "Audit & Approvals", href: "/admin/finance/audit-approvals", icon: faFileShield, permission: "reports.read" },
    { label: "Scheduled Financial Jobs", href: "/admin/finance/scheduled-jobs", icon: faClockRotateLeft, permission: "reports.read" },
  ]},
  { label: "Administration", items: [
    { label: "Staff & Roles", href: "/admin/staff", icon: faUserShield, permission: "roles.read" },
    { label: "Internal Consumption", href: "/admin/internal-consumption", icon: faPlateWheat, permission: "settings.manage" },
    { label: "Consumption Configuration", href: "/admin/internal-consumption-configuration", icon: faSliders, permission: "settings.manage" },
    { label: "Consumption Analytics", href: "/admin/internal-consumption-analytics", icon: faChartLine, permission: "reports.read" },
    { label: "Consumption Executive BI", href: "/admin/internal-consumption-executive", icon: faArrowTrendUp, permission: "reports.read" },
    { label: "Consumption Records", href: "/admin/internal-consumption-records", icon: faChartLine, permission: "reports.read" },
    { label: "Enterprise Operations", href: "/admin/enterprise-operations", icon: faServer, permission: "settings.manage" },
    { label: "Account Security", href: "/admin/security", icon: faUserShield },
    { label: "Settings", href: "/admin/settings", icon: faStore, permission: "settings.manage" },
  ]},
];
