"use client";

import { motion } from "framer-motion";
import type { ReactNode } from "react";
import type { InventoryActionDialog } from "@/components/admin/inventory/admin-inventory.types";

export function InventoryActionModal({dialog,saving,onConfirmationTextChange,onClose,onConfirm}:{dialog:InventoryActionDialog;saving:boolean;onConfirmationTextChange:(value:string)=>void;onClose:()=>void;onConfirm:()=>void}){
 const permanent=dialog.type==="permanent-delete",canConfirm=!saving&&(!permanent||dialog.confirmationText==="DELETE");
 return <motion.div className="fixed inset-0 z-[120] grid place-items-end bg-black/55 p-0 backdrop-blur-sm sm:place-items-center sm:p-5" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose} role="presentation"><motion.section role="dialog" aria-modal="true" aria-labelledby="inventory-action-title" aria-describedby="inventory-action-description" onMouseDown={e=>e.stopPropagation()} className="w-full overflow-hidden rounded-t-[28px] border border-white/10 bg-[#fffdfb] shadow-2xl sm:max-w-lg sm:rounded-[28px]" initial={{y:50,opacity:0,scale:.98}} animate={{y:0,opacity:1,scale:1}} exit={{y:50,opacity:0,scale:.98}} transition={{duration:.2}}>
 <div className={`h-1.5 w-full ${permanent?"bg-red-700":"bg-gradient-to-r from-[#C8102E] via-[#E8A53A] to-[#173044]"}`}/><div className="p-5 sm:p-6"><div className="flex items-start gap-4"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl text-xl font-black ${permanent?"bg-red-100 text-red-700":"bg-[#fff0e8] text-[#C8102E]"}`} aria-hidden="true">{permanent?"!":"↘"}</span><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#C8102E]">Inventory control</p><h2 id="inventory-action-title" className="mt-1 break-words text-xl font-black text-[#173044]">{permanent?"Permanently delete item?":"Archive inventory item?"}</h2><p id="inventory-action-description" className="mt-2 text-sm leading-6 text-[#756b63]">{permanent?`"${dialog.item.name}" will be permanently removed. This cannot be undone. The system will block deletion if historical or operational records still reference it.`:`"${dialog.item.name}" will be removed from active inventory, daily stock counts and purchase requirements. Historical movements and reports will remain available.`}</p></div><button type="button" onClick={onClose} disabled={saving} aria-label="Close confirmation" className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[#e5dbd3] text-lg text-[#655d57] transition hover:bg-[#f7f0ea] disabled:opacity-50">×</button></div>
 <div className="mt-5 rounded-2xl border border-[#eadfd6] bg-[#fffaf6] p-4"><div className="grid grid-cols-2 gap-3 text-xs"><Info label="Item" value={dialog.item.name}/><Info label="SKU" value={dialog.item.sku}/></div></div>
 {permanent?<label className="mt-5 block"><span className="mb-2 block text-[10px] font-black uppercase tracking-wider text-[#756b63]">Type DELETE to confirm</span><input autoFocus value={dialog.confirmationText} onChange={e=>onConfirmationTextChange(e.currentTarget.value)} placeholder="DELETE" autoComplete="off" className="h-12 w-full rounded-xl border border-red-200 bg-white px-4 text-sm font-black uppercase tracking-[.12em] text-red-700 outline-none transition placeholder:text-red-300 focus:border-red-600 focus:ring-4 focus:ring-red-100"/><p className="mt-2 text-xs leading-5 text-red-700/75">Use permanent deletion only for unused test records. Operational inventory should normally remain archived.</p></label>:<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs font-bold leading-5 text-amber-900">You can restore this item later from the Archived Items filter.</div>}</div>
 <footer className="grid grid-cols-2 gap-3 border-t border-[#eee4dc] bg-white p-4 sm:flex sm:justify-end"><button type="button" onClick={onClose} disabled={saving} className="h-12 rounded-xl border border-[#ded3ca] px-5 text-xs font-black text-[#173044] transition hover:bg-[#f7f0ea] disabled:opacity-50">Keep item</button><button type="button" onClick={onConfirm} disabled={!canConfirm} className={`h-12 rounded-xl px-5 text-xs font-black text-white shadow-lg transition disabled:cursor-not-allowed disabled:opacity-40 ${permanent?"bg-red-700 hover:bg-red-800":"bg-[#C8102E] hover:bg-[#a90d27]"}`}>{saving?"Processing…":permanent?"Permanently delete":"Archive item"}</button></footer></motion.section></motion.div>
}
function Info({label,value}:{label:string;value:string}){return <div><p className="font-black uppercase tracking-wider text-[#9a8f87]">{label}</p><p className="mt-1 break-words font-black text-[#173044]">{value}</p></div>}

export function SummaryCard({label,value,alert=false}:{label:string;value:string|number;alert?:boolean}){return <div className="rounded-2xl border border-[#e8ddd4] bg-white p-4 sm:p-5"><p className="text-[9px] font-black uppercase tracking-[.16em] text-[#8c8178]">{label}</p><p className={`mt-3 break-words text-xl font-black sm:text-2xl ${alert?"text-[#C8102E]":"text-[#173044]"}`}>{value}</p></div>}
export function TabButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return <button onClick={onClick} className={`rounded-xl px-3 py-2 text-[10px] font-black uppercase tracking-wider sm:px-4 ${active?"bg-[#fff0e8] text-[#C8102E]":"text-[#786e66]"}`}>{children}</button>}
export function LoadingState(){return <div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6},(_,index)=><div key={index} className="h-36 animate-pulse rounded-2xl bg-[#f5eee8]"/>)}</div>}
export function EmptyState({text}:{text:string}){return <div className="px-5 py-20 text-center"><p className="text-sm font-bold text-[#8c8178]">{text}</p></div>}
