"use client";

import { money,type InventoryItem,type InventoryMovement } from "@/components/admin/inventory/admin-inventory.types";

export function InventoryRow(props:InventoryItemViewProps){const {item}=props,status=statusOf(item);return <tr className={!item.isActive?"bg-slate-50/70":""}><td className="px-5 py-4"><b className="block text-sm text-[#173044]">{item.name}</b><span className="text-[10px] font-bold text-[#968a81]">{item.sku}</span></td><td className="px-5 py-4 text-xs font-bold text-[#655d57]">{item.category}</td><td className="px-5 py-4"><b className="text-sm text-[#173044]">{item.currentStock}</b> <span className="text-xs text-[#8c8178]">{item.unit}</span></td><td className="px-5 py-4 text-xs text-[#655d57]">{item.reorderLevel} / {item.idealStockLevel} {item.unit}</td><td className="px-5 py-4 text-xs font-bold text-[#173044]">{money.format(item.averageUnitCost)}/{item.unit}</td><td className="px-5 py-4"><Status status={status}/></td><td className="px-5 py-4"><Actions {...props}/></td></tr>}

export function InventoryCard(props:InventoryItemViewProps){const {item,canManage,saving,onEdit,onMovement,onArchive,onRestore,onPermanentDelete}=props,status=statusOf(item);return <article className={`min-w-0 rounded-2xl border p-4 ${item.isActive?"border-[#eee4dc]":"border-slate-200 bg-slate-50"}`}><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-sm font-black text-[#173044]">{item.name}</h3><p className="mt-1 truncate text-[10px] font-bold text-[#8c8178]">{item.sku} · {item.category}</p></div><Status status={status}/></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-[#fffaf6] p-3"><Metric label="Current">{item.currentStock} {item.unit}</Metric><Metric label="Reorder level">{item.reorderLevel} {item.unit}</Metric></div>{canManage&&(item.isActive?<div className="mt-3 grid grid-cols-3 gap-2"><Button disabled={saving} onClick={onMovement}>Stock</Button><Button disabled={saving} onClick={onEdit} dark>Edit</Button><Button disabled={saving} onClick={onArchive} danger>Delete</Button></div>:<div className="mt-3 grid grid-cols-2 gap-2"><Button disabled={saving} onClick={onRestore} restore>Restore item</Button><Button disabled={saving} onClick={onPermanentDelete} permanent>Permanent delete</Button></div>)}</article>}

export function MovementList({movements}:{movements:InventoryMovement[]}){return <div className="divide-y divide-[#eee5de]">{movements.map(movement=>{const item=typeof movement.inventoryItemId==="string"?null:movement.inventoryItemId;return <div key={movement._id} className="grid gap-2 p-4 sm:grid-cols-[1fr_auto] sm:items-center sm:px-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><b className="truncate text-sm text-[#173044]">{item?.name??"Inventory item"}</b><span className="rounded-full bg-[#fff0e8] px-2 py-1 text-[8px] font-black uppercase text-[#C8102E]">{movement.type.replaceAll("_"," ")}</span></div><p className="mt-1 text-[10px] font-bold text-[#8c8178]">{item?.sku??""} · {new Date(movement.createdAt).toLocaleString("en-IN")}</p>{movement.reason&&<p className="mt-2 text-xs text-[#6f655e]">{movement.reason}</p>}</div><div className="text-left sm:text-right"><b className="text-sm text-[#173044]">{movement.stockBefore} → {movement.stockAfter} {item?.unit??""}</b><p className="mt-1 text-[10px] font-bold text-[#8c8178]">Quantity: {movement.quantity}{movement.totalCost>0?` · ${money.format(movement.totalCost)}`:""}</p></div></div>})}</div>}

type InventoryItemViewProps={item:InventoryItem;canManage:boolean;saving:boolean;onEdit:()=>void;onMovement:()=>void;onArchive:()=>void;onRestore:()=>void;onPermanentDelete:()=>void};
function statusOf(item:InventoryItem){if(!item.isActive)return{label:"Inactive",cls:"bg-slate-100 text-slate-600"};if(item.currentStock<=0)return{label:"Out of stock",cls:"bg-red-50 text-red-700"};if(item.currentStock<=item.reorderLevel)return{label:"Low stock",cls:"bg-amber-50 text-amber-700"};return{label:"Healthy",cls:"bg-emerald-50 text-emerald-700"}}
function Status({status}:{status:{label:string;cls:string}}){return <span className={`shrink-0 rounded-full px-3 py-1 text-[9px] font-black uppercase ${status.cls}`}>{status.label}</span>}
function Metric({label,children}:{label:string;children:React.ReactNode}){return <div><p className="text-[8px] font-black uppercase text-[#968a81]">{label}</p><b className="mt-1 block text-base text-[#173044]">{children}</b></div>}
function Actions({item,canManage,saving,onEdit,onMovement,onArchive,onRestore,onPermanentDelete}:InventoryItemViewProps){return <div className="flex flex-wrap justify-end gap-2">{canManage&&(item.isActive?<><Button disabled={saving} onClick={onMovement}>Stock</Button><Button disabled={saving} onClick={onEdit} dark>Edit</Button><Button disabled={saving} onClick={onArchive} danger>Delete</Button></>:<><Button disabled={saving} onClick={onRestore} restore>Restore</Button><Button disabled={saving} onClick={onPermanentDelete} permanent>Permanent delete</Button></>)}</div>}
function Button({children,disabled,onClick,dark,danger,restore,permanent}:{children:React.ReactNode;disabled:boolean;onClick:()=>void;dark?:boolean;danger?:boolean;restore?:boolean;permanent?:boolean}){const cls=permanent?"bg-red-700 text-white":restore?"bg-emerald-600 text-white":danger?"border border-red-200 bg-red-50 text-red-700":dark?"bg-[#173044] text-white":"border border-[#ded3ca]";return <button disabled={disabled} onClick={onClick} className={`rounded-lg px-3 py-2 text-[10px] font-black disabled:opacity-50 ${cls}`}>{children}</button>}
