"use client";

import { motion } from "framer-motion";
import type { ReactNode } from "react";
import { units,type ItemForm,type InventoryItem,type Unit } from "@/components/admin/inventory/admin-inventory.types";

export function ItemDrawer({editor,saving,onChange,onClose,onSave}:{editor:{item:InventoryItem|null;form:ItemForm};saving:boolean;onChange:(form:ItemForm)=>void;onClose:()=>void;onSave:()=>void}){
 const {form}=editor;const set=<K extends keyof ItemForm>(key:K,value:ItemForm[K])=>onChange({...form,[key]:value});
 return <Drawer title={editor.item?"Edit inventory item":"Create inventory item"} onClose={onClose} footer={<><button onClick={onClose} className="rounded-xl border border-[#ded3ca] px-5 py-3 text-xs font-black">Cancel</button><button disabled={saving} onClick={onSave} className="rounded-xl bg-[#C8102E] px-5 py-3 text-xs font-black text-white disabled:opacity-50">{saving?"Saving…":"Save item"}</button></>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Item name *"><input value={form.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="SKU *"><input value={form.sku} onChange={e=>set("sku",e.target.value.toUpperCase())}/></Field><Field label="Category *"><input value={form.category} onChange={e=>set("category",e.target.value)} placeholder="Cheese, vegetables, packaging…"/></Field><Field label="Stock unit"><select value={form.unit} onChange={e=>set("unit",e.target.value as Unit)}>{units.map(unit=><option key={unit}>{unit}</option>)}</select></Field>{!editor.item&&<Field label="Opening stock"><input type="number" min="0" step="any" value={form.currentStock} onChange={e=>set("currentStock",e.target.value)}/></Field>}<Field label="Reorder level"><input type="number" min="0" step="any" value={form.reorderLevel} onChange={e=>set("reorderLevel",e.target.value)}/></Field><Field label="Ideal stock level"><input type="number" min="0" step="any" value={form.idealStockLevel} onChange={e=>set("idealStockLevel",e.target.value)}/></Field><Field label="Average cost per unit"><input type="number" min="0" step="any" value={form.averageUnitCost} onChange={e=>set("averageUnitCost",e.target.value)}/></Field><label className="flex items-center gap-3 rounded-xl border border-[#e4dad2] p-4 text-xs font-bold text-[#173044]"><input type="checkbox" checked={form.expiryTrackingEnabled} onChange={e=>set("expiryTrackingEnabled",e.target.checked)}/> Track batch expiry</label><label className="flex items-center gap-3 rounded-xl border border-[#e4dad2] p-4 text-xs font-bold text-[#173044]"><input type="checkbox" checked={form.isActive} onChange={e=>set("isActive",e.target.checked)}/> Active inventory item</label><div className="sm:col-span-2"><Field label="Internal notes"><textarea rows={4} value={form.notes} onChange={e=>set("notes",e.target.value)}/></Field></div></div></Drawer>
}
function Drawer({title,onClose,children,footer}:{title:string;onClose:()=>void;children:ReactNode;footer?:ReactNode}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[100] flex items-end justify-end bg-black/45 backdrop-blur-[2px] sm:items-stretch" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><motion.aside initial={{y:"100%"}} animate={{y:0}} exit={{y:"100%"}} transition={{type:"spring",damping:28,stiffness:260}} className="flex h-[94dvh] w-full flex-col overflow-hidden rounded-t-[28px] bg-[#fffdf9] shadow-2xl sm:h-full sm:max-w-2xl sm:rounded-none"><header className="flex items-center justify-between border-b border-[#eee4dc] px-5 py-4"><h2 className="text-xl font-black text-[#173044]">{title}</h2><button onClick={onClose} className="h-10 w-10 rounded-xl border border-[#ded3ca] bg-white text-xl">×</button></header><div className="flex-1 overflow-y-auto p-5">{children}</div>{footer&&<footer className="flex justify-end gap-2 border-t border-[#eee4dc] bg-white p-4">{footer}</footer>}</motion.aside></motion.div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-xs font-black text-[#173044]"><span className="mb-2 block">{label}</span><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-[#ded3ca] [&_input]:bg-white [&_input]:px-3 [&_input]:py-3 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-[#ded3ca] [&_select]:bg-white [&_select]:px-3 [&_select]:py-3 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-[#ded3ca] [&_textarea]:bg-white [&_textarea]:px-3 [&_textarea]:py-3">{children}</div></label>}
