"use client";

import { cloneElement,type ReactElement,type ReactNode } from "react";
import { motion } from "framer-motion";
import { todayInputValue } from "@/lib/validation/dateTime";
import { movementTypes,type InventoryItem,type MovementForm,type MovementType } from "@/components/admin/inventory/admin-inventory.types";

export function MovementDrawer({form,items,saving,onChange,onClose,onSave}:{form:MovementForm;items:InventoryItem[];saving:boolean;onChange:(form:MovementForm)=>void;onClose:()=>void;onSave:()=>void}){
 const set=<K extends keyof MovementForm>(key:K,value:MovementForm[K])=>onChange({...form,[key]:value});
 const selected=items.find(item=>item._id===form.inventoryItemId);
 const inbound=["opening","purchase","adjustment_in","return_in"].includes(form.type);
 return <Drawer title="Update stock" onClose={onClose} footer={<><button onClick={onClose} className="rounded-xl border border-[#ded3ca] px-5 py-3 text-xs font-black">Cancel</button><button disabled={saving} onClick={onSave} className="rounded-xl bg-[#C8102E] px-5 py-3 text-xs font-black text-white disabled:opacity-50">{saving?"Saving…":"Record movement"}</button></>}>
  <div className="space-y-4"><Field label="Inventory item"><select value={form.inventoryItemId} onChange={e=>set("inventoryItemId",e.target.value)}><option value="">Select item</option>{items.filter(item=>item.isActive).map(item=><option key={item._id} value={item._id}>{item.name} ({item.currentStock} {item.unit})</option>)}</select></Field>
  {selected&&<div className="rounded-xl bg-[#fff5ee] p-4 text-xs font-bold text-[#6c5e54]">Current stock: <span className="text-[#C8102E]">{selected.currentStock} {selected.unit}</span></div>}
  <div className="grid gap-4 sm:grid-cols-2"><Field label="Movement type"><select value={form.type} onChange={e=>set("type",e.target.value as MovementType)}>{movementTypes.map(type=><option key={type} value={type}>{type.replaceAll("_"," ")}</option>)}</select></Field><Field label={`Quantity${selected?` (${selected.unit})`:""}`}><input type="number" min="0.0001" step="any" value={form.quantity} onChange={e=>set("quantity",e.target.value)}/></Field>{inbound&&<Field label="Unit cost"><input type="number" min="0" step="any" value={form.unitCost} onChange={e=>set("unitCost",e.target.value)}/></Field>}<Field label="Batch number"><input value={form.batchNumber} onChange={e=>set("batchNumber",e.target.value)}/></Field>{selected?.expiryTrackingEnabled&&inbound&&<Field label="Expiry date"><input type="date" min={todayInputValue()} value={form.expiryDate} onChange={e=>set("expiryDate",e.target.value)}/></Field>}</div>
  <Field label="Reason / note"><textarea rows={4} value={form.reason} onChange={e=>set("reason",e.target.value)} placeholder="Why is this stock being added or removed?"/></Field></div>
 </Drawer>
}
function Drawer({title,onClose,footer,children}:{title:string;onClose:()=>void;footer:ReactNode;children:ReactNode}){return <motion.div className="fixed inset-0 z-[100] bg-black/45 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.section onMouseDown={event=>event.stopPropagation()} className="absolute inset-x-0 bottom-0 flex max-h-[92dvh] flex-col rounded-t-3xl bg-[#fffdfb] shadow-2xl sm:inset-y-0 sm:left-auto sm:w-[620px] sm:rounded-none" initial={{y:70,opacity:0}} animate={{y:0,opacity:1}} exit={{y:70,opacity:0}}><header className="flex items-center justify-between border-b border-[#eee4dc] p-5"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#C8102E]">Inventory editor</p><h2 className="mt-1 text-xl font-black text-[#173044]">{title}</h2></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border border-[#e5dbd3] text-lg">×</button></header><div className="min-h-0 flex-1 overflow-y-auto p-5">{children}</div><footer className="flex flex-col-reverse gap-2 border-t border-[#eee4dc] bg-white p-4 sm:flex-row sm:justify-end">{footer}</footer></motion.section></motion.div>}
function Field({label,children}:{label:string;children:ReactElement<{className?:string}>}){return <label className="block text-[10px] font-black uppercase tracking-wider text-[#756b63]"><span className="mb-2 block">{label}</span>{cloneElement(children,{className:`${children.props.className??""} w-full min-w-0 rounded-xl border border-[#ded3ca] bg-white px-4 py-3 text-sm font-medium normal-case tracking-normal text-[#173044] outline-none focus:border-[#C8102E]`})}</label>}
