"use client";

import type { Dispatch, SetStateAction } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faIndianRupeeSign } from "@fortawesome/free-solid-svg-icons";
import type { ItemForm, ModifierGroup, VariantForm } from "@/components/admin/menu/admin-menu.types";
import { Field, Toggle } from "@/components/admin/menu/AdminMenuUi";
import { createNaanPortionVariants } from "@/components/admin/menu/admin-menu.utils";
import { isThinCrustExcludedPizza } from "@/lib/menu/special-menu-config";

export function AdminMenuEditorVariants({form,setForm,isPizzaCategory,isNaanCategory,hasRequiredVariants,modifierGroups,combinationGroup,onResetPizza,onUpdateVariant,onSelectCombinationGroup,onUpdateCombinationPrice}:{form:ItemForm;setForm:Dispatch<SetStateAction<ItemForm>>;isPizzaCategory:boolean;isNaanCategory:boolean;hasRequiredVariants:boolean;modifierGroups:ModifierGroup[];combinationGroup?:ModifierGroup;onResetPizza:()=>void;onUpdateVariant:(index:number,updates:Partial<VariantForm>)=>void;onSelectCombinationGroup:(id:string)=>void;onUpdateCombinationPrice:(variant:string,optionId:string,value:string)=>void}) {
  return <>
    {hasRequiredVariants&&<section className="rounded-[22px] border border-[#eadfd5] bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-black text-[#122b3c]">{isPizzaCategory?"Pizza size prices":"Half / Full plate prices"}</p><p className="mt-1 text-xs leading-5 text-[#786b62]">{isPizzaCategory?"Enter prices for Small, Medium and Large.":"Half includes 1 naan and Full includes 2 naans. Sabji is selected separately."}</p></div><button type="button" onClick={()=>isPizzaCategory?onResetPizza():setForm(c=>({...c,basePrice:"",variants:createNaanPortionVariants()}))} className="rounded-xl border border-[#e5d9cf] px-3 py-2 text-[10px] font-black text-[#122b3c]">{isPizzaCategory?"Reset pizza sizes":"Reset portions"}</button></div>
      <div className="mt-4 space-y-3">{form.variants.map((v,i)=><div key={`${v.name}-${i}`} className="rounded-2xl border border-[#eadfd5] bg-[#fffaf6] p-3"><div className="grid gap-3 sm:grid-cols-2"><Field label="Option name *"><input value={v.name} onChange={e=>onUpdateVariant(i,{name:e.target.value})} placeholder="Small 7 inch" className="field"/></Field><Field label="SKU"><input value={v.sku} onChange={e=>onUpdateVariant(i,{sku:e.target.value})} placeholder="SMALL-7" className="field"/></Field>{isPizzaCategory?<><Field label="Selling price *"><input type="number" min="0" step="0.01" value={v.price} onChange={e=>onUpdateVariant(i,{price:e.target.value})} className="field"/></Field><Field label="Original / crossed price"><input type="number" min="0" step="0.01" value={v.compareAtPrice} onChange={e=>onUpdateVariant(i,{compareAtPrice:e.target.value})} placeholder="Crossed price" className="field"/></Field></>:<div className="rounded-xl border border-[#eadfd5] bg-white px-4 py-3 text-xs leading-5 text-[#786b62]">Price is calculated from the Half/Full + second-sabji matrix below.</div>}</div><div className="mt-3 flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs font-black text-[#122b3c]"><input type="radio" name="default-variant" checked={v.isDefault} onChange={()=>onUpdateVariant(i,{isDefault:true})} className="accent-[#C8102E]"/>Default option</label><label className="flex items-center gap-2 text-xs font-black text-[#122b3c]"><input type="checkbox" checked={v.isActive} onChange={e=>onUpdateVariant(i,{isActive:e.target.checked})} className="accent-[#C8102E]"/>Active</label></div></div>)}</div>
    </section>}
    {isPizzaCategory&&<section className="rounded-[22px] border border-[#eadfd5] bg-[#fff8f2] p-4"><p className="text-sm font-black text-[#122b3c]">Pizza crust configuration</p><p className="mt-1 text-xs leading-5 text-[#786b62]">Thin crust is offered only for Medium size. Cheese Burst and Classic Cheese Burst pizzas are always excluded.</p><div className="mt-4"><Toggle label="Enable thin crust on Medium" checked={!isThinCrustExcludedPizza(form.name)&&form.pizzaConfiguration.thinCrustAvailable} onChange={checked=>setForm(c=>({...c,pizzaConfiguration:{...c.pizzaConfiguration,thinCrustAvailable:checked,thinCrustPriceAdjustment:"0"}}))}/></div><p className="mt-3 rounded-xl bg-white px-3 py-2 text-xs font-bold text-[#786b62]">Thin crust uses the normal Medium pizza price. No extra charge is applied.</p>{isThinCrustExcludedPizza(form.name)&&<p className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">Thin crust is disabled because this is a Cheese Burst pizza.</p>}</section>}
    {isNaanCategory&&<section className="rounded-[22px] border border-[#eadfd5] bg-[#fff8f2] p-4"><p className="text-sm font-black text-[#122b3c]">Platter combination pricing</p><p className="mt-1 text-xs leading-5 text-[#786b62]">Set the exact price for each Half/Full + second sabji combination. Dal Makhani, Boondi Raita and Salad are included.</p><div className="mt-4"><Field label="Second sabji modifier group *"><select value={form.combinationPricing.modifierGroupId} onChange={e=>onSelectCombinationGroup(e.target.value)} className="field"><option value="">Select group</option>{modifierGroups.filter(g=>g.isActive&&g.selectionType==="single"&&g.options.some(o=>o._id&&o.isActive)).map(g=><option key={g._id} value={g._id}>{g.name}</option>)}</select></Field></div>
      {combinationGroup&&<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] text-xs"><thead><tr><th className="p-2 text-left">Portion</th>{combinationGroup.options.filter(o=>o._id&&o.isActive&&o.isAvailable!==false).map(o=><th key={o._id} className="p-2 text-left">{o.name}</th>)}</tr></thead><tbody>{form.variants.map(v=><tr key={v.name} className="border-t border-[#eadfd5]"><td className="p-2 font-black">{v.name}</td>{combinationGroup.options.filter(o=>o._id&&o.isActive&&o.isAvailable!==false).map(o=>{const entry=form.combinationPricing.entries.find(e=>e.variantLabel===v.name&&e.optionId===o._id);return <td key={o._id} className="p-2"><div className="relative"><FontAwesomeIcon icon={faIndianRupeeSign} className="absolute left-3 top-1/2 h-3 -translate-y-1/2 text-[#8c7f76]"/><input type="number" min="0" step="0.01" value={entry?.price??""} onChange={e=>onUpdateCombinationPrice(v.name,o._id as string,e.target.value)} className="field price-field"/></div></td>})}</tr>)}</tbody></table></div>}
    </section>}
  </>;
}
