"use client";

import { AnimatePresence, motion } from "framer-motion";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faIndianRupeeSign, faPercent, faXmark } from "@fortawesome/free-solid-svg-icons";
import { Field } from "@/components/admin/menu/AdminMenuUi";

export function AdminMenuBulkDiscountModal({open,acting,selectedCount,type,value,error,onClose,onTypeChange,onValueChange,onApply}:{open:boolean;acting:boolean;selectedCount:number;type:"percentage"|"fixed";value:string;error:string;onClose:()=>void;onTypeChange:(v:"percentage"|"fixed")=>void;onValueChange:(v:string)=>void;onApply:()=>void}) {
 return <AnimatePresence>{open&&<><motion.button type="button" aria-label="Close bulk discount" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>{if(!acting)onClose()}} className="fixed inset-0 z-[80] bg-[#071923]/55 backdrop-blur-sm"/><motion.section role="dialog" aria-modal="true" aria-labelledby="bulk-discount-title" initial={{opacity:0,y:24,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:24,scale:.98}} className="fixed inset-x-4 top-1/2 z-[81] mx-auto w-auto max-w-lg -translate-y-1/2 rounded-[28px] border border-[#eadfd5] bg-[#fffdf9] p-5 shadow-2xl sm:p-6">
  <div className="flex items-start justify-between gap-4"><div><h3 id="bulk-discount-title" className="text-lg font-black text-[#122b3c]">Apply menu-item discount</h3><p className="mt-1 text-xs font-semibold leading-5 text-[#756960]">This will update {selectedCount} selected item{selectedCount===1?"":"s"}. Existing discounts are replaced using the stored original price, so repeated edits do not compound accidentally.</p></div><button type="button" onClick={onClose} disabled={acting} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-[#e5d9cf] bg-white text-[#122b3c]"><FontAwesomeIcon icon={faXmark}/></button></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Discount type"><select value={type} onChange={e=>onTypeChange(e.target.value as "percentage"|"fixed")} className="field"><option value="percentage">Percentage discount</option><option value="fixed">Fixed amount discount</option></select></Field><Field label={type==="percentage"?"Discount percentage":"Discount amount"}><div className="relative"><FontAwesomeIcon icon={type==="percentage"?faPercent:faIndianRupeeSign} className="absolute left-3 top-1/2 h-3 -translate-y-1/2 text-[#8c7f76]"/><input type="number" min="0.01" max={type==="percentage"?"99.99":undefined} step="0.01" value={value} onChange={e=>onValueChange(e.target.value)} placeholder={type==="percentage"?"20":"50"} className="field price-field"/></div></Field></div>
  <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-[11px] font-semibold leading-5 text-amber-900">Percentage applies the same percent to every selected item and every size. Fixed amount subtracts the same rupee amount from each item or size. Combos are intentionally rejected because their selling price belongs to the Combo Builder.</div>
  {error&&<p className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700">{error}</p>}
  <div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={onClose} disabled={acting} className="h-11 rounded-2xl border border-[#e5d9cf] bg-white text-xs font-black text-[#122b3c]">Cancel</button><button type="button" onClick={onApply} disabled={acting} className="h-11 rounded-2xl bg-[#C8102E] text-xs font-black text-white disabled:opacity-60">{acting?"Applying…":"Apply discount"}</button></div>
 </motion.section></>}</AnimatePresence>;
}
