import type { ItemForm, MenuItem, ModifierGroup } from "@/components/admin/menu/admin-menu.types";
import { isAllowedNaanModifierGroup, isThinCrustExcludedPizza } from "@/lib/menu-special-config";

type SaveContext={form:ItemForm;items:MenuItem[];modifierGroups:ModifierGroup[];editingId:string|null;isPizzaCategory:boolean;isNaanCategory:boolean;isComboCategory:boolean;hasRequiredVariants:boolean;combinationGroup?:ModifierGroup};

export function validateMenuItemForm(ctx:SaveContext):string|null {
 const {form,isPizzaCategory,isNaanCategory,isComboCategory,hasRequiredVariants,combinationGroup}=ctx;
 const variants=hasRequiredVariants?form.variants.filter(v=>v.name.trim()):[];
 if(!form.name.trim()||!form.categoryId)return "Item name and category are required.";
 if(isPizzaCategory&&(variants.length!==3||variants.some(v=>v.price===""||Number(v.price)<0)))return "Enter a valid price for Small 7 inch, Medium 9 inch and Large 12 inch.";
 if(isNaanCategory&&variants.length!==2)return "Half Plate and Full Plate portions are required for this naan.";
 if(isNaanCategory){const expected=variants.length*(combinationGroup?.options.filter(o=>o._id&&o.isActive&&o.isAvailable!==false).length??0);const valid=form.combinationPricing.entries.filter(e=>e.price!==""&&Number(e.price)>=0);if(!form.combinationPricing.enabled||!combinationGroup||expected===0||valid.length!==expected)return "Select the second-sabji group and enter every Half/Full combination price.";}
 if(!hasRequiredVariants&&(form.basePrice===""||Number(form.basePrice)<0))return "Selling price is required.";
 if(!isComboCategory&&!hasRequiredVariants&&form.compareAtPrice!==""&&Number(form.compareAtPrice)<=Number(form.basePrice))return "Original price must be greater than the discounted selling price.";
 if(!isComboCategory&&hasRequiredVariants&&variants.some(v=>v.compareAtPrice!==""&&Number(v.compareAtPrice)<=Number(v.price)))return "Each variant original price must be greater than its discounted selling price.";
 if(form.isCombo&&form.comboOfferType==="limited"&&(!form.comboOfferStartsAt||!form.comboOfferExpiresAt))return "Limited-time combos require start and expiry dates.";
 if(form.isCombo&&form.publishComboOnOffersPage&&form.comboOffersPageSection==="todays"&&!form.comboOfferStartsAt)return "Select when the 24-hour Today’s Hot Offer should start.";
 if(form.isTodaysSpecialOffer&&!form.todaysSpecialOfferStartsAt)return "Select when the 24-hour special offer should start.";
 return null;
}

export function buildMenuItemPayload(ctx:SaveContext){
 const {form,items,modifierGroups,editingId,isPizzaCategory,isNaanCategory,isComboCategory,hasRequiredVariants}=ctx;
 const active=hasRequiredVariants?form.variants.filter(v=>v.name.trim()):[];
 const variants=active.map((v,i)=>{const prices=isNaanCategory?form.combinationPricing.entries.filter(e=>e.variantLabel===v.name&&e.price!==""&&Number(e.price)>=0).map(e=>Number(e.price)):[];return{name:v.name.trim(),sku:v.sku.trim(),price:isNaanCategory?(prices.length?Math.min(...prices):0):Number(v.price),compareAtPrice:v.compareAtPrice===""?null:Number(v.compareAtPrice),isDefault:v.isDefault||(!active.some(x=>x.isDefault)&&i===0),isActive:v.isActive,sortOrder:Number(v.sortOrder||i)}});const defaultVariant=variants.find(v=>v.isDefault)??variants[0];
 return {name:form.name.trim(),slug:form.slug.trim()||undefined,categoryId:form.categoryId,shortDescription:form.shortDescription.trim(),description:form.description.trim(),imageUrl:form.imageUrl.trim(),basePrice:hasRequiredVariants&&defaultVariant?defaultVariant.price:Number(form.basePrice),compareAtPrice:isComboCategory||hasRequiredVariants||form.compareAtPrice===""?null:Number(form.compareAtPrice),spiceLevel:form.spiceLevel,preparationTimeMinutes:Number(form.preparationTimeMinutes||15),tags:form.tags.split(",").map(v=>v.trim()).filter(Boolean),allergens:form.allergens.split(",").map(v=>v.trim()).filter(Boolean),availableForDineIn:form.availableForDineIn,availableForTakeaway:form.availableForTakeaway,isAvailable:form.isAvailable,isActive:form.isActive,isFeatured:form.isFeatured,isBestseller:form.isBestseller,isCombo:isComboCategory,comboComponents:isComboCategory?form.comboComponents.map(e=>({menuItemId:e.menuItemId,variantId:e.variantId||null,quantity:Number(e.quantity)})):[],comboOfferType:form.comboOfferType,comboOfferStartsAt:form.isCombo&&form.comboOfferStartsAt?new Date(form.comboOfferStartsAt).toISOString():null,comboOfferExpiresAt:form.isCombo&&form.comboOfferType==="limited"&&form.comboOfferExpiresAt?new Date(form.comboOfferExpiresAt).toISOString():null,publishComboOnMenuPage:form.isCombo?form.publishComboOnMenuPage:true,publishComboOnOffersPage:form.isCombo?form.publishComboOnOffersPage:false,comboOffersPageSection:form.comboOffersPageSection,eligibleTierKeys:form.eligibleTierKeys,isTodaysSpecialOffer:form.isTodaysSpecialOffer,todaysSpecialOfferStartsAt:form.isTodaysSpecialOffer&&form.todaysSpecialOfferStartsAt?new Date(form.todaysSpecialOfferStartsAt).toISOString():null,trackInventory:form.trackInventory,sortOrder:Number(form.sortOrder||0),galleryUrls:[],variants,combinationPricing:isNaanCategory?{enabled:true,modifierGroupId:form.combinationPricing.modifierGroupId,entries:form.combinationPricing.entries.map(e=>({...e,price:Number(e.price)}))}:{enabled:false,modifierGroupId:null,entries:[]},pizzaConfiguration:isPizzaCategory?{thinCrustAvailable:!isThinCrustExcludedPizza(form.name)&&form.pizzaConfiguration.thinCrustAvailable,thinCrustPriceAdjustment:0}:{thinCrustAvailable:false,thinCrustPriceAdjustment:0},modifierGroupIds:isNaanCategory?form.modifierGroupIds.filter(id=>{const g=modifierGroups.find(x=>x._id===id);return Boolean(g&&isAllowedNaanModifierGroup(g.name,g.internalName))}):form.modifierGroupIds,frequentlyOrderedWithIds:form.frequentlyOrderedWithIds.filter(id=>id!==editingId&&items.some(x=>x._id===id&&x.isActive)),taxClassId:null,calories:null,availabilityWindows:[]};
}
