import { requirePermission } from "@/lib/auth/session";
import { connectToDatabase } from "@/lib/db/mongoose";
import { handleApiError } from "@/lib/errors/handleApiError";
import { AppError } from "@/lib/errors/AppError";
import { successResponse } from "@/lib/http/apiResponse";
import { Order } from "@/models/Order";
import { Invoice } from "@/models/Invoice";
import { PrintJob } from "@/models/PrintJob";
export async function GET(_:Request,context:{params:Promise<{id:string}>}){try{await requirePermission("orders.read");await connectToDatabase();const{id}=await context.params;const order=await Order.findById(id).populate("createdBy updatedBy cashierId","name email").lean();if(!order)throw new AppError("Order not found.",404);const [invoice,prints]=await Promise.all([Invoice.findOne({orderId:id}).lean(),PrintJob.find({orderId:id}).populate("requestedBy","name email").sort({requestedAt:1}).lean()]);const events:Array<{at:Date;type:string;title:string;detail:string;actor:string}>=[{at:order.createdAt,type:"order",title:"Order created",detail:`${order.orderMode.replace("_"," ")} · ${order.itemCount} items`,actor:"createdBy" in order&&typeof order.createdBy==="object"&&order.createdBy?String((order.createdBy as {name?:string}).name??""):""},...(order.statusHistory??[]).map(h=>({at:h.changedAt,type:"status",title:`Status changed to ${h.status}`,detail:h.note??"",actor:""}))];if(order.paymentConfirmedAt)events.push({at:order.paymentConfirmedAt,type:"payment",title:"Payment confirmed",detail:`${order.paymentMethod.toUpperCase()} · ₹${order.grandTotal}`,actor:""});if(invoice)events.push({at:invoice.issuedAt,type:"invoice",title:"Invoice generated",detail:invoice.invoiceNumber,actor:""});for(const p of prints)events.push({at:p.requestedAt,type:"print",title:`${p.documentType.replace("_"," ")} opened`,detail:`${p.paper} · ${p.copies} copy`,actor:typeof p.requestedBy==="object"&&p.requestedBy?String((p.requestedBy as {name?:string}).name??""):""});events.sort((a,b)=>a.at.getTime()-b.at.getTime());return successResponse({order:{id:String(order._id),orderNumber:order.orderNumber,status:order.status,paymentStatus:order.paymentStatus,grandTotal:order.grandTotal},events});}catch(error){return handleApiError(error)}}
