import { Types } from "mongoose";
import type { z } from "zod";
import { connectToDatabase } from "@/lib/db/mongoose";
import { AppError } from "@/lib/errors/AppError";
import { PayableBill } from "@/models/PayableBill";
import { PayablePayment } from "@/models/PayablePayment";
import { AccountsPayableSnapshot } from "@/models/AccountsPayableSnapshot";
import type { payableBillCreateSchema,payableBillUpdateSchema,payablePaymentCreateSchema } from "@/validators/accounts-payable";
const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;const dayKey=(d:Date)=>d.toISOString().slice(0,10);
export const getPayableRange=(days:number)=>{const end=new Date();const start=new Date(end);start.setUTCDate(start.getUTCDate()-Math.max(1,days)+1);start.setUTCHours(0,0,0,0);end.setUTCHours(23,59,59,999);return{start,end,days};};
function calculate(input:{subtotal:number;taxAmount:number;discountAmount:number;creditAmount:number;paidAmount:number;writtenOffAmount:number;dueDate:Date;status:string}){const totalAmount=round(Math.max(0,input.subtotal+input.taxAmount-input.discountAmount-input.creditAmount));const paidAmount=round(Math.min(totalAmount,input.paidAmount));const writtenOffAmount=round(Math.min(Math.max(0,totalAmount-paidAmount),input.writtenOffAmount));const outstandingAmount=round(Math.max(0,totalAmount-paidAmount-writtenOffAmount));let status=input.status;if(!["draft","pending_approval","rejected","cancelled"].includes(status)){if(outstandingAmount===0)status=writtenOffAmount>0?"written_off":"paid";else if(paidAmount>0)status="partially_paid";else if(input.dueDate.getTime()<Date.now())status="overdue";else status="approved";}return{totalAmount,paidAmount,writtenOffAmount,outstandingAmount,status};}
async function nextNumber(model:{collection:{countDocuments(filter:Record<string,unknown>):Promise<number>}},prefix:string,field:"billNumber"|"paymentNumber"){const date=new Date().toISOString().slice(0,10).replaceAll("-","");const base=`${prefix}-${date}`;const count=await model.collection.countDocuments({[field]:{$regex:`^${base}-`}});return`${base}-${String(count+1).padStart(4,"0")}`;}
export async function createPayableBill(input:z.infer<typeof payableBillCreateSchema>,actorId:string){await connectToDatabase();const actor=new Types.ObjectId(actorId);const values=calculate({...input,paidAmount:0,writtenOffAmount:0,status:input.status});const doc=new PayableBill({...input,vendorId:input.vendorId?new Types.ObjectId(input.vendorId):null,purchaseOrderId:input.purchaseOrderId?new Types.ObjectId(input.purchaseOrderId):null,billNumber:await nextNumber(PayableBill,"AP","billNumber"),...values,submittedAt:input.status==="pending_approval"?new Date():null,createdBy:actor,updatedBy:actor});await doc.save();return doc;}
export async function updatePayableBill(id:string,input:z.infer<typeof payableBillUpdateSchema>,actorId:string){await connectToDatabase();const doc=await PayableBill.findById(id);if(!doc)throw new AppError("Payable bill not found.",404);if(["paid","written_off"].includes(doc.status))throw new AppError("Closed bills cannot be edited.",409);Object.assign(doc,input,{vendorId:input.vendorId===undefined?doc.vendorId:input.vendorId?new Types.ObjectId(input.vendorId):null,purchaseOrderId:input.purchaseOrderId===undefined?doc.purchaseOrderId:input.purchaseOrderId?new Types.ObjectId(input.purchaseOrderId):null,updatedBy:new Types.ObjectId(actorId)});if(input.status==="pending_approval"&&!doc.submittedAt)doc.submittedAt=new Date();if(input.status==="approved"){doc.approvedAt=new Date();doc.approvedBy=new Types.ObjectId(actorId);}if(input.status==="rejected"){doc.rejectedAt=new Date();doc.rejectedBy=new Types.ObjectId(actorId);doc.rejectionReason=input.rejectionReason??"";}if(input.status==="cancelled"){doc.cancelledAt=new Date();doc.cancellationReason=input.cancellationReason??"";}const values=calculate({subtotal:doc.subtotal,taxAmount:doc.taxAmount,discountAmount:doc.discountAmount,creditAmount:doc.creditAmount,paidAmount:doc.paidAmount,writtenOffAmount:doc.writtenOffAmount,dueDate:doc.dueDate,status:doc.status});Object.assign(doc,values);await doc.save();return doc;}
export async function recordPayablePayment(billId:string,input:z.infer<typeof payablePaymentCreateSchema>,actorId:string){await connectToDatabase();const bill=await PayableBill.findById(billId);if(!bill)throw new AppError("Payable bill not found.",404);if(!["approved","partially_paid","overdue"].includes(bill.status))throw new AppError("Payment can only be recorded against an approved payable bill.",409);if(input.amount>bill.outstandingAmount)throw new AppError("Payment exceeds the outstanding balance.",400);const payment=new PayablePayment({...input,paymentNumber:await nextNumber(PayablePayment,"APP","paymentNumber"),billId:bill._id,vendorId:bill.vendorId,recordedBy:new Types.ObjectId(actorId)});await payment.save();const values=calculate({subtotal:bill.subtotal,taxAmount:bill.taxAmount,discountAmount:bill.discountAmount,creditAmount:bill.creditAmount,paidAmount:bill.paidAmount+input.amount,writtenOffAmount:bill.writtenOffAmount,dueDate:bill.dueDate,status:bill.status});Object.assign(bill,values,{paidAt:values.outstandingAmount===0?new Date():null,updatedBy:new Types.ObjectId(actorId)});await bill.save();return{bill,payment};}
export async function writeOffPayable(billId:string,amount:number,reason:string,actorId:string){await connectToDatabase();const bill=await PayableBill.findById(billId);if(!bill)throw new AppError("Payable bill not found.",404);if(amount>bill.outstandingAmount)throw new AppError("Write-off exceeds outstanding balance.",400);const values=calculate({subtotal:bill.subtotal,taxAmount:bill.taxAmount,discountAmount:bill.discountAmount,creditAmount:bill.creditAmount,paidAmount:bill.paidAmount,writtenOffAmount:bill.writtenOffAmount+amount,dueDate:bill.dueDate,status:bill.status});Object.assign(bill,values,{writtenOffAt:new Date(),writeOffReason:reason,updatedBy:new Types.ObjectId(actorId)});await bill.save();return bill;}
type Row={count:number;billed:number;paid:number;outstanding:number};function add(map:Map<string,Row>,key:string,v:Omit<Row,"count">){const row=map.get(key)??{count:0,billed:0,paid:0,outstanding:0};row.count++;row.billed+=v.billed;row.paid+=v.paid;row.outstanding+=v.outstanding;map.set(key,row);}function finalize(map:Map<string,Row>){return[...map.entries()].map(([key,v])=>({key,count:v.count,billed:round(v.billed),paid:round(v.paid),outstanding:round(v.outstanding)}));}
export async function buildAccountsPayableSnapshot(input:{days:number;source:"manual"|"scheduled"|"system";generatedBy?:string|null}){await connectToDatabase();const range=getPayableRange(input.days);const bills=await PayableBill.find({billDate:{$gte:range.start,$lte:range.end},status:{$nin:["cancelled","rejected"]}}).lean();const byStatus=new Map<string,Row>(),byVendor=new Map<string,Row>(),byDepartment=new Map<string,Row>(),byDay=new Map<string,Row>();const vendors=new Set<string>();let billed=0,paid=0,outstanding=0,overdue=0,writtenOff=0,credit=0,weightedDays=0;const aging={current:0,days1To30:0,days31To60:0,days61To90:0,daysOver90:0};for(const bill of bills){const total=Number(bill.totalAmount),settled=Number(bill.paidAmount),open=Number(bill.outstandingAmount);billed+=total;paid+=settled;outstanding+=open;writtenOff+=Number(bill.writtenOffAmount);credit+=Number(bill.creditAmount);vendors.add(bill.vendorId?.toString()??bill.vendorName);const v={billed:total,paid:settled,outstanding:open};add(byStatus,bill.status,v);add(byVendor,bill.vendorName,v);add(byDepartment,bill.department,v);add(byDay,dayKey(new Date(bill.billDate)),v);if(open>0){const daysPast=Math.max(0,Math.floor((Date.now()-new Date(bill.dueDate).getTime())/86400000));weightedDays+=open*daysPast;if(daysPast===0)aging.current+=open;else if(daysPast<=30)aging.days1To30+=open;else if(daysPast<=60)aging.days31To60+=open;else if(daysPast<=90)aging.days61To90+=open;else aging.daysOver90+=open;if(daysPast>0)overdue+=open;}}
const metrics={billCount:bills.length,vendorCount:vendors.size,billedAmount:round(billed),paidAmount:round(paid),outstandingAmount:round(outstanding),overdueAmount:round(overdue),writtenOffAmount:round(writtenOff),creditAmount:round(credit),paymentRate:billed?round(paid/billed*100):0,averageDaysPayable:outstanding?round(weightedDays/outstanding):0};const roundedAging=Object.fromEntries(Object.entries(aging).map(([k,v])=>[k,round(v)]));const periodKey=`${dayKey(range.start)}_${dayKey(range.end)}`;return AccountsPayableSnapshot.findOneAndUpdate({periodKey},{$set:{periodStart:range.start,periodEnd:range.end,currency:"INR",metrics,aging:roundedAging,byStatus:finalize(byStatus),byVendor:finalize(byVendor).sort((a,b)=>b.outstanding-a.outstanding).slice(0,20),byDepartment:finalize(byDepartment).sort((a,b)=>b.outstanding-a.outstanding),byDay:finalize(byDay).sort((a,b)=>a.key.localeCompare(b.key)),generatedAt:new Date(),generatedBy:input.generatedBy?new Types.ObjectId(input.generatedBy):null,source:input.source}},{upsert:true,returnDocument:"after",runValidators:true}).lean();}
export async function getAccountsPayableSummary(days:number){await connectToDatabase();const range=getPayableRange(days);const periodKey=`${dayKey(range.start)}_${dayKey(range.end)}`;const[snapshot,recentBills]=await Promise.all([AccountsPayableSnapshot.findOne({periodKey}).lean(),PayableBill.find({billDate:{$gte:range.start,$lte:range.end}}).sort({billDate:-1}).limit(25).lean()]);return{snapshot:snapshot??await buildAccountsPayableSnapshot({days,source:"system"}),recentBills};}
