import { Types } from "mongoose";
import type { z } from "zod";
import { connectToDatabase } from "@/lib/db/mongoose";
import { AppError } from "@/lib/errors/AppError";
import { ReceivableInvoice } from "@/models/ReceivableInvoice";
import { ReceivablePayment } from "@/models/ReceivablePayment";
import { AccountsReceivableSnapshot } from "@/models/AccountsReceivableSnapshot";
import type { receivableInvoiceCreateSchema, receivableInvoiceUpdateSchema, receivablePaymentCreateSchema } from "@/validators/accounts-receivable";
const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;
const dayKey=(d:Date)=>d.toISOString().slice(0,10);
export const getReceivableRange=(days:number)=>{const end=new Date();const start=new Date(end);start.setUTCDate(start.getUTCDate()-Math.max(1,days)+1);start.setUTCHours(0,0,0,0);end.setUTCHours(23,59,59,999);return{start,end,days};};
function calculate(input:{subtotal:number;taxAmount:number;discountAmount:number;creditAmount:number;paidAmount:number;writtenOffAmount:number;dueDate:Date;status:string}){const totalAmount=round(Math.max(0,input.subtotal+input.taxAmount-input.discountAmount-input.creditAmount));const paidAmount=round(Math.min(totalAmount,input.paidAmount));const writtenOffAmount=round(Math.min(Math.max(0,totalAmount-paidAmount),input.writtenOffAmount));const outstandingAmount=round(Math.max(0,totalAmount-paidAmount-writtenOffAmount));let status=input.status;if(!["draft","cancelled"].includes(status)){if(outstandingAmount===0)status=writtenOffAmount>0?"written_off":"paid";else if(paidAmount>0)status="partially_paid";else if(input.dueDate.getTime()<Date.now())status="overdue";else status="issued";}return{totalAmount,paidAmount,writtenOffAmount,outstandingAmount,status};}
async function nextNumber(model:typeof ReceivableInvoice|typeof ReceivablePayment,prefix:string,field:"invoiceNumber"|"paymentNumber"){const date=new Date().toISOString().slice(0,10).replaceAll("-","");const base=`${prefix}-${date}`;const count=await model.collection.countDocuments({[field]:{$regex:`^${base}-`}});return`${base}-${String(count+1).padStart(4,"0")}`;}
export async function createReceivableInvoice(input:z.infer<typeof receivableInvoiceCreateSchema>,actorId:string){await connectToDatabase();const actor=new Types.ObjectId(actorId);const values=calculate({...input,paidAmount:0,writtenOffAmount:0,status:input.status});const doc=new ReceivableInvoice({...input,customerId:input.customerId?new Types.ObjectId(input.customerId):null,orderId:input.orderId?new Types.ObjectId(input.orderId):null,invoiceNumber:await nextNumber(ReceivableInvoice,"AR", "invoiceNumber"),...values,issuedAt:input.status==="issued"?new Date():null,createdBy:actor,updatedBy:actor});await doc.save();return doc;}
export async function updateReceivableInvoice(id:string,input:z.infer<typeof receivableInvoiceUpdateSchema>,actorId:string){await connectToDatabase();const doc=await ReceivableInvoice.findById(id);if(!doc)throw new AppError("Receivable invoice not found.",404);if(["paid","written_off"].includes(doc.status))throw new AppError("Closed invoices cannot be edited.",409);Object.assign(doc,input,{customerId:input.customerId===undefined?doc.customerId:input.customerId?new Types.ObjectId(input.customerId):null,orderId:input.orderId===undefined?doc.orderId:input.orderId?new Types.ObjectId(input.orderId):null,updatedBy:new Types.ObjectId(actorId)});const values=calculate({subtotal:doc.subtotal,taxAmount:doc.taxAmount,discountAmount:doc.discountAmount,creditAmount:doc.creditAmount,paidAmount:doc.paidAmount,writtenOffAmount:doc.writtenOffAmount,dueDate:doc.dueDate,status:doc.status});Object.assign(doc,values);if(input.status==="issued"&&!doc.issuedAt)doc.issuedAt=new Date();if(input.status==="cancelled"){doc.cancelledAt=new Date();doc.cancellationReason=input.cancellationReason??"";}await doc.save();return doc;}
export async function recordReceivablePayment(invoiceId:string,input:z.infer<typeof receivablePaymentCreateSchema>,actorId:string){await connectToDatabase();const invoice=await ReceivableInvoice.findById(invoiceId);if(!invoice)throw new AppError("Receivable invoice not found.",404);if(["draft","cancelled","paid","written_off"].includes(invoice.status))throw new AppError("Payment cannot be recorded against this invoice.",409);if(input.amount>invoice.outstandingAmount)throw new AppError("Payment exceeds the outstanding balance.",400);const payment=new ReceivablePayment({...input,paymentNumber:await nextNumber(ReceivablePayment,"ARP","paymentNumber"),invoiceId:invoice._id,customerId:invoice.customerId,recordedBy:new Types.ObjectId(actorId)});await payment.save();const values=calculate({subtotal:invoice.subtotal,taxAmount:invoice.taxAmount,discountAmount:invoice.discountAmount,creditAmount:invoice.creditAmount,paidAmount:invoice.paidAmount+input.amount,writtenOffAmount:invoice.writtenOffAmount,dueDate:invoice.dueDate,status:invoice.status});Object.assign(invoice,values,{paidAt:values.outstandingAmount===0?new Date():null,updatedBy:new Types.ObjectId(actorId)});await invoice.save();return{invoice,payment};}
export async function writeOffReceivable(invoiceId:string,amount:number,reason:string,actorId:string){await connectToDatabase();const invoice=await ReceivableInvoice.findById(invoiceId);if(!invoice)throw new AppError("Receivable invoice not found.",404);if(amount>invoice.outstandingAmount)throw new AppError("Write-off exceeds outstanding balance.",400);const values=calculate({subtotal:invoice.subtotal,taxAmount:invoice.taxAmount,discountAmount:invoice.discountAmount,creditAmount:invoice.creditAmount,paidAmount:invoice.paidAmount,writtenOffAmount:invoice.writtenOffAmount+amount,dueDate:invoice.dueDate,status:invoice.status});Object.assign(invoice,values,{writtenOffAt:new Date(),writeOffReason:reason,updatedBy:new Types.ObjectId(actorId)});await invoice.save();return invoice;}
type Row={count:number;invoiced:number;paid:number;outstanding:number};function add(map:Map<string,Row>,key:string,v:Omit<Row,"count">){const row=map.get(key)??{count:0,invoiced:0,paid:0,outstanding:0};row.count++;row.invoiced+=v.invoiced;row.paid+=v.paid;row.outstanding+=v.outstanding;map.set(key,row);}function finalize(map:Map<string,Row>){return[...map.entries()].map(([key,v])=>({key,count:v.count,invoiced:round(v.invoiced),paid:round(v.paid),outstanding:round(v.outstanding)}));}
export async function buildAccountsReceivableSnapshot(input:{days:number;source:"manual"|"scheduled"|"system";generatedBy?:string|null}){await connectToDatabase();const range=getReceivableRange(input.days);const invoices=await ReceivableInvoice.find({invoiceDate:{$gte:range.start,$lte:range.end},status:{$ne:"cancelled"}}).lean();const byStatus=new Map<string,Row>(),byCustomer=new Map<string,Row>(),byDay=new Map<string,Row>();const customers=new Set<string>();let issued=0,collected=0,outstanding=0,overdue=0,writtenOff=0,credit=0,weightedDays=0;const aging={current:0,days1To30:0,days31To60:0,days61To90:0,daysOver90:0};for(const inv of invoices){const total=Number(inv.totalAmount),paid=Number(inv.paidAmount),open=Number(inv.outstandingAmount);issued+=total;collected+=paid;outstanding+=open;writtenOff+=Number(inv.writtenOffAmount);credit+=Number(inv.creditAmount);const customerKey=inv.customerId?.toString()??inv.customerName;customers.add(customerKey);const v={invoiced:total,paid,outstanding:open};add(byStatus,inv.status,v);add(byCustomer,inv.customerName,v);add(byDay,dayKey(new Date(inv.invoiceDate)),v);if(open>0){const daysPast=Math.max(0,Math.floor((Date.now()-new Date(inv.dueDate).getTime())/86400000));weightedDays+=open*daysPast;if(daysPast===0)aging.current+=open;else if(daysPast<=30)aging.days1To30+=open;else if(daysPast<=60)aging.days31To60+=open;else if(daysPast<=90)aging.days61To90+=open;else aging.daysOver90+=open;if(daysPast>0)overdue+=open;}}
const metrics={invoiceCount:invoices.length,customerCount:customers.size,issuedAmount:round(issued),collectedAmount:round(collected),outstandingAmount:round(outstanding),overdueAmount:round(overdue),writtenOffAmount:round(writtenOff),creditAmount:round(credit),collectionRate:issued?round(collected/issued*100):0,averageDaysOutstanding:outstanding?round(weightedDays/outstanding):0};const roundedAging=Object.fromEntries(Object.entries(aging).map(([k,v])=>[k,round(v)]));const periodKey=`${dayKey(range.start)}_${dayKey(range.end)}`;return AccountsReceivableSnapshot.findOneAndUpdate({periodKey},{$set:{periodStart:range.start,periodEnd:range.end,currency:"INR",metrics,aging:roundedAging,byStatus:finalize(byStatus),byCustomer:finalize(byCustomer).sort((a,b)=>b.outstanding-a.outstanding).slice(0,20),byDay:finalize(byDay).sort((a,b)=>a.key.localeCompare(b.key)),generatedAt:new Date(),generatedBy:input.generatedBy?new Types.ObjectId(input.generatedBy):null,source:input.source}},{upsert:true,returnDocument:"after",runValidators:true}).lean();}
export async function getAccountsReceivableSummary(days:number){await connectToDatabase();const range=getReceivableRange(days);const periodKey=`${dayKey(range.start)}_${dayKey(range.end)}`;const[snapshot,recentInvoices]=await Promise.all([AccountsReceivableSnapshot.findOne({periodKey}).lean(),ReceivableInvoice.find({invoiceDate:{$gte:range.start,$lte:range.end}}).sort({invoiceDate:-1}).limit(25).lean()]);return{snapshot:snapshot??await buildAccountsReceivableSnapshot({days,source:"system"}),recentInvoices};}
