import { Types } from "mongoose";
import { CustomerInsight } from "@/models/CustomerInsight";
import { CustomerProfile } from "@/models/CustomerProfile";
import { CustomerTimelineEvent } from "@/models/CustomerTimelineEvent";
import { Order } from "@/models/Order";
import { Reservation } from "@/models/Reservation";
import { Review } from "@/models/Review";
import { User } from "@/models/User";
import { getCustomerRoleId } from "@/services/userManagement.service";

type PlainOrder={_id:Types.ObjectId;customerId:Types.ObjectId|null;status:string;grandTotal:number;orderMode:string;tableNumber:string;coinsEarned:number;coinsRedeemed:number;createdAt:Date;items:Array<{menuItemId?:Types.ObjectId|null;name:string;quantity:number;lineTotal:number}>};
type PlainReservation={_id:Types.ObjectId;customerId:Types.ObjectId;status:string;tableNumber:string;reservationDate:Date;createdAt:Date};
type PlainReview={_id:Types.ObjectId;customerId:Types.ObjectId;rating:number;createdAt:Date};
const day=86_400_000; const round=(n:number,d=2)=>Number(n.toFixed(d));
function segmentCustomer(value:number,orders:number,days:number,createdAt:Date){const keys:string[]=[];if(orders===0&&Date.now()-createdAt.getTime()<=30*day)keys.push("new");if(orders>=3)keys.push("loyal");if(value>=10000||orders>=12)keys.push("vip");if(value>=5000)keys.push("high_spender");if(orders>0&&days>=30&&days<90)keys.push("at_risk");if(orders>0&&days>=90)keys.push("lost");if(!keys.length)keys.push("regular");return keys;}
export async function rebuildCustomerInsights(input:{customerId?:string;limit:number}){
 const roleId=await getCustomerRoleId(); const userFilter:Record<string,unknown>={roleId}; if(input.customerId)userFilter._id=new Types.ObjectId(input.customerId);
 const users=await User.find(userFilter).select("_id createdAt").limit(input.limit).lean(); let updated=0;
 for(const user of users){
  const id=user._id; const [orders,reservations,reviews,profile]=await Promise.all([
   Order.find({customerId:id}).select("_id customerId status grandTotal orderMode tableNumber coinsEarned coinsRedeemed createdAt items").sort({createdAt:1}).lean() as unknown as Promise<PlainOrder[]>,
   Reservation.find({customerId:id}).select("_id customerId status tableNumber reservationDate createdAt").lean() as unknown as Promise<PlainReservation[]>,
   Review.find({customerId:id}).select("_id customerId rating createdAt").lean() as unknown as Promise<PlainReview[]>,
   CustomerProfile.findOne({userId:id}).lean(),
  ]);
  const completed=orders.filter(o=>o.status==="completed"); const value=completed.reduce((s,o)=>s+o.grandTotal,0); const first=completed[0]?.createdAt??null; const last=completed.at(-1)?.createdAt??null; const daysSince=last?Math.max(0,Math.floor((Date.now()-new Date(last).getTime())/day)):0;
  const itemMap=new Map<string,{itemId:Types.ObjectId|null;name:string;quantity:number;revenue:number}>(); for(const order of completed)for(const item of order.items){const key=String(item.menuItemId??item.name);const current=itemMap.get(key)??{itemId:item.menuItemId??null,name:item.name,quantity:0,revenue:0};current.quantity+=item.quantity;current.revenue+=item.lineTotal;itemMap.set(key,current);}
  const modes=completed.reduce<Record<string,number>>((a,o)=>(a[o.orderMode]=(a[o.orderMode]??0)+1,a),{}); const hours=completed.map(o=>new Date(o.createdAt).getHours()); const tables=completed.map(o=>o.tableNumber).filter(Boolean); const top=(values:string[])=>values.sort((a,b)=>values.filter(v=>v===a).length-values.filter(v=>v===b).length).at(-1)??"";
  const span=first&&last?Math.max(1,(new Date(last).getTime()-new Date(first).getTime())/day):0; const frequency=completed.length>1?span/(completed.length-1):0; const segments=segmentCustomer(value,completed.length,daysSince,new Date(user.createdAt));
  const engagement=Math.min(100,Math.round(completed.length*6+reservations.length*4+reviews.length*8+(profile?.marketingEmailOptIn?5:0)+(profile?.marketingWhatsAppOptIn?5:0)-Math.min(30,daysSince/3)));
  await CustomerInsight.findOneAndUpdate({customerId:id},{$set:{lifetimeValue:round(value),orderCount:orders.length,completedOrderCount:completed.length,cancelledOrderCount:orders.filter(o=>["cancelled","rejected"].includes(o.status)).length,averageOrderValue:completed.length?round(value/completed.length):0,visitFrequencyDays:round(frequency),daysSinceLastOrder:daysSince,lastOrderAt:last,firstOrderAt:first,reservationCount:reservations.length,completedReservationCount:reservations.filter(r=>r.status==="completed").length,noShowCount:reservations.filter(r=>r.status==="no_show").length,reviewCount:reviews.length,averageRating:reviews.length?round(reviews.reduce((s,r)=>s+r.rating,0)/reviews.length):0,referralCount:profile?.successfulReferralCount??0,coinsEarned:orders.reduce((s,o)=>s+(o.coinsEarned??0),0),coinsRedeemed:orders.reduce((s,o)=>s+(o.coinsRedeemed??0),0),favoriteItems:[...itemMap.values()].sort((a,b)=>b.quantity-a.quantity).slice(0,5),preferredOrderMode:(Object.entries(modes).sort((a,b)=>b[1]-a[1])[0]?.[0]??"none"),preferredVisitHour:hours.length?Math.round(hours.reduce((s,h)=>s+h,0)/hours.length):null,preferredTable:top(tables),segmentKeys:segments,riskLevel:segments.includes("lost")?"high":segments.includes("at_risk")?"medium":"low",engagementScore:Math.max(0,engagement),generatedAt:new Date()}},{upsert:true,new:true,setDefaultsOnInsert:true}); updated++;
 }
 return {processed:users.length,updated,generatedAt:new Date()};
}
export async function getCrmSummary(){const [customers,insights]=await Promise.all([CustomerInsight.countDocuments(),CustomerInsight.find().select("lifetimeValue completedOrderCount segmentKeys riskLevel engagementScore").lean()]);const ltv=insights.reduce((s,x)=>s+x.lifetimeValue,0);return{customers,totalLifetimeValue:round(ltv),averageLifetimeValue:customers?round(ltv/customers):0,totalCompletedOrders:insights.reduce((s,x)=>s+x.completedOrderCount,0),vipCustomers:insights.filter(x=>x.segmentKeys.includes("vip")).length,atRiskCustomers:insights.filter(x=>x.riskLevel!=="low").length,averageEngagement:customers?round(insights.reduce((s,x)=>s+x.engagementScore,0)/customers):0,segments:["new","regular","loyal","vip","high_spender","at_risk","lost"].map(key=>({key,count:insights.filter(x=>x.segmentKeys.includes(key)).length}))};}
export async function listCrmCustomers(params:URLSearchParams){const page=Math.max(1,Number(params.get("page")||1));const limit=Math.min(100,Math.max(1,Number(params.get("limit")||20)));const segment=params.get("segment")||"";const risk=params.get("risk")||"";const filter:Record<string,unknown>={};if(segment)filter.segmentKeys=segment;if(risk)filter.riskLevel=risk;const [rows,total]=await Promise.all([CustomerInsight.find(filter).populate("customerId","name email phone avatarUrl isActive createdAt").sort({lifetimeValue:-1}).skip((page-1)*limit).limit(limit).lean(),CustomerInsight.countDocuments(filter)]);return{rows,page,limit,total,totalPages:Math.ceil(total/limit)};}
export async function getCustomer360(customerId:string){const [user,profile,insight]=await Promise.all([User.findById(customerId).select("name email phone avatarUrl isActive emailVerifiedAt lastLoginAt createdAt").lean(),CustomerProfile.findOne({userId:customerId}).lean(),CustomerInsight.findOne({customerId}).lean()]);if(!user)return null;return{user,profile,insight};}
export async function getCustomerTimeline(customerId:string,limit=50){const [events,orders,reservations,reviews]=await Promise.all([CustomerTimelineEvent.find({customerId}).sort({occurredAt:-1}).limit(limit).lean(),Order.find({customerId}).select("orderNumber status grandTotal createdAt").sort({createdAt:-1}).limit(limit).lean(),Reservation.find({customerId}).select("reservationNumber status reservationDate createdAt").sort({createdAt:-1}).limit(limit).lean(),Review.find({customerId}).select("rating title createdAt").sort({createdAt:-1}).limit(limit).lean()]);return[...events.map(e=>({type:e.eventType,title:e.title,description:e.description,occurredAt:e.occurredAt,amount:e.amount})),...orders.map(o=>({type:"order",title:`Order ${o.orderNumber}`,description:o.status,occurredAt:o.createdAt,amount:o.grandTotal})),...reservations.map(r=>({type:"reservation",title:`Reservation ${r.reservationNumber}`,description:r.status,occurredAt:r.createdAt,amount:0})),...reviews.map(r=>({type:"review",title:`${r.rating}-star review`,description:r.title||"Customer review",occurredAt:r.createdAt,amount:0}))].sort((a,b)=>new Date(b.occurredAt).getTime()-new Date(a.occurredAt).getTime()).slice(0,limit);}
