import { Types } from "mongoose";
import { CampaignExecution } from "@/models/CampaignExecution";
import { CustomerAnalyticsSnapshot } from "@/models/CustomerAnalyticsSnapshot";
import { CustomerInsight } from "@/models/CustomerInsight";
import { MarketingCampaign } from "@/models/MarketingCampaign";
import { Order } from "@/models/Order";
import { Reservation } from "@/models/Reservation";
import { Review } from "@/models/Review";
import { User } from "@/models/User";
const DAY=86_400_000;const round=(n:number,d=2)=>Number(n.toFixed(d));const monthKey=(date:Date)=>`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,"0")}`;
type OrderRow={customerId:Types.ObjectId|null;grandTotal:number;status:string;createdAt:Date;couponDiscount:number;coinDiscount:number};
export async function buildCustomerAnalytics(input:{days:number;cohortMonths:number;source:"manual"|"scheduled"|"script"}){const now=new Date();const since=new Date(now.getTime()-input.days*DAY);const cohortSince=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-input.cohortMonths+1,1));const [orders,insights,users,reservations,reviews,campaigns,executions]=await Promise.all([Order.find({createdAt:{$gte:cohortSince},customerId:{$ne:null}}).select("customerId grandTotal status createdAt couponDiscount coinDiscount").lean() as unknown as Promise<OrderRow[]>,CustomerInsight.find().select("customerId lifetimeValue completedOrderCount segmentKeys riskLevel firstOrderAt lastOrderAt").lean(),User.find({createdAt:{$gte:cohortSince}}).select("_id createdAt").lean(),Reservation.find({createdAt:{$gte:since}}).select("customerId status createdAt").lean(),Review.find({createdAt:{$gte:since}}).select("customerId createdAt").lean(),MarketingCampaign.find({createdAt:{$gte:since}}).select("name channel metrics createdAt").lean(),CampaignExecution.find({createdAt:{$gte:since}}).select("campaignId customerId status createdAt convertedAt").lean()]);
 const completed=orders.filter(o=>o.status==="completed");const current=completed.filter(o=>new Date(o.createdAt)>=since);const customerMap=new Map<string,OrderRow[]>();for(const order of completed){const id=String(order.customerId);const list=customerMap.get(id)??[];list.push(order);customerMap.set(id,list)}const activeIds=new Set(current.map(o=>String(o.customerId)));const repeatIds=new Set([...customerMap].filter(([,rows])=>rows.filter(r=>new Date(r.createdAt)>=since).length>=2).map(([id])=>id));const previousStart=new Date(since.getTime()-input.days*DAY);const previousIds=new Set(completed.filter(o=>new Date(o.createdAt)>=previousStart&&new Date(o.createdAt)<since).map(o=>String(o.customerId)));const retained=[...previousIds].filter(id=>activeIds.has(id)).length;const churned=[...previousIds].filter(id=>!activeIds.has(id)).length;const revenue=current.reduce((s,o)=>s+o.grandTotal,0);const discounts=current.reduce((s,o)=>s+(o.couponDiscount??0)+(o.coinDiscount??0),0);const ltvTotal=insights.reduce((s,x)=>s+x.lifetimeValue,0);const customers=insights.length;
 const growthByMonth=new Map<string,{newCustomers:number;orderingCustomers:Set<string>;orders:number;revenue:number}>();for(const user of users){const key=monthKey(new Date(user.createdAt));const row=growthByMonth.get(key)??{newCustomers:0,orderingCustomers:new Set<string>(),orders:0,revenue:0};row.newCustomers++;growthByMonth.set(key,row)}for(const order of completed){const key=monthKey(new Date(order.createdAt));const row=growthByMonth.get(key)??{newCustomers:0,orderingCustomers:new Set<string>(),orders:0,revenue:0};row.orderingCustomers.add(String(order.customerId));row.orders++;row.revenue+=order.grandTotal;growthByMonth.set(key,row)}const growth=[...growthByMonth].sort(([a],[b])=>a.localeCompare(b)).map(([month,row])=>({month,newCustomers:row.newCustomers,orderingCustomers:row.orderingCustomers.size,orders:row.orders,revenue:round(row.revenue)}));
 const cohortMap=new Map<string,{customers:Set<string>;activity:Map<number,Set<string>>}>();for(const [id,rows] of customerMap){const first=new Date([...rows].sort((a,b)=>+new Date(a.createdAt)-+new Date(b.createdAt))[0].createdAt);const key=monthKey(first);const cohort=cohortMap.get(key)??{customers:new Set<string>(),activity:new Map<number,Set<string>>()};cohort.customers.add(id);for(const row of rows){const d=new Date(row.createdAt);const offset=(d.getUTCFullYear()-first.getUTCFullYear())*12+d.getUTCMonth()-first.getUTCMonth();const set=cohort.activity.get(offset)??new Set<string>();set.add(id);cohort.activity.set(offset,set)}cohortMap.set(key,cohort)}const cohorts=[...cohortMap].sort(([a],[b])=>a.localeCompare(b)).slice(-input.cohortMonths).map(([cohort,row])=>({cohort,size:row.customers.size,retention:[...row.activity].sort(([a],[b])=>a-b).map(([month,set])=>({month,customers:set.size,rate:row.customers.size?round(set.size*100/row.customers.size):0}))}));
 const segmentNames=["new","regular","loyal","vip","high_spender","at_risk","lost"];const segments=segmentNames.map(segment=>({segment,customers:insights.filter(x=>x.segmentKeys.includes(segment)).length,revenue:round(insights.filter(x=>x.segmentKeys.includes(segment)).reduce((s,x)=>s+x.lifetimeValue,0)),averageLtv:round(insights.filter(x=>x.segmentKeys.includes(segment)).reduce((s,x)=>s+x.lifetimeValue,0)/Math.max(1,insights.filter(x=>x.segmentKeys.includes(segment)).length))}));
 const reservationCustomers=new Set(reservations.map(x=>String(x.customerId)));const reviewCustomers=new Set(reviews.map(x=>String(x.customerId)));const funnels=[{name:"Customer lifecycle",steps:[{label:"Registered",value:users.length},{label:"Ordered",value:activeIds.size},{label:"Repeat customer",value:repeatIds.size},{label:"Reserved",value:reservationCustomers.size},{label:"Reviewed",value:reviewCustomers.size}]}];
 const campaignRows=campaigns.map(c=>{const rows=executions.filter(e=>String(e.campaignId)===String(c._id));const sent=rows.filter(e=>["sent","delivered","opened","clicked","converted"].includes(e.status)).length;const clicked=rows.filter(e=>["clicked","converted"].includes(e.status)).length;const converted=rows.filter(e=>e.status==="converted").length;return{id:String(c._id),name:c.name,channel:c.channel,audience:c.metrics?.audienceSize??0,sent,clicked,converted,ctr:sent?round(clicked*100/sent):0,conversionRate:sent?round(converted*100/sent):0,attributedRevenue:0,roi:null}});
 const metrics={periodDays:input.days,totalCustomers:customers,activeCustomers:activeIds.size,newCustomers:users.filter(u=>new Date(u.createdAt)>=since).length,repeatCustomers:repeatIds.size,repeatRate:activeIds.size?round(repeatIds.size*100/activeIds.size):0,retainedCustomers:retained,retentionRate:previousIds.size?round(retained*100/previousIds.size):0,churnedCustomers:churned,churnRate:previousIds.size?round(churned*100/previousIds.size):0,revenue:round(revenue),revenuePerCustomer:activeIds.size?round(revenue/activeIds.size):0,averageLtv:customers?round(ltvTotal/customers):0,totalLtv:round(ltvTotal),orders:current.length,discounts:round(discounts),marketingRoi:null,campaignConversions:executions.filter(e=>e.status==="converted").length};
 const snapshotDate=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));const snapshot=await CustomerAnalyticsSnapshot.findOneAndUpdate({snapshotDate,periodDays:input.days},{$set:{periodStart:since,periodEnd:now,metrics,growth,cohorts,segments,funnels,campaigns:campaignRows,generatedBy:input.source,generatedAt:now}},{upsert:true,returnDocument:"after",setDefaultsOnInsert:true});return snapshot;}
export async function getCustomerAnalytics(days=90,cohortMonths=12){const latest=await CustomerAnalyticsSnapshot.findOne({periodDays:days}).sort({generatedAt:-1}).lean();if(latest)return latest;return (await buildCustomerAnalytics({days,cohortMonths,source:"manual"})).toObject();}
export async function getCustomerAnalyticsHistory(limit=12){return CustomerAnalyticsSnapshot.find().sort({generatedAt:-1}).limit(limit).select("snapshotDate periodDays metrics generatedAt").lean();}
