import { Types } from "mongoose";
import { connectToDatabase } from "@/lib/db/mongoose";
import { FinanceJobRun } from "@/models/FinanceJobRun";
import { FinancePeriodClose } from "@/models/FinancePeriodClose";
import { ReceivableInvoice } from "@/models/ReceivableInvoice";
import { PayableBill } from "@/models/PayableBill";
import { buildRevenueSnapshot } from "@/services/revenue-management.service";
import { buildExpenseSnapshot } from "@/services/expense-management.service";
import { buildAccountsReceivableSnapshot } from "@/services/accounts-receivable.service";
import { buildAccountsPayableSnapshot } from "@/services/accounts-payable.service";
import { buildPaymentManagementSnapshot } from "@/services/payment-management.service";
import { buildFinancialReportSnapshot } from "@/services/financial-reports.service";
import { buildBudgetForecastSnapshot } from "@/services/budgeting-forecasting.service";
import { buildExecutiveFinanceSnapshot } from "@/services/executive-finance.service";
import { buildFinanceGovernanceSnapshot } from "@/services/finance-governance.service";

type JobType="nightly_reconciliation"|"overdue_refresh"|"snapshot_refresh"|"month_end_close"|"year_end_close";
type Source="manual"|"scheduled"|"system";
const round=(v:number)=>Math.round(v*100)/100;
function number(prefix:string){return `${prefix}-${new Date().toISOString().replace(/\D/g,"").slice(0,14)}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;}
async function overdueRefresh(){const now=new Date();const [receivables,payables]=await Promise.all([
  ReceivableInvoice.updateMany({dueDate:{$lt:now},outstandingAmount:{$gt:0},status:{$in:["issued","partially_paid"]}},{$set:{status:"overdue"}}),
  PayableBill.updateMany({dueDate:{$lt:now},outstandingAmount:{$gt:0},status:{$in:["approved","partially_paid"]}},{$set:{status:"overdue"}}),
]);return {receivables:receivables.modifiedCount,payables:payables.modifiedCount};}
async function snapshotRefresh(days:number,source:Source){const year=new Date().getUTCFullYear();await buildRevenueSnapshot({days,source});await buildExpenseSnapshot({days,source});await buildAccountsReceivableSnapshot({days,source});await buildAccountsPayableSnapshot({days,source});await buildPaymentManagementSnapshot({days,source});await buildFinancialReportSnapshot({days,source});await buildBudgetForecastSnapshot({fiscalYear:year,scenario:"base",department:"Company",source});await buildExecutiveFinanceSnapshot({days,fiscalYear:year,scenario:"base",source});await buildFinanceGovernanceSnapshot({days,source});}
export async function runFinanceJob(input:{jobType:JobType;days:number;source:Source;triggeredBy?:string|null;triggeredByName?:string}){await connectToDatabase();const startedAt=new Date();const run=await FinanceJobRun.create({runNumber:number("FJOB"),jobType:input.jobType,status:"running",source:input.source,startedAt,triggeredBy:input.triggeredBy??null,triggeredByName:input.triggeredByName??"System",steps:[]});const steps:Array<{name:string;fn:()=>Promise<unknown>}>=input.jobType==="overdue_refresh"?[{name:"Refresh overdue receivables and payables",fn:overdueRefresh}]:input.jobType==="nightly_reconciliation"?[{name:"Refresh overdue balances",fn:overdueRefresh},{name:"Rebuild finance snapshots",fn:()=>snapshotRefresh(input.days,input.source)}]:[{name:"Rebuild finance snapshots",fn:()=>snapshotRefresh(input.days,input.source)}];let failed=0;for(const step of steps){const index=run.steps.length;run.steps.push({name:step.name,status:"running",startedAt:new Date(),completedAt:null,message:""});await run.save();try{const result=await step.fn();run.steps[index].status="succeeded";run.steps[index].message=JSON.stringify(result??{});}catch(error){failed+=1;run.steps[index].status="failed";run.steps[index].message=error instanceof Error?error.message:"Unknown job error";}run.steps[index].completedAt=new Date();await run.save();}run.status=failed===0?"succeeded":failed===steps.length?"failed":"partially_failed";run.completedAt=new Date();run.durationMs=run.completedAt.getTime()-startedAt.getTime();run.errorMessage=failed?`${failed} step(s) failed.`:"";await run.save();return run.toObject();}
export async function closeFinancePeriod(input:{closeType:"month_end"|"year_end";fiscalYear:number;month?:number|null;notes?:string;closedBy?:string|null;closedByName?:string}){await connectToDatabase();const month=input.closeType==="month_end"?input.month??null:null;const periodKey=input.closeType==="month_end"?`${input.fiscalYear}-${String(month).padStart(2,"0")}`:`${input.fiscalYear}`;const existing=await FinancePeriodClose.findOne({periodKey});if(existing?.status==="closed")throw new Error(`Finance period ${periodKey} is already closed.`);const close=existing??await FinancePeriodClose.create({closeNumber:number("FCLOSE"),closeType:input.closeType,fiscalYear:input.fiscalYear,month,periodKey,status:"open",notes:input.notes??"",checklist:[{name:"Refresh overdue balances"},{name:"Rebuild operational snapshots"},{name:"Rebuild financial reports"},{name:"Rebuild executive dashboard"},{name:"Rebuild governance snapshot"}]});close.status="closing";close.lockedAt=new Date();await close.save();try{const closeJobType:JobType=input.closeType==="month_end"?"month_end_close":"year_end_close";const closedByObjectId=input.closedBy&&Types.ObjectId.isValid(input.closedBy)?new Types.ObjectId(input.closedBy):null;const job=await runFinanceJob({jobType:closeJobType,days:input.closeType==="month_end"?62:366,source:"system",triggeredBy:input.closedBy,triggeredByName:input.closedByName});close.jobRunId=job._id;close.checklist.forEach(item=>{item.completed=true;item.completedAt=new Date();});close.status="closed";close.closedAt=new Date();close.closedBy=closedByObjectId;close.closedByName=input.closedByName??"System";await close.save();return close.toObject();}catch(error){close.status="failed";await close.save();throw error;}}
export async function getFinanceJobsSummary(days:number){await connectToDatabase();const since=new Date(Date.now()-days*86400000);const [runs,closes]=await Promise.all([FinanceJobRun.find({createdAt:{$gte:since}}).sort({createdAt:-1}).limit(50).lean(),FinancePeriodClose.find().sort({createdAt:-1}).limit(24).lean()]);const succeeded=runs.filter(r=>r.status==="succeeded").length,failed=runs.filter(r=>r.status==="failed"||r.status==="partially_failed").length;return {metrics:{totalRuns:runs.length,succeeded,failed,running:runs.filter(r=>r.status==="running").length,successRate:runs.length?round(succeeded/runs.length*100):0,averageDurationSeconds:runs.length?round(runs.reduce((s,r)=>s+Number(r.durationMs??0),0)/runs.length/1000):0,closedPeriods:closes.filter(c=>c.status==="closed").length},recentRuns:runs,periodCloses:closes};}
