import { Types } from "mongoose";
import { connectToDatabase } from "@/lib/db/mongoose";
import { AppError } from "@/lib/errors/AppError";
import { FinanceApprovalRequest } from "@/models/FinanceApprovalRequest";
import { FinanceAuditEvent } from "@/models/FinanceAuditEvent";
import { FinanceGovernanceSnapshot } from "@/models/FinanceGovernanceSnapshot";
const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;
async function nextRequestNumber(){const date=new Date().toISOString().slice(0,10).replaceAll("-","");const base=`APR-${date}`;const count=await FinanceApprovalRequest.collection.countDocuments({requestNumber:{$regex:`^${base}-`}});return `${base}-${String(count+1).padStart(4,"0")}`;}
export async function recordFinanceAudit(input:{module:string;entityType:string;entityId:string;action:string;actorId?:string|null;actorName?:string;actorRole?:string;before?:unknown;after?:unknown;metadata?:Record<string,unknown>}){await connectToDatabase();return FinanceAuditEvent.create({...input,actorId:input.actorId?new Types.ObjectId(input.actorId):null});}
export async function createApprovalRequest(input:{module:string;entityType:string;entityId:string;action:string;title:string;description:string;amount:number;priority:"low"|"normal"|"high"|"critical";assignedRole:string;expiresAt?:Date|null;payload:Record<string,unknown>},user:{id:string;name:string}){await connectToDatabase();const request=await FinanceApprovalRequest.create({...input,requestNumber:await nextRequestNumber(),currency:"INR",requestedBy:new Types.ObjectId(user.id),requestedByName:user.name,history:[{action:"submitted",actorId:new Types.ObjectId(user.id),actorName:user.name,note:"Approval request submitted."}]});await recordFinanceAudit({module:input.module,entityType:"FinanceApprovalRequest",entityId:String(request._id),action:"approval.requested",actorId:user.id,actorName:user.name,after:{status:"pending",amount:input.amount,priority:input.priority}});return request.toObject();}
export async function decideApprovalRequest(id:string,input:{decision:"approve"|"reject"|"cancel";note:string},user:{id:string;name:string}){await connectToDatabase();const request=await FinanceApprovalRequest.findById(id);if(!request)throw new AppError("Approval request not found.",404);if(request.status!=="pending")throw new AppError("Only pending approval requests can be decided.",409);if(String(request.requestedBy)===user.id&&input.decision!=="cancel")throw new AppError("Maker-checker control prevents requesters from approving their own request.",409);const status=input.decision==="approve"?"approved":input.decision==="reject"?"rejected":"cancelled";request.status=status;request.decidedBy=new Types.ObjectId(user.id);request.decidedByName=user.name;request.decisionNote=input.note;request.decidedAt=new Date();request.history.push({action:status,actorId:new Types.ObjectId(user.id),actorName:user.name,note:input.note,occurredAt:new Date()});await request.save();await recordFinanceAudit({module:request.module,entityType:"FinanceApprovalRequest",entityId:String(request._id),action:`approval.${status}`,actorId:user.id,actorName:user.name,before:{status:"pending"},after:{status},metadata:{note:input.note}});return request.toObject();}
export async function listApprovalRequests(limit=50){await connectToDatabase();return FinanceApprovalRequest.find({}).sort({createdAt:-1}).limit(limit).lean();}
export async function buildFinanceGovernanceSnapshot(input:{days:number;source:"manual"|"scheduled"|"system"}){await connectToDatabase();const periodEnd=new Date();const periodStart=new Date(periodEnd);periodStart.setUTCDate(periodStart.getUTCDate()-input.days+1);periodStart.setUTCHours(0,0,0,0);periodEnd.setUTCHours(23,59,59,999);await FinanceApprovalRequest.updateMany({status:"pending",expiresAt:{$ne:null,$lt:new Date()}},{$set:{status:"expired"}});const [events,requests]=await Promise.all([FinanceAuditEvent.find({occurredAt:{$gte:periodStart,$lte:periodEnd}}).sort({occurredAt:-1}).lean(),FinanceApprovalRequest.find({createdAt:{$lte:periodEnd}}).sort({createdAt:-1}).lean()]);const pending=requests.filter(r=>r.status==="pending"),decided=requests.filter(r=>r.decidedAt);const avg=decided.length?decided.reduce((s,r)=>s+(new Date(r.decidedAt!).getTime()-new Date(r.createdAt).getTime())/36e5,0)/decided.length:0;const approved=requests.filter(r=>r.status==="approved").length,rejected=requests.filter(r=>r.status==="rejected").length;const modules=[...new Set([...events.map(e=>e.module),...requests.map(r=>r.module)])];const metrics={totalAuditEvents:events.length,pendingApprovals:pending.length,approvedRequests:approved,rejectedRequests:rejected,expiredRequests:requests.filter(r=>r.status==="expired").length,criticalPending:pending.filter(r=>r.priority==="critical").length,pendingValue:round(pending.reduce((s,r)=>s+Number(r.amount??0),0)),averageDecisionHours:round(avg),approvalRate:approved+rejected?round(approved/(approved+rejected)*100):0};const periodKey=`${periodStart.toISOString().slice(0,10)}_${periodEnd.toISOString().slice(0,10)}`;return FinanceGovernanceSnapshot.findOneAndUpdate({periodKey},{$set:{periodStart,periodEnd,metrics,byModule:modules.map(module=>({module,auditEvents:events.filter(e=>e.module===module).length,approvals:requests.filter(r=>r.module===module).length,pending:pending.filter(r=>r.module===module).length})),recentApprovals:requests.slice(0,20),recentAuditEvents:events.slice(0,30),generatedAt:new Date(),source:input.source}},{upsert:true,returnDocument:"after",runValidators:true}).lean();}
export async function getFinanceGovernanceSummary(days:number){await connectToDatabase();const periodEnd=new Date();const periodStart=new Date(periodEnd);periodStart.setUTCDate(periodStart.getUTCDate()-days+1);const periodKey=`${periodStart.toISOString().slice(0,10)}_${periodEnd.toISOString().slice(0,10)}`;return FinanceGovernanceSnapshot.findOne({periodKey}).lean()??buildFinanceGovernanceSnapshot({days,source:"system"});}
