import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { Types } from "mongoose";
import type { z } from "zod";
import { connectToDatabase } from "@/lib/db/mongoose";
import { AppError } from "@/lib/errors/AppError";
import { FinanceDocument } from "@/models/FinanceDocument";
import { FinanceReceipt } from "@/models/FinanceReceipt";
import { InvoiceReceiptSnapshot } from "@/models/InvoiceReceiptSnapshot";
import type { financeDocumentCreateSchema, financeDocumentUpdateSchema, receiptCreateSchema } from "@/validators/invoice-receipt";
const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;const dayKey=(d:Date)=>d.toISOString().slice(0,10);
export const getInvoiceReceiptRange=(days:number)=>{const end=new Date();const start=new Date(end);start.setUTCDate(start.getUTCDate()-Math.max(1,days)+1);start.setUTCHours(0,0,0,0);end.setUTCHours(23,59,59,999);return{start,end,days};};
async function nextNumber(model:{collection:{countDocuments(filter:Record<string,unknown>):Promise<number>}},prefix:string,field:"documentNumber"|"receiptNumber"){const date=new Date().toISOString().slice(0,10).replaceAll("-","");const base=`${prefix}-${date}`;const count=await model.collection.countDocuments({[field]:{$regex:`^${base}-`}});return`${base}-${String(count+1).padStart(4,"0")}`;}
function calculateLines(items:Array<{description:string;quantity:number;unitPrice:number;taxRate:number;discountAmount:number}>,roundingAmount:number){let subtotal=0,discountAmount=0,taxableAmount=0,taxAmount=0;const lineItems=items.map(item=>{const base=round(item.quantity*item.unitPrice);const discount=round(Math.min(base,item.discountAmount));const taxable=round(base-discount);const tax=round(taxable*item.taxRate/100);const total=round(taxable+tax);subtotal+=base;discountAmount+=discount;taxableAmount+=taxable;taxAmount+=tax;return{...item,discountAmount:discount,taxableAmount:taxable,taxAmount:tax,lineTotal:total};});const totalAmount=round(Math.max(0,taxableAmount+taxAmount+roundingAmount));return{lineItems,subtotal:round(subtotal),discountAmount:round(discountAmount),taxableAmount:round(taxableAmount),taxAmount:round(taxAmount),roundingAmount:round(roundingAmount),totalAmount};}
type FinanceDocumentStatus="draft"|"issued"|"partially_paid"|"paid"|"overdue"|"cancelled";function deriveStatus(input:{current:FinanceDocumentStatus;dueDate:Date;total:number;received:number}):FinanceDocumentStatus{if(["draft","cancelled"].includes(input.current))return input.current;if(input.received>=input.total)return"paid";if(input.received>0)return"partially_paid";return input.dueDate.getTime()<Date.now()?"overdue":"issued";}
export async function createFinanceDocument(input:z.infer<typeof financeDocumentCreateSchema>,actorId:string){await connectToDatabase();if(input.sourceId){const duplicate=await FinanceDocument.exists({sourceType:input.sourceType,sourceId:new Types.ObjectId(input.sourceId),documentType:input.documentType});if(duplicate)throw new AppError("A financial document already exists for this source.",409);}const actor=new Types.ObjectId(actorId);const totals=calculateLines(input.lineItems,input.roundingAmount);const prefix=input.documentType==="sales_invoice"?"INV":input.documentType==="credit_note"?"CN":"DN";const doc=new FinanceDocument({...input,sourceId:input.sourceId?new Types.ObjectId(input.sourceId):null,customerId:input.customerId?new Types.ObjectId(input.customerId):null,documentNumber:await nextNumber(FinanceDocument,prefix,"documentNumber"),...totals,receivedAmount:0,balanceAmount:totals.totalAmount,status:"draft",createdBy:actor,updatedBy:actor});await doc.save();return doc;}
export async function updateFinanceDocument(id:string,input:z.infer<typeof financeDocumentUpdateSchema>,actorId:string){await connectToDatabase();const doc=await FinanceDocument.findById(id);if(!doc)throw new AppError("Financial document not found.",404);if(doc.status!=="draft")throw new AppError("Only draft documents can be edited.",409);Object.assign(doc,input,{sourceId:input.sourceId===undefined?doc.sourceId:input.sourceId?new Types.ObjectId(input.sourceId):null,customerId:input.customerId===undefined?doc.customerId:input.customerId?new Types.ObjectId(input.customerId):null,updatedBy:new Types.ObjectId(actorId)});if(input.lineItems||input.roundingAmount!==undefined){const normalized=(input.lineItems??doc.lineItems).map(item=>({description:item.description,quantity:Number(item.quantity),unitPrice:Number(item.unitPrice),taxRate:Number(item.taxRate),discountAmount:Number(item.discountAmount)}));Object.assign(doc,calculateLines(normalized,input.roundingAmount??doc.roundingAmount));doc.balanceAmount=doc.totalAmount;}await doc.save();return doc;}
export async function issueFinanceDocument(id:string,actorId:string){await connectToDatabase();const doc=await FinanceDocument.findById(id);if(!doc)throw new AppError("Financial document not found.",404);if(doc.status!=="draft")throw new AppError("Only draft documents can be issued.",409);doc.status=deriveStatus({current:"issued",dueDate:doc.dueDate,total:doc.totalAmount,received:doc.receivedAmount});doc.issuedAt=new Date();doc.issuedBy=new Types.ObjectId(actorId);doc.updatedBy=new Types.ObjectId(actorId);await doc.save();return doc;}
export async function cancelFinanceDocument(id:string,reason:string,actorId:string){await connectToDatabase();const doc=await FinanceDocument.findById(id);if(!doc)throw new AppError("Financial document not found.",404);if(doc.receivedAmount>0)throw new AppError("A document with recorded receipts cannot be cancelled.",409);if(doc.status==="cancelled")throw new AppError("Document is already cancelled.",409);doc.status="cancelled";doc.cancelledAt=new Date();doc.cancelledBy=new Types.ObjectId(actorId);doc.cancellationReason=reason;doc.updatedBy=new Types.ObjectId(actorId);await doc.save();return doc;}
export async function createReceipt(documentId:string,input:z.infer<typeof receiptCreateSchema>,actorId:string){await connectToDatabase();const doc=await FinanceDocument.findById(documentId);if(!doc)throw new AppError("Financial document not found.",404);if(!["issued","partially_paid","overdue"].includes(doc.status))throw new AppError("Receipt can only be recorded against an open issued document.",409);if(input.amount>doc.balanceAmount)throw new AppError("Receipt amount exceeds the outstanding balance.",400);const receipt=new FinanceReceipt({...input,receiptNumber:await nextNumber(FinanceReceipt,"RCT","receiptNumber"),documentId:doc._id,customerId:doc.customerId,partyName:doc.partyName,currency:doc.currency,recordedBy:new Types.ObjectId(actorId)});await receipt.save();doc.receivedAmount=round(doc.receivedAmount+input.amount);doc.balanceAmount=round(Math.max(0,doc.totalAmount-doc.receivedAmount));doc.status=deriveStatus({current:"issued",dueDate:doc.dueDate,total:doc.totalAmount,received:doc.receivedAmount});doc.updatedBy=new Types.ObjectId(actorId);await doc.save();return{document:doc,receipt};}
type Break={count:number;amount:number};function add(map:Map<string,Break>,key:string,amount:number){const row=map.get(key)??{count:0,amount:0};row.count++;row.amount+=amount;map.set(key,row);}function finish(map:Map<string,Break>){return[...map.entries()].map(([key,v])=>({key,count:v.count,amount:round(v.amount)}));}
export async function buildInvoiceReceiptSnapshot(input:{days:number;source:"manual"|"scheduled"|"system";generatedBy?:string|null}){await connectToDatabase();const range=getInvoiceReceiptRange(input.days);const[documents,receipts]=await Promise.all([FinanceDocument.find({issueDate:{$gte:range.start,$lte:range.end},status:{$ne:"cancelled"}}).lean(),FinanceReceipt.find({receiptDate:{$gte:range.start,$lte:range.end},status:"active"}).lean()]);const byStatus=new Map<string,Break>(),byDocumentType=new Map<string,Break>(),byPaymentMethod=new Map<string,Break>();let issuedCount=0,paidCount=0,overdueCount=0,invoicedAmount=0,receivedAmount=0,balanceAmount=0,taxAmount=0,receiptAmount=0;for(const doc of documents){if(doc.status!=="draft")issuedCount++;if(doc.status==="paid")paidCount++;if(doc.status==="overdue")overdueCount++;invoicedAmount+=Number(doc.totalAmount);receivedAmount+=Number(doc.receivedAmount);balanceAmount+=Number(doc.balanceAmount);taxAmount+=Number(doc.taxAmount);add(byStatus,doc.status,Number(doc.totalAmount));add(byDocumentType,doc.documentType,Number(doc.totalAmount));}for(const receipt of receipts){receiptAmount+=Number(receipt.amount);add(byPaymentMethod,receipt.paymentMethod,Number(receipt.amount));}const metrics={documentCount:documents.length,issuedCount,paidCount,overdueCount,invoicedAmount:round(invoicedAmount),receivedAmount:round(receivedAmount),balanceAmount:round(balanceAmount),taxAmount:round(taxAmount),receiptCount:receipts.length,receiptAmount:round(receiptAmount),collectionRate:invoicedAmount?round(receivedAmount/invoicedAmount*100):0};const periodKey=`${dayKey(range.start)}_${dayKey(range.end)}`;return InvoiceReceiptSnapshot.findOneAndUpdate({periodKey},{$set:{periodStart:range.start,periodEnd:range.end,currency:"INR",metrics,byStatus:finish(byStatus),byDocumentType:finish(byDocumentType),byPaymentMethod:finish(byPaymentMethod),generatedAt:new Date(),generatedBy:input.generatedBy?new Types.ObjectId(input.generatedBy):null,source:input.source}},{upsert:true,returnDocument:"after",runValidators:true}).lean();}
export async function getInvoiceReceiptSummary(days:number){await connectToDatabase();const range=getInvoiceReceiptRange(days);const periodKey=`${dayKey(range.start)}_${dayKey(range.end)}`;const[snapshot,recentDocuments,recentReceipts]=await Promise.all([InvoiceReceiptSnapshot.findOne({periodKey}).lean(),FinanceDocument.find({issueDate:{$gte:range.start,$lte:range.end}}).sort({issueDate:-1}).limit(25).lean(),FinanceReceipt.find({receiptDate:{$gte:range.start,$lte:range.end}}).sort({receiptDate:-1}).limit(25).lean()]);return{snapshot:snapshot??await buildInvoiceReceiptSnapshot({days,source:"system"}),recentDocuments,recentReceipts};}
const money=(v:number,currency:string)=>`${currency} ${v.toFixed(2)}`;
export async function generateFinanceDocumentPdf(id:string){await connectToDatabase();const doc=await FinanceDocument.findById(id).lean();if(!doc)throw new AppError("Financial document not found.",404);const pdf=await PDFDocument.create();const page=pdf.addPage([595.28,841.89]);const font=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);let y=790;page.drawText("THE ROLLING STOVE",{x:48,y,size:18,font:bold,color:rgb(0.1,0.1,0.1)});page.drawText(doc.documentType.replaceAll("_"," ").toUpperCase(),{x:430,y,size:11,font:bold});y-=34;page.drawText(`Document: ${doc.documentNumber}`,{x:48,y,size:10,font});page.drawText(`Issue date: ${new Date(doc.issueDate).toLocaleDateString("en-IN")}`,{x:340,y,size:10,font});y-=18;page.drawText(`Party: ${doc.partyName}`,{x:48,y,size:10,font});page.drawText(`Due date: ${new Date(doc.dueDate).toLocaleDateString("en-IN")}`,{x:340,y,size:10,font});y-=30;page.drawText("Description",{x:48,y,size:9,font:bold});page.drawText("Qty",{x:330,y,size:9,font:bold});page.drawText("Rate",{x:380,y,size:9,font:bold});page.drawText("Tax",{x:450,y,size:9,font:bold});page.drawText("Total",{x:500,y,size:9,font:bold});y-=16;for(const item of doc.lineItems.slice(0,22)){page.drawText(item.description.slice(0,44),{x:48,y,size:8,font});page.drawText(String(item.quantity),{x:330,y,size:8,font});page.drawText(Number(item.unitPrice).toFixed(2),{x:380,y,size:8,font});page.drawText(Number(item.taxAmount).toFixed(2),{x:450,y,size:8,font});page.drawText(Number(item.lineTotal).toFixed(2),{x:500,y,size:8,font});y-=15;}y-=18;page.drawText(`Subtotal: ${money(Number(doc.subtotal),doc.currency)}`,{x:350,y,size:10,font});y-=16;page.drawText(`Discount: ${money(Number(doc.discountAmount),doc.currency)}`,{x:350,y,size:10,font});y-=16;page.drawText(`Tax: ${money(Number(doc.taxAmount),doc.currency)}`,{x:350,y,size:10,font});y-=18;page.drawText(`Total: ${money(Number(doc.totalAmount),doc.currency)}`,{x:350,y,size:12,font:bold});y-=18;page.drawText(`Received: ${money(Number(doc.receivedAmount),doc.currency)}`,{x:350,y,size:10,font});y-=16;page.drawText(`Balance: ${money(Number(doc.balanceAmount),doc.currency)}`,{x:350,y,size:10,font:bold});page.drawText("Generated by TRS Financial Management",{x:48,y:42,size:8,font,color:rgb(0.4,0.4,0.4)});return{bytes:await pdf.save(),filename:`${doc.documentNumber}.pdf`};}
