import { randomBytes } from "node:crypto";
import { Types } from "mongoose";
import { AppError } from "@/lib/errors/AppError";
import { CoinTransaction } from "@/models/CoinTransaction";
import { CoinWallet } from "@/models/CoinWallet";
import { LoyaltyMembership } from "@/models/LoyaltyMembership";
import { LoyaltyMilestone } from "@/models/LoyaltyMilestone";
import { LoyaltyMilestoneProgress } from "@/models/LoyaltyMilestoneProgress";
import { LoyaltyPointLot } from "@/models/LoyaltyPointLot";
import { LoyaltyTier } from "@/models/LoyaltyTier";
import { Order } from "@/models/Order";
import { RewardCatalogItem } from "@/models/RewardCatalogItem";
import { RewardRedemption } from "@/models/RewardRedemption";
import { Role } from "@/models/Role";
import { User } from "@/models/User";
import { getOrCreateWallet, adjustCoins } from "@/services/rewards.service";
const KEYS=["bronze","silver","gold","platinum"] as const;
type LoyaltyTierKey=(typeof KEYS)[number];
type DefaultLoyaltyTier={key:LoyaltyTierKey;name:string;rank:number;minimumLifetimeSpend:number;minimumAnnualSpend:number;minimumAnnualOrders:number;pointsMultiplier:number;birthdayBonusCoins:number;benefits:string[];colorHex:string};
export async function seedDefaultLoyaltyConfiguration(){const defaults:DefaultLoyaltyTier[]=[
 {key:"bronze",name:"Bronze",rank:1,minimumLifetimeSpend:0,minimumAnnualSpend:0,minimumAnnualOrders:0,pointsMultiplier:1,birthdayBonusCoins:25,benefits:["Base earn rate","Member-only offers"],colorHex:"#A97142"},
 {key:"silver",name:"Silver",rank:2,minimumLifetimeSpend:5000,minimumAnnualSpend:3000,minimumAnnualOrders:8,pointsMultiplier:1.25,birthdayBonusCoins:50,benefits:["1.25x coins","Priority offers"],colorHex:"#8E9AAF"},
 {key:"gold",name:"Gold",rank:3,minimumLifetimeSpend:15000,minimumAnnualSpend:10000,minimumAnnualOrders:20,pointsMultiplier:1.5,birthdayBonusCoins:100,benefits:["1.5x coins","Early reward access","Birthday bonus"],colorHex:"#D4A017"},
 {key:"platinum",name:"Platinum",rank:4,minimumLifetimeSpend:40000,minimumAnnualSpend:25000,minimumAnnualOrders:40,pointsMultiplier:2,birthdayBonusCoins:200,benefits:["2x coins","Exclusive catalog","Priority support"],colorHex:"#5B6073"},
 ];for(const item of defaults){const existing=await LoyaltyTier.findOne({key:item.key}).select("_id").lean();if(!existing)await LoyaltyTier.create({...item,isActive:true});}return LoyaltyTier.find().sort({rank:1}).lean();}
export async function getOrCreateMembership(customerId:string){let m=await LoyaltyMembership.findOne({customerId});if(!m)m=await LoyaltyMembership.create({customerId,qualificationYear:new Date().getUTCFullYear()});return m;}
export async function evaluateCustomerTier(customerId:string){await seedDefaultLoyaltyConfiguration();const year=new Date().getUTCFullYear();const start=new Date(Date.UTC(year,0,1));const [lifetime,annual]=await Promise.all([Order.aggregate([{$match:{customerId:new Types.ObjectId(customerId),status:"completed"}},{$group:{_id:null,spend:{$sum:"$grandTotal"},orders:{$sum:1}}}]),Order.aggregate([{$match:{customerId:new Types.ObjectId(customerId),status:"completed",createdAt:{$gte:start}}},{$group:{_id:null,spend:{$sum:"$grandTotal"},orders:{$sum:1}}}])]);const ls=lifetime[0]?.spend??0,as=annual[0]?.spend??0,ao=annual[0]?.orders??0;const tiers=await LoyaltyTier.find({isActive:true}).sort({rank:-1}).lean();const selected=tiers.find(t=>ls>=t.minimumLifetimeSpend&&(as>=t.minimumAnnualSpend||ao>=t.minimumAnnualOrders))??tiers.at(-1);if(!selected)throw new AppError("No active loyalty tier is configured.",500);const m=await getOrCreateMembership(customerId);const old=m.tierKey;const oldRank=KEYS.indexOf(old as typeof KEYS[number]);const newRank=KEYS.indexOf(selected.key as typeof KEYS[number]);m.tierKey=selected.key;m.lifetimeSpend=ls;m.annualSpend=as;m.annualOrders=ao;m.qualificationYear=year;m.lastEvaluatedAt=new Date();m.nextReviewAt=new Date(Date.UTC(year+1,0,1));if(old!==selected.key){m.lastTierChangeAt=new Date();if(newRank>oldRank)m.upgradeCount+=1;else m.downgradeCount+=1;if(newRank>KEYS.indexOf(m.highestTierKey as typeof KEYS[number]))m.highestTierKey=selected.key;}await m.save();await updateMilestones(customerId,m);return {membership:m,tier:selected,previousTierKey:old,changed:old!==selected.key};}
async function updateMilestones(customerId:string,m:{lifetimeSpend:number;annualSpend:number;annualOrders:number}){const wallet=await getOrCreateWallet(customerId);const milestones=await LoyaltyMilestone.find({isActive:true}).lean();for(const x of milestones){const value=x.metric==="lifetime_spend"?m.lifetimeSpend:x.metric==="annual_spend"?m.annualSpend:x.metric==="annual_orders"?m.annualOrders:x.metric==="lifetime_earned"?wallet.lifetimeEarned:0;const progress=await LoyaltyMilestoneProgress.findOneAndUpdate({customerId,milestoneId:x._id},{$set:{currentValue:value}},{upsert:true,new:true});if(value>=x.threshold&&!progress.completedAt){progress.completedAt=new Date();if(x.rewardCoins>0){const result=await adjustCoins({customerId,amount:x.rewardCoins,description:`Milestone reward: ${x.name}`,actorId:customerId});progress.rewardTransactionId=result.transaction._id;}await progress.save();}}}
export async function getCustomerLoyaltyDashboard(customerId:string){const evaluated=await evaluateCustomerTier(customerId);const wallet=await getOrCreateWallet(customerId);const now=new Date(),soon=new Date(Date.now()+30*86400000);const [tiers,catalog,transactions,redemptions,milestones,expiring]=await Promise.all([LoyaltyTier.find({isActive:true}).sort({rank:1}).lean(),RewardCatalogItem.find({isActive:true,$and:[{$or:[{startsAt:null},{startsAt:{$lte:now}}]},{$or:[{expiresAt:null},{expiresAt:{$gte:now}}]}]}).sort({coinCost:1}).lean(),CoinTransaction.find({customerId}).sort({createdAt:-1}).limit(30).lean(),RewardRedemption.find({customerId}).sort({createdAt:-1}).limit(20).lean(),LoyaltyMilestoneProgress.find({customerId}).populate("milestoneId").lean(),LoyaltyPointLot.aggregate([{$match:{customerId:new Types.ObjectId(customerId),status:"active",expiresAt:{$lte:soon}}},{$group:{_id:null,total:{$sum:"$remainingAmount"},nextExpiry:{$min:"$expiresAt"}}}])]);return {...evaluated,wallet,tiers,catalog:catalog.filter(x=>x.eligibleTierKeys.includes(evaluated.membership.tierKey)),transactions,redemptions,milestones,expiringSoon:{coins:expiring[0]?.total??0,nextExpiry:expiring[0]?.nextExpiry??null}};}
export async function redeemCatalogReward(customerId:string,rewardId:string){const reward=await RewardCatalogItem.findById(rewardId);if(!reward||!reward.isActive)throw new AppError("Reward is unavailable.",404);const {membership}=await evaluateCustomerTier(customerId);if(!reward.eligibleTierKeys.includes(membership.tierKey))throw new AppError("Your current tier is not eligible for this reward.",403);if(reward.inventoryLimit!=null&&reward.redeemedCount>=reward.inventoryLimit)throw new AppError("Reward inventory is exhausted.",400);const wallet=await getOrCreateWallet(customerId);if(wallet.balance<reward.coinCost)throw new AppError("Insufficient TRS Coins.",400);const result=await adjustCoins({customerId,amount:-reward.coinCost,description:`Redeemed catalog reward: ${reward.name}`,actorId:customerId});const redemption=await RewardRedemption.create({customerId,rewardId:reward._id,transactionId:result.transaction._id,code:`TRS-${randomBytes(5).toString("hex").toUpperCase()}`,coinsSpent:reward.coinCost,rewardSnapshot:{name:reward.name,rewardType:reward.rewardType,rewardValue:reward.rewardValue,minimumOrderAmount:reward.minimumOrderAmount,menuItemId:reward.menuItemId},expiresAt:reward.expiresAt??new Date(Date.now()+30*86400000)});reward.redeemedCount+=1;await reward.save();return {redemption,wallet:result.wallet};}
export async function expireLoyaltyCoins(limit=5000){const now=new Date();const lots=await LoyaltyPointLot.find({status:"active",expiresAt:{$lte:now},remainingAmount:{$gt:0}}).limit(limit);let expired=0;for(const lot of lots){const wallet=await getOrCreateWallet(String(lot.customerId));const amount=Math.min(lot.remainingAmount,wallet.balance);if(amount>0){wallet.balance-=amount;wallet.lastActivityAt=now;await wallet.save();await CoinTransaction.create({customerId:lot.customerId,walletId:wallet._id,type:"expire",amount:-amount,balanceAfter:wallet.balance,description:`Expired ${amount} TRS Coins.`,expiresAt:lot.expiresAt});expired+=amount;}lot.remainingAmount=0;lot.status="expired";await lot.save();}return {lotsProcessed:lots.length,coinsExpired:expired};}
export async function getLoyaltyAdminSummary(){await seedDefaultLoyaltyConfiguration();const now=new Date();const [tiers,members,wallets,catalog,redemptions,expiring]=await Promise.all([LoyaltyTier.find().sort({rank:1}).lean(),LoyaltyMembership.aggregate([{$group:{_id:"$tierKey",customers:{$sum:1},annualSpend:{$sum:"$annualSpend"}}}]),CoinWallet.aggregate([{$group:{_id:null,balance:{$sum:"$balance"},earned:{$sum:"$lifetimeEarned"},redeemed:{$sum:"$lifetimeRedeemed"}}}]),RewardCatalogItem.find().sort({createdAt:-1}).lean(),RewardRedemption.aggregate([{$group:{_id:"$status",count:{$sum:1},coins:{$sum:"$coinsSpent"}}}]),LoyaltyPointLot.aggregate([{$match:{status:"active",expiresAt:{$lte:new Date(now.getTime()+30*86400000)}}},{$group:{_id:null,coins:{$sum:"$remainingAmount"}}}])]);return {tiers,members,wallet:wallets[0]??{balance:0,earned:0,redeemed:0},catalog,redemptions,expiringCoins:expiring[0]?.coins??0};}
export async function rebuildAllLoyaltyMemberships(limit=10000){const role=await Role.findOne({key:"customer"}).select("_id").lean();if(!role)throw new AppError("Customer role is not configured.",500);const users=await User.find({roleId:role._id,isActive:true}).select("_id").limit(limit).lean();let changed=0;for(const u of users){const r=await evaluateCustomerTier(String(u._id));if(r.changed)changed++;}return {processed:users.length,tierChanges:changed};}
