import { Types } from "mongoose";
import { AppError } from "@/lib/errors/AppError";
import { verifyPassword } from "@/lib/auth/password";
import { Order } from "@/models/Order";
import { StaffProfile } from "@/models/StaffProfile";
import { User } from "@/models/User";
import { getRoleWithPermissions } from "@/services/rbac.service";

type InternalConsumptionInput={saleType:"customer"|"staff_meal"|"family_meal"|"complimentary"|"food_wastage"|"kitchen_test";referenceId:string|null;personName:string;reason:string;notes:string;managerApprovalEmail:string;managerApprovalPassword:string;managerApprovalReason:string};
export type InternalConsumptionApproval={isInternalOrder:boolean;approvalStatus:"not_required"|"required"|"approved";approvalReason:string;approvedBy:Types.ObjectId|null;approvedAt:Date|null;dailyUsageBefore:number;monthlyUsageBefore:number;dailyLimit:number;monthlyLimit:number};

export async function validatePosInternalConsumption(input:InternalConsumptionInput):Promise<InternalConsumptionApproval>{const isInternalOrder=input.saleType!=="customer";if(isInternalOrder&&!input.personName.trim())throw new AppError("Select or enter the person/name for this internal order.",422);if(isInternalOrder&&!input.reason.trim())throw new AppError("Reason is required for internal consumption.",422);let approvalStatus:InternalConsumptionApproval["approvalStatus"]="not_required",approvalReason="";let approvedBy:Types.ObjectId|null=null,approvedAt:Date|null=null,dailyUsageBefore=0,monthlyUsageBefore=0,dailyLimit=0,monthlyLimit=0;
if(input.saleType==="staff_meal"){if(!input.referenceId)throw new AppError("Select a staff member.",422);const staffUser=await User.findOne({_id:input.referenceId,deletedAt:null,isActive:true}).select("_id name").lean();if(!staffUser)throw new AppError("Selected staff member is no longer active.",409);if(staffUser.name!==input.personName.trim())input.personName=staffUser.name;const profile=await StaffProfile.findOne({userId:staffUser._id}).lean();if(!profile||profile.mealEligible===false)throw new AppError("This staff member is not eligible for staff meals.",409);if(profile.mealSuspendedUntil&&new Date(profile.mealSuspendedUntil)>new Date())throw new AppError(`Staff meal access is suspended until ${new Date(profile.mealSuspendedUntil).toLocaleDateString("en-IN")}. ${profile.mealSuspensionReason||""}`.trim(),409);
dailyLimit=profile.dailyMealLimit??2;monthlyLimit=profile.monthlyMealLimit??60;const weeklyLimit=profile.weeklyMealLimit??14,yearlyLimit=profile.yearlyMealLimit??720,now=new Date(),dayStart=new Date(now),weekStart=new Date(now);dayStart.setHours(0,0,0,0);weekStart.setDate(now.getDate()-((now.getDay()+6)%7));weekStart.setHours(0,0,0,0);const monthStart=new Date(now.getFullYear(),now.getMonth(),1),yearStart=new Date(now.getFullYear(),0,1);const[dailyCount,weeklyCount,monthlyCount,yearlyCount]=await Promise.all([dayStart,weekStart,monthStart,yearStart].map(start=>Order.countDocuments({saleType:"staff_meal","internalConsumption.referenceId":staffUser._id,status:{$nin:["cancelled","rejected"]},createdAt:{$gte:start}})));dailyUsageBefore=dailyCount;monthlyUsageBefore=monthlyCount;const limitExceeded=profile.unlimitedMeals!==true&&(dailyCount>=dailyLimit||weeklyCount>=weeklyLimit||monthlyCount>=monthlyLimit||yearlyCount>=yearlyLimit);
if(limitExceeded&&profile.requireManagerApprovalOnLimit!==false){approvalStatus="required";const email=input.managerApprovalEmail.trim().toLowerCase(),password=input.managerApprovalPassword;if(!email||!password||input.managerApprovalReason.trim().length<3)throw new AppError(`Manager approval is required. Daily ${dailyCount}/${dailyLimit}; weekly ${weeklyCount}/${weeklyLimit}; monthly ${monthlyCount}/${monthlyLimit}; yearly ${yearlyCount}/${yearlyLimit}.`,409,{code:"INTERNAL_MEAL_APPROVAL_REQUIRED"});const manager=await User.findOne({email,isActive:true,deletedAt:null}).select("+passwordHash name roleId");if(!manager||!(await verifyPassword(password,manager.passwordHash)))throw new AppError("Manager approval credentials are invalid.",403);const role=await getRoleWithPermissions(String(manager.roleId));const canApprove=role?.permissionIds.some(permission=>["settings.manage","orders.update","pos.manage"].includes(permission.key));if(!canApprove)throw new AppError("This account does not have permission to approve meal-limit overrides.",403);approvalStatus="approved";approvalReason=input.managerApprovalReason.trim();approvedBy=manager._id;approvedAt=new Date()}}
return{isInternalOrder,approvalStatus,approvalReason,approvedBy,approvedAt,dailyUsageBefore,monthlyUsageBefore,dailyLimit,monthlyLimit}}
