import { Types } from "mongoose";
import { CustomerRecommendationCache } from "@/models/CustomerRecommendationCache";
import { MenuItem } from "@/models/MenuItem";
import { Order } from "@/models/Order";
import { RecommendationAffinity } from "@/models/RecommendationAffinity";
import { RecommendationEvent } from "@/models/RecommendationEvent";
import { RecommendationRule } from "@/models/RecommendationRule";
import { RecommendationTrend } from "@/models/RecommendationTrend";
import { User } from "@/models/User";
import { getCustomerRoleId } from "@/services/userManagement.service";

type OrderRow={_id:Types.ObjectId;customerId:Types.ObjectId|null;createdAt:Date;grandTotal:number;items:Array<{menuItemId?:Types.ObjectId|null;quantity:number;lineTotal:number}>};
type MenuRow={_id:Types.ObjectId;name:string;slug:string;imageUrl:string;basePrice:number;categoryId:Types.ObjectId;tags:string[];isBestseller:boolean;isFeatured:boolean;preparationTimeMinutes:number};
type Scored={menuItemId:Types.ObjectId;score:number;reasonCodes:string[];explanation:string};
const round=(value:number,digits=4)=>Number(value.toFixed(digits));
const validItemIds=(order:OrderRow)=>[...new Set(order.items.map(item=>item.menuItemId?String(item.menuItemId):"").filter(Boolean))];

export async function rebuildRecommendationIntelligence(input:{lookbackDays:number;customerLimit:number}){
 const since=new Date(Date.now()-input.lookbackDays*86400000);
 const orders=await Order.find({status:"completed",createdAt:{$gte:since}}).select("_id customerId createdAt grandTotal items.menuItemId items.quantity items.lineTotal").lean() as unknown as OrderRow[];
 const itemOrderCounts=new Map<string,number>();const pairCounts=new Map<string,number>();const itemStats=new Map<string,{orders:Set<string>;quantity:number;revenue:number;customers:Set<string>;recent24:number;recent7:number;recent30:number}>();
 const now=Date.now();
 for(const order of orders){const ids=validItemIds(order);for(const id of ids)itemOrderCounts.set(id,(itemOrderCounts.get(id)??0)+1);for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){pairCounts.set(`${ids[i]}:${ids[j]}`,(pairCounts.get(`${ids[i]}:${ids[j]}`)??0)+1);pairCounts.set(`${ids[j]}:${ids[i]}`,(pairCounts.get(`${ids[j]}:${ids[i]}`)??0)+1);}for(const item of order.items){if(!item.menuItemId)continue;const id=String(item.menuItemId);const current=itemStats.get(id)??{orders:new Set<string>(),quantity:0,revenue:0,customers:new Set<string>(),recent24:0,recent7:0,recent30:0};current.orders.add(String(order._id));current.quantity+=item.quantity;current.revenue+=item.lineTotal;if(order.customerId)current.customers.add(String(order.customerId));const age=now-new Date(order.createdAt).getTime();if(age<=86400000)current.recent24+=item.quantity;if(age<=7*86400000)current.recent7+=item.quantity;if(age<=30*86400000)current.recent30+=item.quantity;itemStats.set(id,current);}}
 const affinityOps:Parameters<typeof RecommendationAffinity.bulkWrite>[0]=[];for(const [key,count] of pairCounts){const[source,target]=key.split(":");const sourceOrders=itemOrderCounts.get(source)??1;const targetOrders=itemOrderCounts.get(target)??1;const confidence=count/sourceOrders;const lift=orders.length?confidence/(targetOrders/orders.length):0;affinityOps.push({updateOne:{filter:{sourceItemId:new Types.ObjectId(source),targetItemId:new Types.ObjectId(target),relationType:"frequently_bought_together"},update:{$set:{coPurchaseCount:count,sourceOrderCount:sourceOrders,confidence:round(confidence),lift:round(lift),score:round(count*0.5+confidence*40+Math.min(lift,5)*8),generatedAt:new Date()}},upsert:true}});}
 if(affinityOps.length)await RecommendationAffinity.bulkWrite(affinityOps);
 const windows=[{key:"24h",days:1},{key:"7d",days:7},{key:"30d",days:30},{key:"all_time",days:input.lookbackDays}] as const;const trendOps:Parameters<typeof RecommendationTrend.bulkWrite>[0]=[];for(const[id,stats]of itemStats){for(const window of windows){const quantity=window.key==="24h"?stats.recent24:window.key==="7d"?stats.recent7:window.key==="30d"?stats.recent30:stats.quantity;const velocity=quantity/Math.max(1,window.days);trendOps.push({updateOne:{filter:{menuItemId:new Types.ObjectId(id),windowKey:window.key},update:{$set:{orders:stats.orders.size,quantity,revenue:round(stats.revenue),uniqueCustomers:stats.customers.size,velocity:round(velocity),score:round(velocity*20+stats.customers.size*2+stats.revenue/1000),generatedAt:new Date()}},upsert:true}});}}
 if(trendOps.length)await RecommendationTrend.bulkWrite(trendOps);
 const roleId=await getCustomerRoleId();const customers=await User.find({roleId}).select("_id").limit(input.customerLimit).lean();let caches=0;for(const customer of customers){await rebuildCustomerRecommendationCache(String(customer._id));caches++;}
 return{ordersAnalyzed:orders.length,affinities:affinityOps.length,trends:trendOps.length,customerCaches:caches,generatedAt:new Date()};
}

async function activeRules(){const now=new Date();return RecommendationRule.find({isActive:true,$and:[{$or:[{startsAt:null},{startsAt:{$lte:now}}]},{$or:[{endsAt:null},{endsAt:{$gte:now}}]}]}).lean();}
function ruleBoost(item:MenuRow,rules:Awaited<ReturnType<typeof activeRules>>,hour:number){let boost=0;const reasons:string[]=[];for(const rule of rules){const inTime=rule.startHour==null||rule.endHour==null||(rule.startHour<=rule.endHour?hour>=rule.startHour&&hour<=rule.endHour:hour>=rule.startHour||hour<=rule.endHour);if(!inTime)continue;const matches=rule.ruleType==="item_boost"&&rule.menuItemIds.some(id=>String(id)===String(item._id))||rule.ruleType==="category_boost"&&rule.categoryIds.some(id=>String(id)===String(item.categoryId))||rule.ruleType==="tag_boost"&&rule.tags.some(tag=>item.tags.includes(tag))||["time_window","seasonal"].includes(rule.ruleType)&&(rule.menuItemIds.length===0||rule.menuItemIds.some(id=>String(id)===String(item._id)));if(matches){boost+=rule.weight;reasons.push(rule.ruleType);}}return{boost,reasons};}

export async function rebuildCustomerRecommendationCache(customerId:string){
 const [history,menu,trends,rules]=await Promise.all([Order.find({customerId,status:"completed"}).select("items.menuItemId items.quantity createdAt").sort({createdAt:-1}).limit(100).lean(),MenuItem.find({isActive:true,isAvailable:true,deletedAt:null}).select("name slug imageUrl basePrice categoryId tags isBestseller isFeatured preparationTimeMinutes").lean() as unknown as Promise<MenuRow[]>,RecommendationTrend.find({windowKey:"30d"}).lean(),activeRules()]);
 const purchased=new Map<string,number>();const categoryWeights=new Map<string,number>();for(const order of history)for(const item of order.items){if(!item.menuItemId)continue;const id=String(item.menuItemId);purchased.set(id,(purchased.get(id)??0)+item.quantity);const found=menu.find(m=>String(m._id)===id);if(found)categoryWeights.set(String(found.categoryId),(categoryWeights.get(String(found.categoryId))??0)+item.quantity);}
 const trendMap=new Map(trends.map(t=>[String(t.menuItemId),t.score]));const hour=new Date().getHours();const rows:Scored[]=menu.map(item=>{const prior=purchased.get(String(item._id))??0;const category=categoryWeights.get(String(item.categoryId))??0;const trend=trendMap.get(String(item._id))??0;const business=ruleBoost(item,rules,hour);let score=Math.min(40,trend)+Math.min(25,category*3)+Math.min(15,prior*2)+(item.isBestseller?8:0)+(item.isFeatured?5:0)+business.boost;const reasons:string[]=[];if(prior)reasons.push("previously_ordered");if(category)reasons.push("preferred_category");if(trend>0)reasons.push("trending");if(item.isBestseller)reasons.push("bestseller");reasons.push(...business.reasons);if(!history.length)score+=item.isBestseller?15:0;return{menuItemId:item._id,score:Math.max(0,round(score)),reasonCodes:[...new Set(reasons)],explanation:prior?"Based on your order history and current popularity.":category?"Popular in categories you frequently order.":"Trending with TRS customers right now."};}).sort((a,b)=>b.score-a.score).slice(0,30);
 return CustomerRecommendationCache.findOneAndUpdate({customerId},{$set:{items:rows,contextVersion:"v1",generatedAt:new Date(),expiresAt:new Date(Date.now()+6*3600000)}},{upsert:true,new:true,setDefaultsOnInsert:true});
}

async function hydrate(rows:Array<{menuItemId:unknown;score:number;reasonCodes?:string[];explanation?:string}>,limit:number){const ids=rows.slice(0,limit).map(row=>row.menuItemId);const items=await MenuItem.find({_id:{$in:ids},isActive:true,isAvailable:true,deletedAt:null}).select("name slug imageUrl basePrice categoryId tags isBestseller preparationTimeMinutes").lean();const map=new Map(items.map(item=>[String(item._id),item]));return rows.slice(0,limit).flatMap(row=>{const item=map.get(String(row.menuItemId));return item?[{...item,score:row.score,reasonCodes:row.reasonCodes??[],explanation:row.explanation??""}]:[];});}
export async function getPersonalizedRecommendations(customerId:string,limit=10){const cache=await CustomerRecommendationCache.findOne({customerId,expiresAt:{$gt:new Date()}}).lean();if(!cache){const rebuilt=await rebuildCustomerRecommendationCache(customerId);return hydrate(rebuilt.items,limit);}return hydrate(cache.items,limit);}
export async function getTrendingRecommendations(limit=10,windowKey:"24h"|"7d"|"30d"|"all_time"="7d"){const rows=await RecommendationTrend.find({windowKey}).sort({score:-1}).limit(limit*2).lean();return hydrate(rows.map(row=>({menuItemId:row.menuItemId,score:row.score,reasonCodes:["trending"],explanation:`Trending over the last ${windowKey}.`})),limit);}
export async function getFrequentlyBoughtTogether(menuItemId:string,limit=6){const rows=await RecommendationAffinity.find({sourceItemId:menuItemId,relationType:"frequently_bought_together"}).sort({score:-1}).limit(limit*2).lean();return hydrate(rows.map(row=>({menuItemId:row.targetItemId,score:row.score,reasonCodes:["frequently_bought_together"],explanation:"Frequently ordered together by TRS customers."})),limit);}
export async function getCrossSellRecommendations(menuItemId:string,limit=6){const base=await MenuItem.findById(menuItemId).select("categoryId basePrice").lean();if(!base)return[];const affinities=await getFrequentlyBoughtTogether(menuItemId,limit);if(affinities.length)return affinities;const rows=await MenuItem.find({_id:{$ne:menuItemId},categoryId:{$ne:base.categoryId},isActive:true,isAvailable:true,deletedAt:null}).select("name slug imageUrl basePrice categoryId tags isBestseller preparationTimeMinutes").sort({isBestseller:-1,sortOrder:1}).limit(limit).lean();return rows.map((item,index)=>({...item,score:100-index,reasonCodes:["cross_sell"],explanation:"Complements your current selection."}));}
export async function getUpsellRecommendations(menuItemId:string,limit=6){const base=await MenuItem.findById(menuItemId).select("categoryId basePrice").lean();if(!base)return[];const maxPrice=Math.max(base.basePrice*1.8,base.basePrice+250);const rows=await MenuItem.find({_id:{$ne:menuItemId},categoryId:base.categoryId,basePrice:{$gt:base.basePrice,$lte:maxPrice},isActive:true,isAvailable:true,deletedAt:null}).select("name slug imageUrl basePrice categoryId tags isBestseller preparationTimeMinutes").sort({isBestseller:-1,basePrice:1}).limit(limit).lean();return rows.map((item,index)=>({...item,score:100-index,reasonCodes:["upsell"],explanation:"A premium option in the same category."}));}
type RecommendationPlacement="personalized"|"trending"|"frequently_bought_together"|"upsell"|"cross_sell"|"seasonal"|"time_based";
type RecommendationEventType="impression"|"click"|"add_to_cart"|"purchase"|"dismiss";
type RecommendationEventInput={customerId?:string|null;sessionId:string;menuItemId:string;sourceItemId?:string|null;placement:RecommendationPlacement;eventType:RecommendationEventType;score:number;orderId?:string|null;metadata:Record<string,unknown>};
export async function recordRecommendationEvent(input:RecommendationEventInput){const event=new RecommendationEvent({...input,customerId:input.customerId??null,sourceItemId:input.sourceItemId??null,orderId:input.orderId??null,occurredAt:new Date()});await event.save();return event;}
export async function getRecommendationAdminSummary(){const since=new Date(Date.now()-30*86400000);const[events,affinities,trends,caches,rules]=await Promise.all([RecommendationEvent.find({occurredAt:{$gte:since}}).lean(),RecommendationAffinity.countDocuments(),RecommendationTrend.find({windowKey:"7d"}).sort({score:-1}).limit(10).populate("menuItemId","name slug imageUrl").lean(),CustomerRecommendationCache.countDocuments({expiresAt:{$gt:new Date()}}),RecommendationRule.find().sort({createdAt:-1}).lean()]);const impressions=events.filter(e=>e.eventType==="impression").length;const clicks=events.filter(e=>e.eventType==="click").length;const carts=events.filter(e=>e.eventType==="add_to_cart").length;const purchases=events.filter(e=>e.eventType==="purchase").length;const placements=["personalized","trending","frequently_bought_together","upsell","cross_sell","seasonal","time_based"].map(placement=>{const subset=events.filter(e=>e.placement===placement);const imp=subset.filter(e=>e.eventType==="impression").length;const clk=subset.filter(e=>e.eventType==="click").length;return{placement,impressions:imp,clicks:clk,ctr:imp?round(clk/imp*100,2):0,addToCarts:subset.filter(e=>e.eventType==="add_to_cart").length,purchases:subset.filter(e=>e.eventType==="purchase").length};});return{periodDays:30,impressions,clicks,addToCarts:carts,purchases,ctr:impressions?round(clicks/impressions*100,2):0,conversionRate:impressions?round(purchases/impressions*100,2):0,affinities,cachedCustomers:caches,topTrending:trends,rules,placements};}
export async function recommendationReportCsv(){const summary=await getRecommendationAdminSummary();const lines=["Placement,Impressions,Clicks,CTR %,Add to carts,Purchases",...summary.placements.map(row=>[row.placement,row.impressions,row.clicks,row.ctr,row.addToCarts,row.purchases].join(","))];return lines.join("\n");}
