"use client";

import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCloudArrowUp, faCopy, faSearch, faTrash, faVideo } from "@fortawesome/free-solid-svg-icons";
import { PageHeader } from "@/components/admin/AdminPrimitives";
import { CustomActionModal } from "@/components/admin/CustomActionModal";
import type { MediaAsset } from "@/components/admin/media/MediaPicker";

type Api<T> = { data: T; message?: string };
export function AdminMediaLibraryClient() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [rows, setRows] = useState<MediaAsset[]>([]); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(false); const [remove, setRemove] = useState<MediaAsset | null>(null);
  const load = useCallback(async()=>{const response=await fetch(`/api/v1/admin/media${query.trim()?`?q=${encodeURIComponent(query.trim())}`:""}`,{cache:"no-store"});const json=await response.json() as Api<MediaAsset[]>;if(response.ok)setRows(json.data);else setMessage(json.message||"Unable to load media.");},[query]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer);},[load]);
  async function upload(files:FileList|null){if(!files?.length)return;setUploading(true);const body=new FormData();Array.from(files).forEach((file)=>body.append("files",file));body.append("category","library");const response=await fetch("/api/v1/admin/media",{method:"POST",body});const json=await response.json() as Api<MediaAsset[]>;setMessage(response.ok?json.message||"Uploaded.":json.message||"Upload failed.");setUploading(false);if(inputRef.current)inputRef.current.value="";if(response.ok)await load();}
  async function destroy(){if(!remove)return;const response=await fetch(`/api/v1/admin/media/${remove._id}`,{method:"DELETE"});const json=await response.json() as Api<null>;setMessage(json.message||"");setRemove(null);if(response.ok)await load();}
  return <div><PageHeader eyebrow="Content" title="Media Library" description="Upload once and reuse images or videos across CMS, gallery and future content modules." action={<button onClick={()=>inputRef.current?.click()} disabled={uploading} className="rounded-xl bg-[#C8102E] px-4 py-3 text-xs font-black text-white"><FontAwesomeIcon icon={faCloudArrowUp} className="mr-2"/>{uploading?"Uploading...":"Upload media"}</button>}/><input ref={inputRef} type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" onChange={(event)=>void upload(event.target.files)} className="hidden"/>{message&&<p className="mb-4 rounded-xl bg-[#fff0e8] px-4 py-3 text-sm font-semibold text-[#8d1b2a]">{message}</p>}<div className="mb-5 flex items-center gap-3 rounded-2xl border bg-white px-4"><FontAwesomeIcon icon={faSearch}/><input aria-label="Search media" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search file name, category or alt text" className="h-12 flex-1 outline-none"/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">{rows.map((asset)=><article key={asset._id} className="overflow-hidden rounded-2xl border bg-white"><div className="relative aspect-video bg-[#f5ede6]">{asset.mediaType==="image"?<Image src={asset.url} alt={asset.altText||asset.originalName} fill unoptimized className="object-cover"/>:<div className="grid h-full place-items-center text-4xl text-[#C8102E]"><FontAwesomeIcon icon={faVideo}/></div>}</div><div className="p-4"><p className="truncate text-sm font-black text-[#173044]">{asset.originalName}</p><p className="mt-1 text-[10px] text-[#756960]">{asset.category} · {(asset.sizeBytes/1024).toFixed(0)} KB</p><div className="mt-3 flex gap-2"><button onClick={()=>void navigator.clipboard.writeText(asset.url).then(()=>setMessage("Media URL copied."))} className="rounded-lg border px-3 py-2 text-xs font-black"><FontAwesomeIcon icon={faCopy}/></button><button onClick={()=>setRemove(asset)} className="rounded-lg border px-3 py-2 text-xs font-black text-red-700"><FontAwesomeIcon icon={faTrash}/></button></div></div></article>)}</div><CustomActionModal open={Boolean(remove)} title="Delete media file?" description="This removes the physical file. Make sure it is not currently used by CMS or Gallery." confirmLabel="Delete" tone="danger" onClose={()=>setRemove(null)} onConfirm={destroy}/></div>;
}
