export const endpoints = {
  auth: {
    me: "/api/v1/auth/me",
    login: "/api/v1/auth/login",
    signup: "/api/v1/auth/signup",
    logout: "/api/v1/auth/logout",
    refresh: "/api/v1/auth/refresh",
    forgotPassword: "/api/v1/auth/forgot-password",
    resetPassword: "/api/v1/auth/reset-password",
    verifyEmail: "/api/v1/auth/verify-email",
    verifyOtp: "/api/v1/auth/verify-otp",
  },
  menu: {
    categories: "/api/v1/menu/categories",
    items: "/api/v1/menu/items",
    item: (slug: string) => `/api/v1/menu/items/${slug}`,
    favourites: "/api/v1/menu/favourites",
  },
  cart: {
    current: "/api/v1/cart",
    items: "/api/v1/cart/items",
    item: (id: string) => `/api/v1/cart/items/${id}`,
    coupon: "/api/v1/cart/coupon",
  },
  checkout: {
    preview: "/api/v1/checkout/preview",
    placeOrder: "/api/v1/checkout/order",
    paymentIntent: "/api/v1/payments/create",
    verifyPayment: "/api/v1/payments/verify",
  },
  orders: {
    list: "/api/v1/orders",
    detail: (id: string) => `/api/v1/orders/${id}`,
    track: (orderNumber: string) => `/api/v1/orders/track/${orderNumber}`,
    cancel: (id: string) => `/api/v1/orders/${id}/cancel`,
    review: (id: string) => `/api/v1/orders/${id}/review`,
  },
  reservations: {
    list: "/api/v1/reservations",
    create: "/api/v1/reservations",
    detail: (id: string) => `/api/v1/reservations/${id}`,
    cancel: (id: string) => `/api/v1/reservations/${id}/cancel`,
  },
  rewards: {
    wallet: "/api/v1/rewards/wallet",
    transactions: "/api/v1/rewards/transactions",
    spin: "/api/v1/rewards/spin",
  },
  notifications: {
    list: "/api/v1/notifications",
    read: (id: string) => `/api/v1/notifications/${id}/read`,
    readAll: "/api/v1/notifications/read-all",
  },
  account: {
    profile: "/api/v1/account/profile",
    password: "/api/v1/account/password",
    preferences: "/api/v1/account/preferences",
  },
  admin: {
    dashboard: "/api/v1/admin/dashboard",
    orders: "/api/v1/admin/orders",
    menu: "/api/v1/admin/menu",
    inventory: "/api/v1/admin/inventory",
    customers: "/api/v1/admin/customers",
    reservations: "/api/v1/admin/reservations",
    rewards: "/api/v1/admin/rewards",
    coupons: "/api/v1/admin/coupons",
    offers: "/api/v1/admin/offers",
    reviews: "/api/v1/admin/reviews",
    notifications: "/api/v1/admin/notifications",
    reports: "/api/v1/admin/reports",
    analytics: "/api/v1/admin/analytics",
    roles: "/api/v1/admin/roles",
    settings: "/api/v1/admin/settings",
    activityLogs: "/api/v1/admin/activity-logs",
  },
} as const;
