"use client";
import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faChartLine, faDownload, faIndianRupeeSign, faReceipt, faRotate, faTags, faUtensils } from "@fortawesome/free-solid-svg-icons";

type Data = { summary:{grossSales:number;netSales:number;discounts:number;taxes:number;orders:number;itemsSold:number;refundedAmount:number;averageOrderValue:number;cancelledOrders:number;cancelledValue:number}; trend:Array<{period:string;grossSales:number;netSales:number;refunded:number;orders:number}>; payments:Array<{method:string;amount:number}>; orderTypes:Array<{type:string;orders:number;revenue:number}>; categories:Array<{category:string;quantity:number;revenue:number}>; items:Array<{name:string;quantity:number;revenue:number}>; details:Array<{id:string;createdAt:string;orderNumber:string;customer:string;orderMode:string;itemCount:number;paymentMethod:string;paymentBreakdown:Array<{method:string;amount:number}>;gross:number;discount:number;tax:number;refund:number;net:number;cashier:string;status:string;paymentStatus:string}> };
type ApiResponse<T>={success:boolean;message:string;data:T};
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
const dateInput=(date:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);
const empty:Data={summary:{grossSales:0,netSales:0,discounts:0,taxes:0,orders:0,itemsSold:0,refundedAmount:0,averageOrderValue:0,cancelledOrders:0,cancelledValue:0},trend:[],payments:[],orderTypes:[],categories:[],items:[],details:[]};
const paymentLabel=(row:Data["details"][number])=>row.paymentBreakdown?.length?[...new Set(row.paymentBreakdown.map(p=>p.method.toUpperCase()))].join(" + "):row.paymentMethod?.toUpperCase()||"—";
export function SalesAnalyticsClient(){
 const today=dateInput(new Date()); const [from,setFrom]=useState(today); const [to,setTo]=useState(today); const [data,setData]=useState<Data>(empty); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [query,setQuery]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/v1/admin/sales-analytics?from=${from}&to=${to}`,{cache:"no-store"});const json=await response.json() as ApiResponse<Data>;if(!response.ok)throw new Error(json.message);setData(json.data);}catch(e){setError(e instanceof Error?e.message:"Unable to load sales analytics.");}finally{setLoading(false)}},[from,to]);
 useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[load]);
 function preset(days:number){const end=new Date();const start=new Date(end);start.setDate(start.getDate()-(days-1));setFrom(dateInput(start));setTo(dateInput(end));}
 function yesterday(){const day=new Date();day.setDate(day.getDate()-1);const value=dateInput(day);setFrom(value);setTo(value);}
 function previousMonth(){const now=new Date();const first=new Date(now.getFullYear(),now.getMonth()-1,1);const last=new Date(now.getFullYear(),now.getMonth(),0);setFrom(dateInput(first));setTo(dateInput(last));}
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?data.details.filter(r=>[r.orderNumber,r.customer,r.cashier,r.status,paymentLabel(r)].join(" ").toLowerCase().includes(q)):data.details},[data.details,query]);
 function exportCsv(){const rows=[["Date","Order","Customer","Type","Items","Payment","Gross","Discount","Tax","Refund","Net","Cashier","Status"],...filtered.map(r=>[new Date(r.createdAt).toLocaleString("en-IN"),r.orderNumber,r.customer,r.orderMode,r.itemCount,paymentLabel(r),r.gross,r.discount,r.tax,r.refund,r.net,r.cashier,r.paymentStatus])];const csv=rows.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`trs-sales-${from}-to-${to}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <div className="min-w-0 space-y-6 overflow-hidden"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#C8102E]">Business intelligence</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em] text-[#173044] sm:text-4xl">Sales Analytics</h1><p className="mt-2 text-sm text-slate-500">Overall historical sales, collections and menu performance across POS, website and admin orders.</p></div><div className="flex flex-wrap gap-2"><button onClick={exportCsv} className="flex h-11 items-center gap-2 rounded-xl bg-[#173044] px-4 text-xs font-black text-white"><FontAwesomeIcon icon={faDownload}/>Export CSV</button><a href={`/api/v1/admin/sales-analytics/export?from=${from}&to=${to}`} className="flex h-11 items-center gap-2 rounded-xl border border-[#173044] px-4 text-xs font-black text-[#173044]"><FontAwesomeIcon icon={faDownload}/>Export Excel</a><button onClick={()=>window.print()} className="h-11 rounded-xl border border-[#C8102E] px-4 text-xs font-black text-[#C8102E]">Print / Save PDF</button></div></header>
 <section className="rounded-3xl border bg-white p-4 sm:p-5"><div className="flex flex-wrap gap-2">{[["Today",1],["Last 2 days",2],["Last 7 days",7],["Last 30 days",30]].map(([label,days])=><button key={String(label)} onClick={()=>preset(Number(days))} className="rounded-xl border px-3 py-2 text-xs font-black text-[#173044] hover:border-[#C8102E] hover:text-[#C8102E]">{label}</button>)}<button onClick={yesterday} className="rounded-xl border px-3 py-2 text-xs font-black">Yesterday</button><button onClick={()=>{const d=new Date();setFrom(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`);setTo(today)}} className="rounded-xl border px-3 py-2 text-xs font-black">This month</button><button onClick={previousMonth} className="rounded-xl border px-3 py-2 text-xs font-black">Previous month</button><div className="ml-auto flex flex-wrap gap-2"><input type="date" value={from} onChange={e=>setFrom(e.currentTarget.value)} className="h-10 rounded-xl border px-3 text-xs font-bold"/><input type="date" value={to} onChange={e=>setTo(e.currentTarget.value)} className="h-10 rounded-xl border px-3 text-xs font-bold"/><button onClick={()=>void load()} className="grid h-10 w-10 place-items-center rounded-xl bg-[#C8102E] text-white" aria-label="Refresh"><FontAwesomeIcon icon={faRotate}/></button></div></div></section>
 {error?<p className="rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>:null}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Net sales",money.format(data.summary.netSales),faIndianRupeeSign],["Orders",String(data.summary.orders),faReceipt],["Average order",money.format(data.summary.averageOrderValue),faChartLine],["Items sold",String(data.summary.itemsSold),faUtensils],["Gross sales",money.format(data.summary.grossSales),faIndianRupeeSign],["Discounts",money.format(data.summary.discounts),faTags],["Refunded",money.format(data.summary.refundedAmount),faRotate],["Cancelled",String(data.summary.cancelledOrders),faReceipt]].map(([label,value,icon])=><article key={String(label)} className="rounded-3xl border bg-white p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-[#C8102E]"><FontAwesomeIcon icon={icon as typeof faReceipt}/></span><p className="mt-4 text-2xl font-black text-[#173044]">{value as string}</p><p className="mt-1 text-[10px] font-black uppercase tracking-wider text-slate-500">{label as string}</p></article>)}</div>
 <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)]"><ChartCard title="Revenue trend" subtitle="Gross, net and refunded value over the selected period"><ResponsiveContainer width="100%" height={300}><AreaChart data={data.trend} margin={{top:10,right:10,left:-10,bottom:0}}><defs><linearGradient id="netFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#C8102E" stopOpacity={.25}/><stop offset="95%" stopColor="#C8102E" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="4 4"/><XAxis dataKey="period" tick={{fontSize:10}} minTickGap={24}/><YAxis tick={{fontSize:10}} tickFormatter={v=>`₹${Math.round(Number(v)/1000)}k`}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Legend/><Area type="monotone" dataKey="netSales" name="Net sales" stroke="#C8102E" fill="url(#netFill)" strokeWidth={3}/><Area type="monotone" dataKey="grossSales" name="Gross sales" stroke="#173044" fill="transparent" strokeWidth={2}/><Area type="monotone" dataKey="refunded" name="Refunded" stroke="#E8A53A" fill="transparent"/></AreaChart></ResponsiveContainer></ChartCard>
 <ChartCard title="Payment mix" subtitle="Split payments allocated to their actual methods"><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={data.payments} dataKey="amount" nameKey="method" innerRadius={62} outerRadius={95} paddingAngle={3}>{data.payments.map((_,i)=><Cell key={i} fill={["#C8102E","#173044","#E8A53A","#64748B"][i%4]}/>)}</Pie><Tooltip formatter={v=>money.format(Number(v))}/><Legend formatter={v=>String(v).toUpperCase()}/></PieChart></ResponsiveContainer></ChartCard></div>
 <div className="grid min-w-0 gap-5 xl:grid-cols-2"><ChartCard title="Orders trend" subtitle="Completed sale count by period"><ResponsiveContainer width="100%" height={280}><BarChart data={data.trend}><CartesianGrid strokeDasharray="4 4"/><XAxis dataKey="period" tick={{fontSize:10}} minTickGap={20}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="orders" name="Orders" fill="#C8102E" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Order-type mix" subtitle="Dine-in versus takeaway revenue"><ResponsiveContainer width="100%" height={280}><BarChart data={data.orderTypes}><CartesianGrid strokeDasharray="4 4"/><XAxis dataKey="type" tickFormatter={v=>String(v).replace("_"," ")}/><YAxis tickFormatter={v=>`₹${Math.round(Number(v)/1000)}k`}/><Tooltip formatter={v=>money.format(Number(v))}/><Bar dataKey="revenue" fill="#173044" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></ChartCard></div>
 <div className="grid min-w-0 gap-5 xl:grid-cols-2"><ChartCard title="Category sales" subtitle="Revenue by menu category"><ResponsiveContainer width="100%" height={Math.max(300,data.categories.length*38)}><BarChart data={data.categories} layout="vertical" margin={{left:20}}><CartesianGrid strokeDasharray="4 4"/><XAxis type="number" tickFormatter={v=>`₹${Math.round(Number(v)/1000)}k`}/><YAxis type="category" dataKey="category" width={105} tick={{fontSize:10}}/><Tooltip formatter={v=>money.format(Number(v))}/><Bar dataKey="revenue" fill="#C8102E" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Top-selling items" subtitle="Highest net item revenue"><div className="space-y-3">{data.items.map((item,index)=><div key={item.name} className="flex items-center justify-between rounded-2xl border p-4"><div className="min-w-0"><p className="truncate text-sm font-black text-[#173044]">{index+1}. {item.name}</p><p className="text-xs text-slate-500">{item.quantity} sold</p></div><b className="text-sm text-[#C8102E]">{money.format(item.revenue)}</b></div>)}</div></ChartCard></div>
 <section className="min-w-0 overflow-hidden rounded-3xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="text-xl font-black text-[#173044]">Sales history</h2><p className="text-sm text-slate-500">Latest 250 orders in the selected period.</p></div><input value={query} onChange={e=>setQuery(e.currentTarget.value)} placeholder="Search order, customer, cashier..." className="h-10 w-full rounded-xl border px-3 text-sm sm:w-72"/></div><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Date","Order","Customer","Type","Items","Payment","Gross","Discount","Tax","Refund","Net","Cashier","Status"].map(h=><th key={h} className="px-4 py-3 font-black uppercase">{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="px-4 py-3">{new Date(r.createdAt).toLocaleString("en-IN")}</td><td className="px-4 py-3 font-black">{r.orderNumber}</td><td className="px-4 py-3">{r.customer||"Guest"}</td><td className="px-4 py-3">{r.orderMode.replace("_"," ")}</td><td className="px-4 py-3">{r.itemCount}</td><td className="px-4 py-3 font-bold">{paymentLabel(r)}</td><td className="px-4 py-3">{money.format(r.gross)}</td><td className="px-4 py-3">{money.format(r.discount)}</td><td className="px-4 py-3">{money.format(r.tax)}</td><td className="px-4 py-3">{money.format(r.refund)}</td><td className="px-4 py-3 font-black">{money.format(r.net)}</td><td className="px-4 py-3">{r.cashier||"—"}</td><td className="px-4 py-3 uppercase">{r.paymentStatus}</td></tr>)}</tbody></table></div>{loading?<p className="p-5 text-center text-sm font-bold text-slate-400">Loading sales…</p>:null}</section></div>
}
function ChartCard({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <section className="min-w-0 overflow-hidden rounded-3xl border bg-white p-4 sm:p-6"><h2 className="text-xl font-black text-[#173044]">{title}</h2><p className="mb-5 mt-1 text-sm text-slate-500">{subtitle}</p>{children}</section>}
