"use client";

import { AnimatePresence, motion } from "framer-motion";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFilter, faRotate, faSearch } from "@fortawesome/free-solid-svg-icons";
import type { AdminOrderStatus } from "@/types/adminOrders";
import { tabs } from "@/components/admin/orders/admin-orders.api";
import { DateField, FilterSelect } from "@/components/admin/orders/AdminOrdersUi";

export function AdminOrdersControls({searchInput,onSearchInput,status,statusCounts,onStatus,showFilters,onToggleFilters,onRefresh,orderMode,onOrderMode,paymentStatus,onPaymentStatus,paymentMethod,onPaymentMethod,from,onFrom,to,onTo,onReset}:{searchInput:string;onSearchInput:(v:string)=>void;status:"all"|AdminOrderStatus;statusCounts:Record<string,number>;onStatus:(v:"all"|AdminOrderStatus)=>void;showFilters:boolean;onToggleFilters:()=>void;onRefresh:()=>void;orderMode:string;onOrderMode:(v:string)=>void;paymentStatus:string;onPaymentStatus:(v:string)=>void;paymentMethod:string;onPaymentMethod:(v:string)=>void;from:string;onFrom:(v:string)=>void;to:string;onTo:(v:string)=>void;onReset:()=>void}){
 return <div className="border-b border-[#eee4dc] p-4 sm:p-5"><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="relative min-w-0 flex-1 xl:max-w-xl"><FontAwesomeIcon icon={faSearch} className="absolute left-4 top-1/2 h-4 -translate-y-1/2 text-[#9b8e84]"/><input value={searchInput} onChange={e=>onSearchInput(e.target.value)} placeholder="Search order ID, customer, phone or email" className="h-12 w-full rounded-2xl border border-[#ded2c8] bg-white pl-11 pr-4 text-sm font-semibold outline-none transition focus:border-[#C8102E] focus:ring-4 focus:ring-[#C8102E]/10"/></div><div className="flex flex-wrap gap-2"><button onClick={onToggleFilters} className="inline-flex h-12 items-center gap-2 rounded-2xl border border-[#ded2c8] bg-white px-4 text-xs font-black text-[#183043]"><FontAwesomeIcon icon={faFilter}/> Filters</button><button onClick={onRefresh} className="inline-flex h-12 items-center gap-2 rounded-2xl bg-[#17384d] px-4 text-xs font-black text-white"><FontAwesomeIcon icon={faRotate}/> Refresh</button></div></div>
 <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{tabs.map(tab=><button key={tab.value} onClick={()=>onStatus(tab.value)} className={`shrink-0 rounded-full px-4 py-2 text-[10px] font-black uppercase tracking-wider transition ${status===tab.value?"bg-[#C8102E] text-white":"bg-[#f4ece6] text-[#776b63] hover:text-[#C8102E]"}`}>{tab.label} <span className="ml-1 opacity-75">{statusCounts[tab.value]??0}</span></button>)}</div>
 <AnimatePresence initial={false}>{showFilters&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><div className="mt-4 grid gap-3 border-t border-[#eee4dc] pt-4 sm:grid-cols-2 xl:grid-cols-6"><FilterSelect label="Order mode" value={orderMode} onChange={onOrderMode} options={["all","dine_in","takeaway"]}/><FilterSelect label="Payment status" value={paymentStatus} onChange={onPaymentStatus} options={["all","pending","paid","failed","refunded"]}/><FilterSelect label="Payment method" value={paymentMethod} onChange={onPaymentMethod} options={["all","cash","upi","card","online"]}/><DateField label="From" value={from} onChange={onFrom}/><DateField label="To" value={to} onChange={onTo}/><button onClick={onReset} className="mt-auto h-11 rounded-xl border border-[#ded2c8] bg-white text-xs font-black text-[#C8102E]">Reset filters</button></div></motion.div>}</AnimatePresence></div>
}
