"use client";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faChevronLeft, faChevronRight, faEye } from "@fortawesome/free-solid-svg-icons";
import type { AdminOrder } from "@/types/adminOrders";
import { dateTime, money, type SortField, type SortOrder } from "@/components/admin/orders/admin-orders.api";
import { Info, PaymentPill, SortableHead, StatusPill } from "@/components/admin/orders/AdminOrdersUi";

type Pagination={page:number;limit:number;total:number;pages:number};
export function AdminOrdersList({orders,pagination,loading,sortBy,sortOrder,onSort,onOpen,onPageChange}:{orders:AdminOrder[];pagination:Pagination;loading:boolean;sortBy:SortField;sortOrder:SortOrder;onSort:(field:SortField)=>void;onOpen:(id:string)=>void;onPageChange:(page:number)=>void}){
 return <><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1050px] text-left"><thead className="bg-[#fbf6f1] text-[9px] font-black uppercase tracking-[.16em] text-[#84776e]"><tr><SortableHead label="Order" field="orderNumber" current={sortBy} direction={sortOrder} onSort={onSort}/><SortableHead label="Date" field="createdAt" current={sortBy} direction={sortOrder} onSort={onSort}/><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Mode</th><SortableHead label="Status" field="status" current={sortBy} direction={sortOrder} onSort={onSort}/><SortableHead label="Payment" field="paymentStatus" current={sortBy} direction={sortOrder} onSort={onSort}/><SortableHead label="Total" field="grandTotal" current={sortBy} direction={sortOrder} onSort={onSort}/><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-[#eee4dc]">{orders.map(order=><tr key={order._id} className="transition hover:bg-[#fffaf6]"><td className="px-5 py-4"><b className="text-sm text-[#173044]">{order.orderNumber}</b><p className="mt-1 text-[10px] font-semibold text-[#958980]">{order.itemCount} item{order.itemCount===1?"":"s"}</p></td><td className="px-5 py-4 text-xs font-semibold text-[#6f645d]">{dateTime.format(new Date(order.createdAt))}</td><td className="px-5 py-4"><p className="text-xs font-extrabold text-[#183043]">{order.customerSnapshot.name}</p><p className="mt-1 text-[10px] font-semibold text-[#958980]">{order.customerSnapshot.phone||order.customerSnapshot.email||"—"}</p></td><td className="px-5 py-4 text-xs font-bold capitalize text-[#6f645d]">{order.orderMode.replace("_"," ")}</td><td className="px-5 py-4"><StatusPill status={order.status}/></td><td className="px-5 py-4"><PaymentPill status={order.paymentStatus} method={order.paymentMethod}/></td><td className="px-5 py-4 text-sm font-black text-[#173044]">{money.format(order.grandTotal)}</td><td className="px-5 py-4 text-right"><ViewButton id={order._id} onOpen={onOpen}/></td></tr>)}</tbody></table></div>
 <div className="grid gap-3 p-4 lg:hidden">{orders.map(order=><article key={order._id} className="rounded-2xl border border-[#e8ddd3] bg-white p-4"><div className="flex items-start justify-between gap-3"><div><b className="text-sm text-[#173044]">{order.orderNumber}</b><p className="mt-1 text-[10px] font-semibold text-[#958980]">{dateTime.format(new Date(order.createdAt))}</p></div><StatusPill status={order.status}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><Info label="Customer" value={order.customerSnapshot.name}/><Info label="Mode" value={order.orderMode.replace("_"," ")}/><Info label="Payment" value={`${order.paymentStatus} · ${order.paymentMethod}`}/><Info label="Total" value={money.format(order.grandTotal)}/></div><button onClick={()=>onOpen(order._id)} className="mt-4 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#17384d] text-[10px] font-black uppercase tracking-wider text-white"><FontAwesomeIcon icon={faEye}/> View order</button></article>)}</div>
 <div className="flex flex-col gap-3 border-t border-[#eee4dc] px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><p className="text-[11px] font-semibold text-[#83776e]">Showing {orders.length} of {pagination.total} orders</p><div className="flex items-center gap-2"><button disabled={pagination.page<=1||loading} onClick={()=>onPageChange(pagination.page-1)} className="grid h-9 w-9 place-items-center rounded-xl border border-[#ded2c8] disabled:opacity-40"><FontAwesomeIcon icon={faChevronLeft}/></button><span className="min-w-24 text-center text-xs font-black text-[#173044]">Page {pagination.page} / {Math.max(pagination.pages,1)}</span><button disabled={pagination.page>=pagination.pages||loading} onClick={()=>onPageChange(pagination.page+1)} className="grid h-9 w-9 place-items-center rounded-xl border border-[#ded2c8] disabled:opacity-40"><FontAwesomeIcon icon={faChevronRight}/></button></div></div></>
}
function ViewButton({id,onOpen}:{id:string;onOpen:(id:string)=>void}){return <button onClick={()=>onOpen(id)} className="inline-flex h-9 items-center gap-2 rounded-xl border border-[#ded2c8] px-3 text-[10px] font-black text-[#173044] hover:border-[#C8102E] hover:text-[#C8102E]"><FontAwesomeIcon icon={faEye}/> View</button>}
