"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRotateRight,faPlus,faSearch,faShieldHalved } from "@fortawesome/free-solid-svg-icons";
import { PageHeader,SectionCard,StatusBadge } from "@/components/admin/AdminPrimitives";
import { CustomActionModal } from "@/components/admin/CustomActionModal";
type Permission={_id:string;key:string;name:string;module:string};
type Role={_id:string;key:string;name:string;description:string;permissionIds:Permission[];isSystem:boolean;isActive:boolean};
type Staff={user:{_id:string;name:string;email:string;phone?:string;roleId:{_id:string;key:string;name:string};isActive:boolean;lastLoginAt?:string;createdAt:string};profile:{employeeCode:string;designation:string;department:string;employmentType:string;shiftName?:string}|null};
const input="h-11 w-full rounded-xl border border-[#e1d6cd] bg-white px-3 text-sm font-semibold text-[#173044] outline-none focus:border-[#C8102E]";
const blankStaff={name:"",email:"",phone:"",password:"",roleId:"",employeeCode:"",designation:"",department:"other",employmentType:"full_time",joiningDate:"",shiftName:"",emergencyContactName:"",emergencyContactPhone:"",address:"",notes:"",avatarUrl:""};
export function AdminStaffRolesClient({permissions}:{permissions:string[]}){
 const can=useCallback((p:string)=>permissions.includes(p),[permissions]); const [tab,setTab]=useState<"staff"|"roles">("staff"),[staff,setStaff]=useState<Staff[]>([]),[roles,setRoles]=useState<Role[]>([]),[allPermissions,setAllPermissions]=useState<Permission[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1),[staffForm,setStaffForm]=useState<typeof blankStaff|null>(null),[roleForm,setRoleForm]=useState<{id?:string;key:string;name:string;description:string;permissionIds:string[]}|null>(null),[action,setAction]=useState<{kind:"toggle_staff"|"delete_role";id:string;label:string;active?:boolean}|null>(null),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const jobs:Array<{kind:"staff"|"roles"|"permissions";request:Promise<Response>}>=[];if(can("users.read")){const qs=new URLSearchParams({page:String(page),limit:"20"});if(search.trim())qs.set("search",search.trim());jobs.push({kind:"staff",request:fetch(`/api/v1/admin/staff?${qs}`,{cache:"no-store"})})}if(can("roles.read"))jobs.push({kind:"roles",request:fetch("/api/v1/admin/roles",{cache:"no-store"})});if(can("permissions.read"))jobs.push({kind:"permissions",request:fetch("/api/v1/admin/permissions",{cache:"no-store"})});const responses=await Promise.all(jobs.map(job=>job.request));const payloads=await Promise.all(responses.map(response=>response.json()));const bad=responses.findIndex(response=>!response.ok);if(bad>=0)throw new Error(payloads[bad]?.message||"Unable to load administration data.");jobs.forEach((job,index)=>{const payload=payloads[index];if(job.kind==="staff"){setStaff(payload.data);setPages(payload.meta?.totalPages||1)}else if(job.kind==="roles")setRoles(payload.data);else setAllPermissions(payload.data)});if(!can("users.read")&&tab==="staff")setTab("roles")}catch(e){setError(e instanceof Error?e.message:"Unable to load data.")}finally{setLoading(false)}},[page,search,can,tab]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
 const grouped=useMemo(()=>Object.entries(allPermissions.reduce<Record<string,Permission[]>>((a,p)=>{(a[p.module]??=[]).push(p);return a},{})),[allPermissions]);
 async function request(url:string,options:RequestInit){setSaving(true);setError("");setNotice("");try{const r=await fetch(url,options),p=await r.json();if(!r.ok)throw new Error(p.message||"Request failed.");setNotice(p.message);setStaffForm(null);setRoleForm(null);setAction(null);await load()}catch(e){setError(e instanceof Error?e.message:"Request failed.")}finally{setSaving(false)}}
 async function saveStaff(){if(!staffForm)return;await request("/api/v1/admin/staff",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...staffForm,phone:staffForm.phone||undefined,joiningDate:staffForm.joiningDate||undefined})})}
 async function saveRole(){if(!roleForm)return;await request(roleForm.id?`/api/v1/admin/roles/${roleForm.id}`:"/api/v1/admin/roles",{method:roleForm.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(roleForm.id?{name:roleForm.name,description:roleForm.description,permissionIds:roleForm.permissionIds}:{key:roleForm.key,name:roleForm.name,description:roleForm.description,permissionIds:roleForm.permissionIds})})}
 return <div><PageHeader eyebrow="Administration" title="Staff & Roles" description="Manage staff accounts, access roles and module-level permissions." action={<button onClick={()=>void load()} className="h-11 rounded-xl border px-4 text-xs font-black"><FontAwesomeIcon icon={faArrowRotateRight}/> Refresh</button>}/>
 {error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}{notice&&<p className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{notice}</p>}
 <div className="mb-5 flex gap-2 rounded-2xl bg-[#f3ece6] p-1">{(["staff","roles"] as const).filter(x=>x==="staff"?can("users.read"):can("roles.read")).map(x=><button key={x} onClick={()=>setTab(x)} className={`flex-1 rounded-xl px-4 py-3 text-xs font-black capitalize ${tab===x?"bg-white text-[#C8102E] shadow":"text-[#6d625a]"}`}>{x==="staff"?"Staff":"Roles & Permissions"}</button>)}</div>
 {tab==="staff"?<SectionCard title="Staff directory" subtitle={loading?"Loading…":`${staff.length} staff shown`}><div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><FontAwesomeIcon icon={faSearch} className="absolute left-3 top-3.5 text-slate-400"/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search name, email or phone" className={`${input} pl-10`}/></div>{can("users.create")&&<button onClick={()=>setStaffForm({...blankStaff,roleId:roles.find(r=>r.isActive&&r.key!=="customer")?._id||""})} className="h-11 rounded-xl bg-[#173044] px-5 text-xs font-black text-white"><FontAwesomeIcon icon={faPlus}/> Add staff</button>}</div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead><tr className="border-b text-[10px] uppercase tracking-wider text-slate-500">{["Staff","Employee","Role","Department","Last login","Status","Action"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{staff.map(s=><tr key={s.user._id} className="border-b"><td className="px-3 py-4"><p className="font-black">{s.user.name}</p><p className="text-xs text-slate-500">{s.user.email}</p></td><td className="px-3 py-4"><p className="font-bold">{s.profile?.employeeCode||"—"}</p><p className="text-xs text-slate-500">{s.profile?.designation||"—"}</p></td><td className="px-3 py-4">{s.user.roleId?.name||"—"}</td><td className="px-3 py-4 capitalize">{s.profile?.department?.replaceAll("_"," ")||"—"}</td><td className="px-3 py-4 text-xs">{s.user.lastLoginAt?new Date(s.user.lastLoginAt).toLocaleString("en-IN"):"Never"}</td><td className="px-3 py-4"><StatusBadge value={s.user.isActive?"active":"inactive"}/></td><td className="px-3 py-4">{can("users.activate")&&<button onClick={()=>setAction({kind:"toggle_staff",id:s.user._id,label:s.user.name,active:s.user.isActive})} className="rounded-lg border px-3 py-2 text-xs font-black">{s.user.isActive?"Deactivate":"Activate"}</button>}</td></tr>)}</tbody></table></div><div className="mt-5 flex justify-between"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-2 text-xs font-black disabled:opacity-40">Previous</button><span className="text-xs font-bold">Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-2 text-xs font-black disabled:opacity-40">Next</button></div></SectionCard>:
 <SectionCard title="Roles and permissions" subtitle={`${roles.length} roles configured`}><div className="mb-4 flex justify-end">{can("roles.create")&&<button onClick={()=>setRoleForm({key:"",name:"",description:"",permissionIds:[]})} className="h-11 rounded-xl bg-[#173044] px-5 text-xs font-black text-white"><FontAwesomeIcon icon={faPlus}/> Create role</button>}</div><div className="grid gap-4 lg:grid-cols-2">{roles.map(r=><article key={r._id} className="rounded-2xl border p-5"><div className="flex items-start justify-between"><div><h3 className="font-black text-[#173044]">{r.name}</h3><p className="text-xs text-slate-500">{r.key}</p></div><StatusBadge value={r.isActive?"active":"inactive"}/></div><p className="mt-3 text-sm text-slate-600">{r.description||"No description."}</p><p className="mt-4 text-xs font-black text-[#C8102E]"><FontAwesomeIcon icon={faShieldHalved}/> {r.permissionIds.length} permissions</p><div className="mt-4 flex gap-2">{can("roles.update")&&<button onClick={()=>setRoleForm({id:r._id,key:r.key,name:r.name,description:r.description,permissionIds:r.permissionIds.map(p=>p._id)})} className="rounded-lg border px-3 py-2 text-xs font-black">Edit</button>}{can("roles.delete")&&!r.isSystem&&<button onClick={()=>setAction({kind:"delete_role",id:r._id,label:r.name})} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-black text-red-700">Delete</button>}</div></article>)}</div></SectionCard>}
 {staffForm&&<div className="fixed inset-0 z-[160] overflow-y-auto bg-black/50 p-4"><form onSubmit={e=>{e.preventDefault();void saveStaff()}} className="mx-auto max-w-3xl rounded-[28px] bg-[#fffdf9] p-6"><h2 className="text-xl font-black">Add staff member</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["name","Full name"],["email","Email"],["phone","Phone"],["password","Temporary password"],["employeeCode","Employee code"],["designation","Designation"],["shiftName","Shift name"]].map(([k,l])=><label key={k} className="text-xs font-black">{l}<input type={k==="password"?"password":"text"} required={["name","email","password","employeeCode"].includes(k)} value={staffForm[k as keyof typeof staffForm]} onChange={e=>setStaffForm({...staffForm,[k]:e.target.value})} className={`${input} mt-2`}/></label>)}<label className="text-xs font-black">Role<select required value={staffForm.roleId} onChange={e=>setStaffForm({...staffForm,roleId:e.target.value})} className={`${input} mt-2`}>{roles.filter(r=>r.isActive&&r.key!=="customer").map(r=><option key={r._id} value={r._id}>{r.name}</option>)}</select></label><label className="text-xs font-black">Department<select value={staffForm.department} onChange={e=>setStaffForm({...staffForm,department:e.target.value})} className={`${input} mt-2`}>{["management","cashier","kitchen","inventory","operations","marketing","other"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-black">Employment type<select value={staffForm.employmentType} onChange={e=>setStaffForm({...staffForm,employmentType:e.target.value})} className={`${input} mt-2`}>{["full_time","part_time","contract","intern"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setStaffForm(null)} className="h-11 rounded-xl border px-5 text-xs font-black">Cancel</button><button disabled={saving} className="h-11 rounded-xl bg-[#173044] px-5 text-xs font-black text-white">{saving?"Creating…":"Create staff"}</button></div></form></div>}
 {roleForm&&<div className="fixed inset-0 z-[160] overflow-y-auto bg-black/50 p-4"><form onSubmit={e=>{e.preventDefault();void saveRole()}} className="mx-auto max-w-4xl rounded-[28px] bg-[#fffdf9] p-6"><h2 className="text-xl font-black">{roleForm.id?"Edit role":"Create role"}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-black">Role name<input required value={roleForm.name} onChange={e=>setRoleForm({...roleForm,name:e.target.value})} className={`${input} mt-2`}/></label>{!roleForm.id&&<label className="text-xs font-black">Role key<input required pattern="[a-z][a-z0-9_]*" value={roleForm.key} onChange={e=>setRoleForm({...roleForm,key:e.target.value.toLowerCase().replace(/\s+/g,"_")})} className={`${input} mt-2`}/></label>}<label className="text-xs font-black sm:col-span-2">Description<textarea value={roleForm.description} onChange={e=>setRoleForm({...roleForm,description:e.target.value})} className="mt-2 min-h-24 w-full rounded-xl border p-3"/></label></div><div className="mt-5 space-y-4">{grouped.map(([module,ps])=><section key={module} className="rounded-2xl border p-4"><h3 className="text-sm font-black capitalize">{module}</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{ps.map(p=><label key={p._id} className="flex items-start gap-2 text-xs font-bold"><input type="checkbox" checked={roleForm.permissionIds.includes(p._id)} onChange={e=>setRoleForm({...roleForm,permissionIds:e.target.checked?[...roleForm.permissionIds,p._id]:roleForm.permissionIds.filter(id=>id!==p._id)})}/><span>{p.name}<small className="block font-medium text-slate-400">{p.key}</small></span></label>)}</div></section>)}</div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setRoleForm(null)} className="h-11 rounded-xl border px-5 text-xs font-black">Cancel</button><button disabled={saving||!roleForm.permissionIds.length} className="h-11 rounded-xl bg-[#173044] px-5 text-xs font-black text-white">{saving?"Saving…":"Save role"}</button></div></form></div>}
 <CustomActionModal open={!!action} title={action?.kind==="delete_role"?"Delete role":"Change staff status"} description={action?.kind==="delete_role"?`Delete ${action?.label}? This cannot be undone.`:`${action?.active?"Deactivate":"Activate"} ${action?.label}?`} tone={action?.kind==="delete_role"||action?.active?"danger":"default"} inputLabel={action?.kind==="toggle_staff"&&action?.active?"Reason":undefined} inputRequired={action?.kind==="toggle_staff"&&action?.active} loading={saving} onClose={()=>setAction(null)} onConfirm={async value=>{if(!action)return;if(action.kind==="delete_role")await request(`/api/v1/admin/roles/${action.id}`,{method:"DELETE"});else await request(`/api/v1/admin/staff/${action.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!action.active,deactivationReason:value})})}}/>
 </div>
}
