"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRotateLeft,faArrowRotateRight,faCheck,faFloppyDisk,faGear } from "@fortawesome/free-solid-svg-icons";
import { PageHeader,SectionCard } from "@/components/admin/AdminPrimitives";
import { CustomActionModal } from "@/components/admin/CustomActionModal";
type Setting={section:string;data:Record<string,unknown>;revision:number;updatedAt:string|null;updatedBy:{name?:string;email?:string}|null};
type ApiErrorDetail={field?:string;path?:string;message?:string};
type Api<T>={data:T;message:string;errors?:ApiErrorDetail[]};
const labels:Record<string,string>={business:"Business",ordering:"Ordering",loyalty:"Loyalty & Rewards",taxes:"Taxes & Charges",notifications:"Notifications",payments:"Payments",operations:"Operations",seo:"SEO & Analytics",integrations:"Integrations"};
const input="h-11 w-full rounded-xl border border-[#e1d6cd] bg-white px-3 text-sm font-semibold text-[#173044] outline-none focus:border-[#C8102E]";
const fieldLabels:Record<string,string>={orderingEnabled:"Enable Public Ordering & Customer Accounts",acceptingOrders:"Accept Public Online Orders",statusMessage:"Public Ordering Status Message",gstin:"GST Number (GSTIN)",phone:"Restaurant Contact Number",defaultTaxRate:"Default GST Rate %",pricesIncludeTax:"Menu Prices Include GST"};
function title(key:string){return fieldLabels[key]||key.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())}
export function AdminSettingsClient(){const [rows,setRows]=useState<Setting[]>([]),[section,setSection]=useState("business"),[draft,setDraft]=useState<Record<string,unknown>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[resetOpen,setResetOpen]=useState(false);
 const current=useMemo(()=>rows.find(x=>x.section===section),[rows,section]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/v1/admin/settings",{cache:"no-store"}),p=await r.json() as Api<Setting[]>;if(!r.ok)throw new Error(p.message||"Unable to load settings.");const available=p.data.filter(x=>x.section!=="reservations");setRows(available);const selected=available.find(x=>x.section==="business")||available[0];if(selected){setSection(selected.section);setDraft(structuredClone(selected.data))}}catch(e){setError(e instanceof Error?e.message:"Unable to load settings.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
 async function save(){if(!current)return;setSaving(true);setError("");setNotice("");try{const r=await fetch(`/api/v1/admin/settings/${section}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({data:draft,expectedRevision:current.revision})}),p=await r.json() as Api<Setting>;if(!r.ok){const detail=p.errors?.[0];const field=detail?.field||detail?.path;throw new Error(detail?.message?`${field?`${title(field)}: `:""}${detail.message}`:(p.message||"Unable to save settings."));}setNotice(p.message);setRows(old=>old.map(x=>x.section===section?p.data:x))}catch(e){setError(e instanceof Error?e.message:"Unable to save settings.")}finally{setSaving(false)}}
 async function reset(){setSaving(true);setError("");try{const r=await fetch(`/api/v1/admin/settings/${section}/reset`,{method:"POST"}),p=await r.json() as Api<Setting>;if(!r.ok){const detail=p.errors?.[0];const field=detail?.field||detail?.path;throw new Error(detail?.message?`${field?`${title(field)}: `:""}${detail.message}`:(p.message||"Unable to reset settings."));}setRows(old=>old.map(x=>x.section===section?p.data:x));setDraft(structuredClone(p.data.data));setNotice(p.message);setResetOpen(false)}catch(e){setError(e instanceof Error?e.message:"Unable to reset settings.")}finally{setSaving(false)}}
 function selectSection(nextSection:string){const next=rows.find(x=>x.section===nextSection);setSection(nextSection);setDraft(next?structuredClone(next.data):{})}
 function setValue(key:string,value:unknown){setDraft(old=>({...old,[key]:value}))}
 return <div><PageHeader eyebrow="Administration" title="System Settings" description="Control business rules, ordering, loyalty, notifications, payments, operations, SEO and integrations." action={<button onClick={()=>void load()} className="h-11 rounded-xl border px-4 text-xs font-black"><FontAwesomeIcon icon={faArrowRotateRight}/> Refresh</button>}/>{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}{notice&&<p className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700"><FontAwesomeIcon icon={faCheck}/> {notice}</p>}<div className="grid gap-5 xl:grid-cols-[250px_1fr]"><SectionCard title="Sections" subtitle="Configuration groups"><nav className="space-y-1">{rows.map(x=><button key={x.section} onClick={()=>selectSection(x.section)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs font-black ${section===x.section?"bg-[#173044] text-white":"text-[#5f554e] hover:bg-[#f5eee8]"}`}><FontAwesomeIcon icon={faGear}/>{labels[x.section]||title(x.section)}</button>)}</nav></SectionCard><SectionCard title={labels[section]||title(section)} subtitle={current?.updatedAt?`Last updated ${new Date(current.updatedAt).toLocaleString("en-IN")}`:"Using default configuration"}>{loading?<p className="py-16 text-center text-sm text-slate-500">Loading settings…</p>:<div><div className="grid gap-5 md:grid-cols-2">{Object.entries(draft).map(([key,value])=><Field key={key} name={key} value={value} onChange={v=>setValue(key,v)}/>)}</div><div className="mt-8 flex flex-col-reverse gap-2 border-t pt-5 sm:flex-row sm:justify-end"><button onClick={()=>setResetOpen(true)} className="h-11 rounded-xl border border-red-200 px-5 text-xs font-black text-red-700"><FontAwesomeIcon icon={faArrowRotateLeft}/> Reset section</button><button disabled={saving} onClick={()=>void save()} className="h-11 rounded-xl bg-[#173044] px-6 text-xs font-black text-white"><FontAwesomeIcon icon={faFloppyDisk}/> {saving?"Saving…":"Save changes"}</button></div></div>}</SectionCard></div><CustomActionModal open={resetOpen} title={`Reset ${labels[section]||title(section)} settings`} description="Restore this section to the project defaults? Existing values in this section will be replaced." tone="danger" confirmLabel="Reset settings" loading={saving} onClose={()=>setResetOpen(false)} onConfirm={reset}/></div>}
function Field({name,value,onChange}:{name:string;value:unknown;onChange:(v:unknown)=>void}){if(typeof value==="boolean")return <label className="flex min-h-16 items-center justify-between rounded-2xl border bg-white px-4"><span><b className="block text-sm text-[#173044]">{title(name)}</b><small className="text-slate-500">Enable or disable this option</small></span><input aria-label={title(name)} type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)} className="h-5 w-5 accent-[#C8102E]"/></label>;if(Array.isArray(value))return <label className="text-xs font-black text-[#173044] md:col-span-2">{title(name)}<textarea value={value.join(", ")} onChange={e=>onChange(e.target.value.split(",").map(x=>x.trim()).filter(Boolean))} className="mt-2 min-h-24 w-full rounded-xl border border-[#e1d6cd] bg-white p-3 text-sm font-semibold outline-none focus:border-[#C8102E]"/><small className="mt-1 block font-medium text-slate-500">Separate values with commas.</small></label>;if(typeof value==="number")return <label className="text-xs font-black text-[#173044]">{title(name)}<input type="number" value={Number.isFinite(value)?value:0} onChange={e=>onChange(Number(e.target.value))} className={`${input} mt-2`}/></label>;const long=String(value??"").length>80||name.toLowerCase().includes("description")||name.toLowerCase().includes("message");return <label className={`text-xs font-black text-[#173044] ${long?"md:col-span-2":""}`}>{title(name)}{long?<textarea value={String(value??"")} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-[#e1d6cd] bg-white p-3 text-sm font-semibold outline-none focus:border-[#C8102E]"/>:<input type={name.toLowerCase().includes("time")&&!name.toLowerCase().includes("minutes")?"time":"text"} value={String(value??"")} onChange={e=>onChange(e.target.value)} className={`${input} mt-2`}/>}</label>}
