import { requirePermission } from "@/lib/auth/session";
import { connectToDatabase } from "@/lib/db/mongoose";
import { AppError } from "@/lib/errors/AppError";
import { handleApiError } from "@/lib/errors/handleApiError";
import { SupplierIntelligenceSnapshot } from "@/models/SupplierIntelligenceSnapshot";
import { createInventoryReportPdf, createInventoryReportWorkbook } from "@/services/inventory-report-export.service";
import { getLatestSupplierIntelligenceRun } from "@/services/supplier-intelligence.service";
import { recordInventoryAudit } from "@/services/inventory-enterprise-events.service";
type Context={params:Promise<{format:string}>};
export async function GET(request:Request,context:Context){ try{ const actor=await requirePermission("reports.read"); const {format}=await context.params; if(format!=="xlsx"&&format!=="pdf") throw new AppError("Supplier export format must be xlsx or pdf.",400); const url=new URL(request.url); await connectToDatabase(); const run=url.searchParams.get("runId")?{_id:url.searchParams.get("runId")} : await getLatestSupplierIntelligenceRun(); if(!run) throw new AppError("Generate supplier intelligence before exporting.",404); const snapshots=await SupplierIntelligenceSnapshot.find({runId:run._id}).sort({overallScore:-1,totalSpend:-1}).lean(); const rows=snapshots.map(row=>({supplier:row.supplierName,code:row.supplierCode,grade:row.grade,preferredSupplier:row.preferredSupplier,overallScore:row.overallScore,totalSpend:row.totalSpend,purchaseOrders:row.purchaseOrderCount,onTimeDeliveryPercent:row.onTimeDeliveryPercent,averageLeadTimeDays:row.averageLeadTimeDays,averageDelayDays:row.averageDelayDays,fillRatePercent:row.fillRatePercent,rejectionRatePercent:row.rejectionRatePercent,qualityScore:row.qualityScore,purchasePriceVariancePercent:row.purchasePriceVariancePercent,returnValue:row.returnValue,recommendation:row.recommendation})); const title="Supplier Performance Scorecards & Recommendations"; const bytes=format==="xlsx"?await createInventoryReportWorkbook({title,reportType:"supplier_intelligence",rows}):await createInventoryReportPdf({title,reportType:"supplier_intelligence",rows}); await recordInventoryAudit({actorUserId:actor.id,action:"supplier.intelligence_exported",entityType:"SupplierIntelligenceRun",entityId:String(run._id),description:`Supplier intelligence exported as ${format.toUpperCase()}.`,metadata:{format,rowCount:rows.length}}); return new Response(bytes as BodyInit,{headers:{"content-type":format==="xlsx"?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"application/pdf","content-disposition":`attachment; filename="supplier-intelligence.${format}"`,"cache-control":"private, no-store"}}); }catch(error){return handleApiError(error);} }
