"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import { faArrowRotateLeft, faCreditCard, faIndianRupeeSign, faMagnifyingGlass, faReceipt } from "@fortawesome/free-solid-svg-icons";
import { CustomActionModal } from "@/components/admin/CustomActionModal";
import { PageHeader, SectionCard, StatusBadge } from "@/components/admin/AdminPrimitives";

import { useRealtimeRefresh } from "@/hooks/useRealtimeRefresh";

type Payment = {
  _id: string; providerOrderId: string; providerPaymentId?: string; amount: number; amountRefunded: number;
  currency: string; status: string; method?: string; email?: string; contact?: string; createdAt: string;
  failureDescription?: string; orderId?: { orderNumber?: string; grandTotal?: number; paymentStatus?: string };
  customerId?: { name?: string; email?: string; phone?: string };
};
type ApiResult = { data: { payments: Payment[]; pagination: { page: number; pages: number; total: number } }; message?: string };
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(value || 0);

export function AdminPaymentsClient({ canRefund }: { canRefund: boolean }) {
  const [rows, setRows] = useState<Payment[]>([]), [loading, setLoading] = useState(true), [searchInput, setSearchInput] = useState(""), [search, setSearch] = useState(""), [status, setStatus] = useState(""), [page, setPage] = useState(1), [pages, setPages] = useState(1), [total, setTotal] = useState(0);
  const [refund, setRefund] = useState<Payment | null>(null), [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ page: String(page), limit: "25" }); if (search) params.set("search", search); if (status) params.set("status", status); const response = await fetch(`/api/v1/admin/payments?${params}`, { cache: "no-store" }); const json = await response.json() as ApiResult; if (!response.ok) throw new Error(json.message || "Unable to load payments."); setRows(json.data.payments); setPages(json.data.pagination.pages || 1); setTotal(json.data.pagination.total); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load payments."); } finally { setLoading(false); } }, [page, search, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useRealtimeRefresh({ events: ["payment.updated", "order.payment_updated"], onEvent: () => load() });
  useEffect(() => { const timer = window.setTimeout(() => { setSearch(searchInput.trim()); setPage(1); }, 300); return () => window.clearTimeout(timer); }, [searchInput]);
  const totals = useMemo(() => ({ captured: rows.filter(x => x.status === "captured").reduce((a, b) => a + b.amount, 0), refunded: rows.reduce((a, b) => a + (b.amountRefunded || 0), 0), failed: rows.filter(x => x.status === "failed").length }), [rows]);
  async function submitRefund(reason: string) { if (!refund) return; const response = await fetch(`/api/v1/admin/payments/${refund._id}/refund`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason }) }); const json = await response.json() as { message?: string }; if (!response.ok) throw new Error(json.message || "Refund failed."); setRefund(null); await load(); }
  return <div><PageHeader eyebrow="Finance" title="Payments" description="Monitor online transactions, failures, captured revenue and refunds from one place." />
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Transactions" value={String(total)} icon={faReceipt}/><Metric label="Captured on page" value={money(totals.captured)} icon={faIndianRupeeSign}/><Metric label="Refunded on page" value={money(totals.refunded)} icon={faArrowRotateLeft}/><Metric label="Failed on page" value={String(totals.failed)} icon={faCreditCard}/>
    </div>
    <div className="mb-5 grid gap-3 lg:grid-cols-[1fr_220px_auto]"><label className="flex items-center gap-2 rounded-xl border border-[#e8ddd3] bg-white px-3"><FontAwesomeIcon icon={faMagnifyingGlass}/><input value={searchInput} onChange={e=>setSearchInput(e.target.value)} placeholder="Order, payment, email or phone" className="w-full py-3 text-sm outline-none"/></label><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="rounded-xl border border-[#e8ddd3] bg-white px-3 text-sm"><option value="">All statuses</option>{["created","authorized","captured","failed","refund_pending","refunded","partially_refunded"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><button onClick={()=>void load()} className="rounded-xl border border-[#e8ddd3] bg-white px-4 py-3 text-xs font-black">Refresh</button></div>
    <SectionCard title="Payment transactions" subtitle={loading ? "Loading…" : `${total} transaction(s)`}>{error && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-sm"><thead><tr className="border-b text-[10px] uppercase tracking-wider text-slate-500">{["Order","Customer","Provider reference","Method","Amount","Status","Created","Action"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row._id} className="border-b border-[#f0e7df] last:border-0"><td className="px-3 py-4 font-black text-[#173044]">#{row.orderId?.orderNumber || "—"}</td><td className="px-3 py-4"><p className="font-bold">{row.customerId?.name || "Guest"}</p><p className="text-xs text-slate-500">{row.email || row.customerId?.email || row.contact || "—"}</p></td><td className="px-3 py-4 font-mono text-xs"><p>{row.providerPaymentId || "Pending"}</p><p className="text-slate-400">{row.providerOrderId}</p></td><td className="px-3 py-4 capitalize">{row.method || "razorpay"}</td><td className="px-3 py-4 font-black">{money(row.amount)}{row.amountRefunded>0&&<p className="text-xs text-red-600">Refunded {money(row.amountRefunded)}</p>}</td><td className="px-3 py-4"><StatusBadge value={row.status}/>{row.failureDescription&&<p className="mt-1 max-w-52 text-xs text-red-600">{row.failureDescription}</p>}</td><td className="px-3 py-4 text-xs text-slate-500">{new Date(row.createdAt).toLocaleString("en-IN")}</td><td className="px-3 py-4">{canRefund && ["captured","partially_refunded"].includes(row.status) && row.amountRefunded < row.amount ? <button onClick={()=>setRefund(row)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-black text-red-700">Refund</button> : <span className="text-xs text-slate-400">—</span>}</td></tr>)}</tbody></table>{!loading&&!rows.length&&<p className="py-12 text-center text-sm text-slate-500">No payments found.</p>}</div><div className="mt-5 flex items-center justify-between"><button disabled={page<=1} onClick={()=>setPage(x=>x-1)} className="rounded-lg border px-3 py-2 text-xs font-black disabled:opacity-40">Previous</button><span className="text-xs font-bold text-slate-500">Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(x=>x+1)} className="rounded-lg border px-3 py-2 text-xs font-black disabled:opacity-40">Next</button></div></SectionCard>
    <CustomActionModal open={!!refund} title="Refund payment" description={refund ? `Refund ${money(refund.amount - refund.amountRefunded)} for order #${refund.orderId?.orderNumber || "—"}.` : ""} inputLabel="Refund reason" inputRequired confirmLabel="Initiate refund" tone="danger" onClose={()=>setRefund(null)} onConfirm={submitRefund}/>
  </div>;
}
function Metric({label,value,icon}:{label:string;value:string;icon: IconDefinition}){return <div className="rounded-2xl border border-[#e8ddd3] bg-white p-4"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</p><FontAwesomeIcon icon={icon} className="text-[#C8102E]"/></div><p className="mt-3 text-2xl font-black text-[#173044]">{value}</p></div>}
