"use client";
import { financeApi } from "@/lib/api/finance-client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRotateRight, faChartLine, faDownload, faMoneyBillTrendUp, faScaleBalanced } from "@fortawesome/free-solid-svg-icons";
import { PageHeader, StatCard } from "@/components/admin/AdminPrimitives";

type Scenario="base"|"optimistic"|"conservative";
type Month={month:string;budgetRevenue:number;actualRevenue:number;forecastRevenue:number;revenueVariance:number;budgetExpenses:number;actualExpenses:number;forecastExpenses:number;expenseVariance:number;forecastProfit:number;forecastCashBalance:number};
type Snapshot={metrics:{budgetRevenue:number;actualRevenue:number;forecastRevenue:number;revenueVariance:number;budgetExpenses:number;actualExpenses:number;forecastExpenses:number;expenseVariance:number;budgetProfit:number;forecastProfit:number;projectedCashBalance:number;cashRunwayMonths:number;forecastAccuracy:number};monthly:Month[]};
type Budget={_id:string;name:string;department:string;scenario:Scenario;status:string;fiscalYear:number};
type ResponseData={snapshot:Snapshot;budgets:Budget[]};

const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value);
const signed=(value:number)=>`${value>=0?"+":""}${money(value)}`;
export function BudgetingForecastingClient(){
  const[fiscalYear,setFiscalYear]=useState(new Date().getUTCFullYear());const[scenario,setScenario]=useState<Scenario>("base");const[data,setData]=useState<ResponseData|null>(null);const[error,setError]=useState("");const[working,setWorking]=useState(false);
  const load=useCallback(async()=>{try{setError("");setData(await financeApi<ResponseData>(`/api/v1/admin/finance/budgeting-forecasting/summary?fiscalYear=${fiscalYear}&scenario=${scenario}&department=Company`));}catch(value){setError(value instanceof Error?value.message:"Unable to load budget forecast.");}},[fiscalYear,scenario]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function rebuild(){setWorking(true);try{await financeApi("/api/v1/admin/finance/budgeting-forecasting/rebuild",{method:"POST",body:JSON.stringify({fiscalYear,scenario,department:"Company",source:"manual"})});await load();}catch(value){setError(value instanceof Error?value.message:"Rebuild failed.");}finally{setWorking(false);}}
  const m=data?.snapshot.metrics;
  return <><PageHeader eyebrow="Phase 8 · Financial Management" title="Budgeting & Forecasting" description="Plan departmental budgets, compare actuals, model scenarios, forecast profit and monitor projected cash runway." action={<div className="flex flex-wrap gap-2"><select value={fiscalYear} onChange={(event)=>setFiscalYear(Number(event.target.value))} className="rounded-xl border bg-white px-4 py-3 text-xs font-black">{[fiscalYear-1,fiscalYear,fiscalYear+1].map((year)=><option key={year} value={year}>{year}</option>)}</select><select value={scenario} onChange={(event)=>setScenario(event.target.value as Scenario)} className="rounded-xl border bg-white px-4 py-3 text-xs font-black"><option value="base">Base</option><option value="optimistic">Optimistic</option><option value="conservative">Conservative</option></select><Link href={`/api/v1/admin/finance/budgeting-forecasting/report?fiscalYear=${fiscalYear}&scenario=${scenario}&department=Company`} prefetch={false} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-xs font-black"><FontAwesomeIcon icon={faDownload}/>Export CSV</Link><button disabled={working} onClick={()=>void rebuild()} className="inline-flex items-center gap-2 rounded-xl bg-[#173044] px-4 py-3 text-xs font-black text-white"><FontAwesomeIcon icon={faArrowRotateRight}/>{working?"Rebuilding…":"Rebuild"}</button></div>}/>
  {error?<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>:null}
  <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Forecast revenue" value={money(m?.forecastRevenue??0)} icon={faMoneyBillTrendUp} detail={`${signed(m?.revenueVariance??0)} vs budget`}/><StatCard label="Forecast expenses" value={money(m?.forecastExpenses??0)} icon={faScaleBalanced} detail={`${signed(m?.expenseVariance??0)} vs budget`}/><StatCard label="Forecast profit" value={money(m?.forecastProfit??0)} icon={faChartLine} detail={`${m?.forecastAccuracy??0}% budget alignment`}/><StatCard label="Projected cash" value={money(m?.projectedCashBalance??0)} icon={faScaleBalanced} detail={`${m?.cashRunwayMonths===999?"No burn":`${m?.cashRunwayMonths??0} months runway`}`}/></div>
  <section className="mt-6 overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="text-lg font-black">Monthly forecast</h2><p className="mt-1 text-sm text-slate-500">Budget, actual and scenario-adjusted outlook for each month.</p></div><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Month</th><th className="p-3">Budget revenue</th><th className="p-3">Forecast revenue</th><th className="p-3">Revenue variance</th><th className="p-3">Budget expenses</th><th className="p-3">Forecast expenses</th><th className="p-3">Forecast profit</th><th className="p-3">Cash balance</th></tr></thead><tbody>{(data?.snapshot.monthly??[]).map((item)=><tr key={item.month} className="border-t"><td className="p-3 font-black">{item.month}</td><td className="p-3">{money(item.budgetRevenue)}</td><td className="p-3">{money(item.forecastRevenue)}</td><td className="p-3 font-bold">{signed(item.revenueVariance)}</td><td className="p-3">{money(item.budgetExpenses)}</td><td className="p-3">{money(item.forecastExpenses)}</td><td className="p-3 font-black">{money(item.forecastProfit)}</td><td className="p-3 font-black">{money(item.forecastCashBalance)}</td></tr>)}</tbody></table></div></section>
  <section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-lg font-black">Budget plans</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(data?.budgets??[]).length?(data?.budgets??[]).map((budget)=><div key={budget._id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{budget.name}</p><p className="mt-1 text-xs text-slate-500">{budget.department} · {budget.scenario}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black uppercase">{budget.status}</span></div></div>):<p className="text-sm text-slate-500">No budget plans have been created for this fiscal year yet. Use the API to create the first company or departmental plan.</p>}</div></section></>;
}
