"use client";
import { useCallback, useEffect, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRotateRight, faBroom, faFloppyDisk, faTriangleExclamation } from "@fortawesome/free-solid-svg-icons";
import { PageHeader, SectionCard, StatusBadge } from "@/components/admin/AdminPrimitives";

type Settings = { workerConcurrency:number; maxRowsPerReport:number; artifactRetentionDays:number; failedJobRetentionDays:number; notificationOnSuccess:boolean; notificationOnFailure:boolean; emailDeliveryEnabled:boolean; queueWarningThreshold:number; staleWorkerMinutes:number };
type Monitor = { settings:Settings; jobs:Record<string,number>; deliveries:Record<string,number>; schedules:Record<string,number>; storage:{bytes:number;files:number}; staleProcessing:number; successRate:number; queueHealthy:boolean; recentFailures:Array<{_id:string;errorMessage:string;outputFilename:string;failedAt?:string;reportId?:{name?:string}|null}> };
const defaults:Settings={workerConcurrency:5,maxRowsPerReport:5000,artifactRetentionDays:30,failedJobRetentionDays:90,notificationOnSuccess:true,notificationOnFailure:true,emailDeliveryEnabled:true,queueWarningThreshold:100,staleWorkerMinutes:15};
const bytes=(value:number)=>value>=1048576?`${(value/1048576).toFixed(1)} MB`:value>=1024?`${(value/1024).toFixed(1)} KB`:`${value} B`;

export function ReportAutomationClient({canManage}:{canManage:boolean}) {
 const [data,setData]=useState<Monitor|null>(null),[settings,setSettings]=useState<Settings>(defaults),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/v1/admin/report-builder/automation",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.message||"Unable to load report automation.");setData(p.data);setSettings({...defaults,...p.data.settings});}catch(e){setError(e instanceof Error?e.message:"Unable to load report automation.");}finally{setLoading(false);}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function request(method:"PATCH"|"POST",body?:unknown){setWorking(true);setError("");setNotice("");try{const r=await fetch("/api/v1/admin/report-builder/automation",{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const p=await r.json();if(!r.ok)throw new Error(p.message||"Request failed.");setNotice(p.message||"Completed.");await load();}catch(e){setError(e instanceof Error?e.message:"Request failed.");}finally{setWorking(false)}}
 const cards=[["Active schedules",data?.schedules.active||0,"Currently enabled"],["Queued jobs",data?.jobs.queued||0,"Waiting for workers"],["Success rate",`${data?.successRate||0}%`,`${data?.jobs.completed||0} completed`],["Artifact storage",bytes(data?.storage.bytes||0),`${data?.storage.files||0} files`]] as const;
 return <div className="space-y-6"><PageHeader eyebrow="Phase 4.2.4 · Batch 4" title="Report Automation & Delivery" description="Monitor queue health, email delivery, generated-file retention and global scheduled-report controls." actions={<button onClick={()=>void load()} className="rounded-xl border bg-white px-4 py-2 text-xs font-black"><FontAwesomeIcon icon={faArrowRotateRight} className="mr-2"/>Refresh</button>}/>
 {error?<p className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>:null}{notice?<p className="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{notice}</p>:null}
 {loading?<SectionCard title="Loading"><p className="py-14 text-center font-bold text-slate-400">Loading automation health…</p></SectionCard>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,detail])=><article key={label} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase tracking-widest text-slate-400">{label}</p><p className="mt-3 text-3xl font-black text-[#173044]">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{detail}</p></article>)}</div>
 <SectionCard title="System health" description="Queue, worker-lock and delivery status."><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border p-4"><p className="text-xs font-black uppercase text-slate-400">Queue</p><div className="mt-3"><StatusBadge value={data?.queueHealthy?"healthy":"warning"}/></div><p className="mt-2 text-xs text-slate-500">{data?.staleProcessing||0} stale processing jobs</p></div><div className="rounded-2xl border p-4"><p className="text-xs font-black uppercase text-slate-400">Deliveries</p><p className="mt-3 text-2xl font-black">{data?.deliveries.sent||0} sent</p><p className="text-xs text-red-600">{data?.deliveries.failed||0} failed</p></div><div className="rounded-2xl border p-4"><p className="text-xs font-black uppercase text-slate-400">Failures</p><p className="mt-3 text-2xl font-black">{data?.jobs.failed||0}</p><p className="text-xs text-slate-500">{data?.jobs.cancelled||0} cancelled</p></div></div></SectionCard>
 <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><SectionCard title="Automation settings" description="Limits and retention are enforced by the worker and cleanup job."><form onSubmit={e=>{e.preventDefault();void request("PATCH",settings)}} className="grid gap-4 sm:grid-cols-2">{([ ["workerConcurrency","Worker concurrency"],["maxRowsPerReport","Maximum report rows"],["artifactRetentionDays","Artifact retention days"],["failedJobRetentionDays","Failed-job retention days"],["queueWarningThreshold","Queue warning threshold"],["staleWorkerMinutes","Stale worker minutes"]] as const).map(([key,label])=><label key={key} className="text-xs font-black">{label}<input disabled={!canManage} type="number" min="1" value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})} className="mt-2 h-11 w-full rounded-xl border px-3"/></label>)}<div className="sm:col-span-2 grid gap-3 sm:grid-cols-3">{([ ["emailDeliveryEnabled","Email delivery"],["notificationOnSuccess","Success notifications"],["notificationOnFailure","Failure notifications"]] as const).map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-xl border p-3 text-xs font-black"><input disabled={!canManage} type="checkbox" checked={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/>{label}</label>)}</div>{canManage?<div className="sm:col-span-2 flex flex-wrap gap-2"><button disabled={working} className="rounded-xl bg-[#C8102E] px-5 py-3 text-xs font-black text-white"><FontAwesomeIcon icon={faFloppyDisk} className="mr-2"/>Save settings</button><button type="button" disabled={working} onClick={()=>void request("POST")} className="rounded-xl border px-5 py-3 text-xs font-black"><FontAwesomeIcon icon={faBroom} className="mr-2"/>Clean expired outputs</button></div>:null}</form></SectionCard>
 <SectionCard title="Recent failures" description="Latest permanently failed report executions."><div className="space-y-3">{data?.recentFailures.map(row=><article key={row._id} className="rounded-2xl border border-red-100 bg-red-50 p-4"><p className="font-black text-red-800"><FontAwesomeIcon icon={faTriangleExclamation} className="mr-2"/>{row.reportId?.name||row.outputFilename||"Report job"}</p><p className="mt-1 text-xs font-bold text-red-700">{row.errorMessage||"Unknown failure"}</p></article>)}{!data?.recentFailures.length?<p className="py-10 text-center text-sm font-bold text-slate-400">No recent permanent failures.</p>:null}</div></SectionCard></div></>}</div>
}
