import { requirePermission } from "@/lib/auth/session";
import { connectToDatabase } from "@/lib/db/mongoose";
import { AppError } from "@/lib/errors/AppError";
import { handleApiError } from "@/lib/errors/handleApiError";
import { ExecutiveBISnapshot } from "@/models/ExecutiveBISnapshot";
import { ExecutiveBIReportRun } from "@/models/ExecutiveBIReportRun";
import { createInventoryReportPdf, createInventoryReportWorkbook } from "@/services/inventory-report-export.service";
import { recordInventoryAudit } from "@/services/inventory-enterprise-events.service";
type Context={params:Promise<{format:string}>};
export async function GET(request:Request,context:Context){ try{ const actor=await requirePermission("reports.read"); const {format}=await context.params; if(format!=="xlsx"&&format!=="pdf") throw new AppError("Executive BI export format must be xlsx or pdf.",400); const url=new URL(request.url); await connectToDatabase(); const run=url.searchParams.get("runId")?await ExecutiveBIReportRun.findById(url.searchParams.get("runId")).lean():await ExecutiveBIReportRun.findOne({status:"completed"}).sort({completedAt:-1}).lean(); if(!run) throw new AppError("Generate an Executive BI report before exporting.",404); const s=await ExecutiveBISnapshot.findOne({runId:run._id}).lean(); if(!s) throw new AppError("Executive BI snapshot was not found.",404); const rows=[{periodStart:s.periodStart,periodEnd:s.periodEnd,revenue:s.revenue,revenueChangePercent:s.revenueChangePercent,orderCount:s.orderCount,averageOrderValue:s.averageOrderValue,purchaseSpend:s.purchaseSpend,cogs:s.cogs,grossProfit:s.grossProfit,grossMarginPercent:s.grossMarginPercent,foodCostPercent:s.foodCostPercent,inventoryValue:s.inventoryValue,inventoryTurnover:s.inventoryTurnover,daysInventoryOutstanding:s.daysInventoryOutstanding,carryingCostEstimate:s.carryingCostEstimate,deadStockCost:s.deadStockCost,overstockCost:s.overstockCost,wastageCost:s.wastageCost,adjustmentLossCost:s.adjustmentLossCost,supplierPerformanceScore:s.supplierPerformanceScore,forecastConfidenceScore:s.forecastConfidenceScore,businessHealthScore:s.businessHealthScore,insights:s.insights.join(" | ")}]; const title="Executive Business Intelligence Report"; const bytes=format==="xlsx"?await createInventoryReportWorkbook({title,reportType:"executive_business_intelligence",rows}):await createInventoryReportPdf({title,reportType:"executive_business_intelligence",rows}); await recordInventoryAudit({actorUserId:actor.id,action:"executive.bi_exported",entityType:"ExecutiveBIReportRun",entityId:String(run._id),description:`Executive BI report exported as ${format.toUpperCase()}.`,metadata:{format}}); return new Response(bytes as BodyInit,{headers:{"content-type":format==="xlsx"?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"application/pdf","content-disposition":`attachment; filename="executive-bi.${format}"`,"cache-control":"private, no-store"}}); }catch(error){ return handleApiError(error); } }
