"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRotateRight, faDownload, faTriangleExclamation } from "@fortawesome/free-solid-svg-icons";
import { PageHeader, SectionCard } from "@/components/admin/AdminPrimitives";
import type { BusinessForecastResult } from "@/services/business-forecast.service";
const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value);
export function BusinessForecastClient(){
 const [lookbackDays,setLookbackDays]=useState(90); const [report,setReport]=useState<BusinessForecastResult|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const query=useMemo(()=>new URLSearchParams({lookbackDays:String(lookbackDays)}).toString(),[lookbackDays]);
 const load=useCallback(async(refresh=false)=>{setLoading(true);setError("");try{const response=await fetch(`/api/v1/admin/business-forecast?${query}&refresh=${refresh}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.message||"Unable to load forecast.");setReport(payload.data);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load forecast.");}finally{setLoading(false);}},[query]);
 useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[load]);
 const max=Math.max(0,...(report?.forecasts.slice(0,30).map(row=>row.revenue)??[]));
 return <div className="space-y-6"><PageHeader eyebrow="Phase 4.2.5" title="Business Forecasting" description="Directional 7, 30 and 90-day projections using recent trends, weekday seasonality and historical variability." actions={<div className="flex flex-wrap gap-2">{(["csv","xlsx","pdf"] as const).map(format=><a key={format} href={`/api/v1/admin/business-forecast?${query}&format=${format}`} className="rounded-xl border bg-white px-4 py-2 text-xs font-black uppercase"><FontAwesomeIcon icon={faDownload} className="mr-2"/>{format}</a>)}<button onClick={()=>void load(true)} disabled={loading} className="rounded-xl bg-[#173044] px-4 py-2 text-xs font-black text-white disabled:opacity-50"><FontAwesomeIcon icon={faArrowRotateRight} className="mr-2"/>Recalculate</button></div>}/>
 <SectionCard title="Forecast settings" description="Longer history improves seasonality and confidence calculations."><div className="flex flex-wrap items-end gap-4"><label className="text-xs font-black">Historical lookback<select value={lookbackDays} onChange={e=>setLookbackDays(Number(e.target.value))} className="mt-2 block h-11 rounded-xl border bg-white px-3"><option value={60}>60 days</option><option value={90}>90 days</option><option value={180}>180 days</option><option value={365}>365 days</option></select></label><button onClick={()=>void load(true)} className="h-11 rounded-xl bg-[#C8102E] px-5 text-xs font-black text-white">Apply & recalculate</button></div></SectionCard>
 {error&&<p className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}{loading&&<SectionCard title="Generating forecast"><p className="py-12 text-center font-bold text-slate-400">Analyzing historical orders and inventory cost…</p></SectionCard>}
 {!loading&&report&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-2xl bg-[#173044] p-5 text-white"><p className="text-xs font-black uppercase text-white/60">30-day revenue forecast</p><p className="mt-3 text-3xl font-black">{money(report.summary.forecast30Revenue)}</p><p className="mt-2 text-xs font-bold text-[#E8A53A]">{report.quality.score}% data quality</p></article>{report.horizons.map(row=><article key={row.days} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-slate-400">Next {row.days} days</p><p className="mt-3 text-2xl font-black text-[#173044]">{money(row.revenue)}</p><p className="mt-1 text-xs font-bold text-slate-500">{row.orders} orders · {money(row.foodCost)} food cost</p></article>)}</div>
 <div className={`rounded-2xl border p-4 ${report.quality.level==="low"?"border-amber-200 bg-amber-50":"border-emerald-200 bg-emerald-50"}`}><FontAwesomeIcon icon={faTriangleExclamation} className="mr-2"/><span className="text-sm font-bold">{report.quality.message}</span></div>
 <SectionCard title="Next 30 days" description="Projected revenue with uncertainty range."><div className="overflow-x-auto"><div className="flex min-w-[760px] items-end gap-2" style={{height:260}}>{report.forecasts.slice(0,30).map(row=><div key={row.date} className="flex min-w-0 flex-1 flex-col items-center"><div className="flex h-48 w-full items-end rounded-t bg-slate-50 px-1"><div title={`${row.date}: ${money(row.revenue)}`} className="w-full rounded-t bg-[#C8102E]" style={{height:`${max?Math.max(3,row.revenue/max*100):0}%`}}/></div><p className="mt-2 text-[9px] font-bold text-slate-500">{row.date.slice(5)}</p></div>)}</div></div></SectionCard>
 <div className="grid gap-6 xl:grid-cols-2"><SectionCard title="30-day cost outlook"><div className="space-y-4"><p className="flex justify-between font-bold"><span>Food cost</span><span>{money(report.summary.forecast30FoodCost)}</span></p><p className="flex justify-between font-bold"><span>Internal consumption value</span><span>{money(report.summary.forecast30InternalValue)}</span></p><p className="flex justify-between font-bold"><span>Historical 30-day revenue</span><span>{money(report.summary.recent30Revenue)}</span></p></div></SectionCard><SectionCard title="Forecast ranges"><div className="space-y-3">{report.horizons.map(row=><div key={row.days} className="rounded-xl border p-3"><p className="font-black">{row.days}-day projection</p><p className="text-sm text-slate-500">Expected {money(row.revenue)} · Range {money(row.lowerRevenue)}–{money(row.upperRevenue)}</p></div>)}</div></SectionCard></div></>}
 </div>;
}
